Add blog Post component
ya-pomogau/frontend pull request #100
Opened 2023-12-25 21:38 UTC by margo-yunanova

Проверить как выглядит компонент можно в сторибуке

2023-12-26 07:02 UTC, kspshnik requested changes

2023-12-26 07:02 UTC, kspshnik commented on src/shared/ui/post/Post.tsx
> +import styles from './styles.module.css';
Это плохое именование. Таких файлов будет стопиццот в проекте, легко потеряться. Лучше `post.module.css`

2023-12-26 07:02 UTC, kspshnik commented on src/shared/ui/post/Post.tsx
> +          <div key={i} className={styles['gallery-item']}>
Это **очень** плохая практика. Надо придумать вариант с отличающимися ключами, например можно добавлять уникальное поле (с помощью `nanoid`, `React.useId()` и т.п.) при _добавлении_ картинки.

2023-12-26 07:02 UTC, kspshnik commented on src/shared/ui/post/Post.tsx
> +          <div key={i} className={styles['gallery-item']}>
И да, @margo-yunanova , я понимаю, что это не ты :) Но поменять надо, тем не менее.

2023-12-26 07:02 UTC, kspshnik commented on src/shared/ui/post/Post.tsx
> +  images: { src: string; alt: string }[];
Элементы массива лучше сделать типом - он понадобится ещё и в месте добавления картинок.

2023-12-26 07:02 UTC, kspshnik commented on src/shared/ui/post/Post.tsx
> +  author: {
Возможно, это тоже лучше отдельно типизировать. Но надо проверить, используется ли такое сочетание ещё где-либо в проекте.

2023-12-29 09:25 UTC, margo-yunanova commented on src/shared/ui/post/Post.tsx
> +import styles from './styles.module.css';
Я так назвала, чтобы сохранить однообразие, все стили в других компонентах так названы.
Мне точно переименовывать?

2023-12-29 09:36 UTC, margo-yunanova commented on src/shared/ui/post/Post.tsx
> +          <div key={i} className={styles['gallery-item']}>
Я использовала индекс как ключ, потому что список фотографий у меня статический, и он никогда не переупорядочивается и не фильтруется. Если фотографии будут редактироваться, то компонент перерендерится весь, реакт не будет сравнивать его до и после.
Переделаю на id картинки, который буду получать в пропсах.

2023-12-29 09:52 UTC, kspshnik commented on src/shared/ui/post/Post.tsx
> +import styles from './styles.module.css';
Пока не надо с ходу. Послушаем мнение @INextYP

2023-12-29 09:53 UTC, kspshnik commented on src/shared/ui/post/Post.tsx
> +          <div key={i} className={styles['gallery-item']}>
Любое переупорядочивание массива === перерендер. Это вообще нельзя делать почти никогда.

2023-12-29 09:57 UTC, margo-yunanova commented on src/shared/ui/post/Post.tsx
> +  author: {
done

2023-12-29 10:01 UTC, margo-yunanova commented on src/shared/ui/post/Post.tsx
> +  images: { src: string; alt: string }[];
done

2023-12-29 10:19 UTC, margo-yunanova commented on src/shared/ui/post/Post.tsx
> +          <div key={i} className={styles['gallery-item']}>
В статье, которую [документация реакта](https://ru.legacy.reactjs.org/docs/lists-and-keys.html#:~:text=%D0%9C%D1%8B%C2%A0%D0%BD%D0%B5%C2%A0%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D1%83%D0%B5%D0%BC%20%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%20%D0%B8%D0%BD%D0%B4%D0%B5%D0%BA%D1%81%D1%8B%20%D0%BA%D0%B0%D0%BA%20%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%2C%20%D0%B5%D1%81%D0%BB%D0%B8%20%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA%20%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2%20%D0%BC%D0%BE%D0%B6%D0%B5%D1%82%20%D0%BF%D0%BE%D0%BC%D0%B5%D0%BD%D1%8F%D1%82%D1%8C%D1%81%D1%8F.) предлагает изучить по ключам https://robinpokorny.com/blog/index-as-a-key-is-an-anti-pattern/ 
есть как раз правила, при которых можно использовать индексы. Это как раз мой случай для картинок:
![image](https://github.com/ya-pomogau/frontend/assets/67325499/cd5ca093-2111-4eec-b326-7b10b918d94c)

2023-12-29 12:13 UTC, kspshnik commented on src/shared/ui/post/Post.tsx
> +          <div key={i} className={styles['gallery-item']}>
Второй пункт сомнителен, а третий не гарантирован.

2024-01-10 11:13 UTC, margo-yunanova commented on src/shared/ui/post/Post.tsx
> +import styles from './styles.module.css';
@INextYP , привет. Посмотри, пожалуйста, вопрос выше.

2024-01-10 11:53 UTC, INextYP commented on src/shared/ui/post/Post.tsx
> +import styles from './styles.module.css';
Не нужно переименовывать. Раз в проекте уже используется такая методика именования файлов со стилями - лучше придерживаться её.
Но обычно, в коммерческих больших проектах такие файлы называют также, как и компонент, к которому они относятся с припиской .module.scss или .css, т.е. если компонент у нас Post.tsx, то стили к нему - post.module.scss или .css :)

2024-01-10 16:42 UTC, margo-yunanova commented on src/shared/ui/post/Post.tsx
> +          <div key={i} className={styles['gallery-item']}>
done

2024-01-10 16:42 UTC, margo-yunanova commented on src/shared/ui/post/Post.tsx
> +import styles from './styles.module.css';
done

2024-01-11 19:17 UTC, INextYP approved these changes
Отлично!

2024-01-12 12:03 UTC, marussia1996 reviewed
Отличная работа!

2024-01-12 12:03 UTC, marussia1996 commented on src/shared/ui/post/post.stories.tsx
> +export const Default: Story = {
так и было задумано на некоторых постах не указывать кнопки удаления и редактирования?

2024-01-12 12:20 UTC, margo-yunanova commented on src/shared/ui/post/post.stories.tsx
> +export const Default: Story = {
Кнопки удаления и редактирования постов по макету доступны только у админов, истории моделируют разные кейсы - волонтера\реципиента, админа, лонгрид.

2024-01-12 12:32 UTC, marussia1996 commented on src/shared/ui/post/post.stories.tsx
> +export const Default: Story = {
ага, поняла)

2024-01-12 12:32 UTC, marussia1996 approved these changes

2024-01-12 15:00 UTC, margo-yunanova commented
@kspshnik , привет. Если нет больше вопросов замёрджишь?

2024-01-12 15:50 UTC, kspshnik approved these changes

2024-01-12 15:51 UTC, merged