feature: добавлено отображение кнопок в заявках в соответствии с правами администратора
ya-pomogau/frontend pull request #104
Opened 2024-01-02 14:27 UTC by SergeyKukhtalevV

Добрый день!
Прошу проверить задачу 2 (Если у обычного администратора нет прав на подтверждение/ блокировку и т.д., то не давать ему это сделать (можно создать мокового админа и поэкспериментировать с ним)
Также хочу обратить внимание на особенность реализации: если у администратора нет прав на подтверждения заявок, то кнопку "заблокировать" я тоже сделал неактивной. 
@kspshnik 
@lexanikitin 
@INextYP

2024-01-11 14:25 UTC, kspshnik requested changes
А зачем пропсами прокидывать-то? :)

2024-01-11 14:25 UTC, kspshnik commented on src/widgets/user-card/components/recipient-actions.tsx
> +  isAdminHavePermissionApprove: boolean;
Не, не надо так :)
У нас есть юзверь в сторе. Если он - админ, у него массив полномочий в комплекте :)
Там надо чекать, а не таскать пропсами.

2024-01-11 14:25 UTC, kspshnik commented on src/widgets/user-card/index.tsx
> +interface IPermission {
А ты уверен в типизации разрешений?

2024-01-11 19:07 UTC, INextYP commented on src/widgets/user-card/index.tsx
> +interface IPermission {
По текущим правилам проекта перед названием интерфейса буква `I` не нужна

2024-01-11 19:07 UTC, INextYP commented on src/widgets/user-card/index.tsx
> +  useEffect(() => {
старайся не слеплять код, уменьшается читабельность

2024-01-11 19:07 UTC, INextYP commented on src/widgets/user-card/index.tsx
> +  const adminData: any = useAppSelector((state) => state.user.data);
**NOT ANY PLS** ^)

2024-01-11 19:07 UTC, INextYP commented on src/widgets/user-card/index.tsx
>    role?: 'volunteer' | 'recipient' | 'admin' | 'master';
Договоритесь с @lexanikitin чтобы кто-то вынес это. Очень много повторений

2024-01-11 19:07 UTC, margo-yunanova commented on src/widgets/user-card/index.tsx
> +  }, [adminPermissions]);
Привет.
Тебе не нужен useEffect, т.к. `adminPermissions` вычисляется один раз при вызове компонента, а права пользователя не меняются в процессе жизни компонента, поэтому перерендера никогда не будет. Если ты хотел кешировать вычисления, то нужно использовать useMemo, но ты перебираешь массив `adminPermissions` в котором мало элементов, поэтому можно и без него обойтись.

"Магические значения" с которыми сравнивается `per.id` хорошо бы заменить на понятные имена, мне кажется в проекте уже должен быть какой-нибудь enum с именами прав.

Метод `map` используется когда нам нужно получить новый массив с измененными данными (сейчас ты возвращаешь массив с true по количеству элементов массива, который нигде не используется), если результат `map` не используется необходимо использовать `forEach` или `for...of`. В твоём случае лучше всего подойдёт метод `some`, с его помощью можно проверить, есть ли в  `adminPermissions` хоть один элемент удовлетворяющий условию.

Т.к. в данном случае перерендер не происходит, нет необходимости создавать состояние для `approvePermission` и `keysPermission`, достаточно создать константы, которым присвоить результат вызова `some`.

2024-01-12 20:39 UTC, SergeyKukhtalevV commented on src/widgets/user-card/components/recipient-actions.tsx
> +  isAdminHavePermissionApprove: boolean;
Я не переделывал код, что был до меня, а дополнял: чтобы все полномочия проверялись в одном родительском компоненте и передавались дочерним.
Можете пояснить, в чем минусы моего решения?

2024-01-12 20:45 UTC, SergeyKukhtalevV commented on src/widgets/user-card/index.tsx
> +interface IPermission {
Поскольку единообразие в проекте отсутствует, и посовещавшись с коллегой, я брал за истину значения в сторе редакса:
![image](https://github.com/ya-pomogau/frontend/assets/106655509/3a57cb5b-97a6-463b-bc00-69902a70f89e)

2024-01-12 20:47 UTC, SergeyKukhtalevV commented on src/widgets/user-card/index.tsx
> +interface IPermission {
странное решение, но ок

2024-01-12 20:47 UTC, SergeyKukhtalevV commented on src/widgets/user-card/index.tsx
> +  useEffect(() => {
Ок

2024-01-12 21:42 UTC, SergeyKukhtalevV commented on src/widgets/user-card/index.tsx
> +  const adminData: any = useAppSelector((state) => state.user.data);
Не могу иначе:
В сторе редакса объект с привилегиями редакса выглядит так:
![image](https://github.com/ya-pomogau/frontend/assets/106655509/c61bd193-22da-4c1f-9ea6-8ca3d38871d8)

А в файле с типизацией объекта с привилегиями админа в стора так:
![image](https://github.com/ya-pomogau/frontend/assets/106655509/1ce76169-accd-4290-87b1-6ac36f41d657)
И у меня возникает абсолютное недопонимание, как это поправить и не "положить" проект

2024-01-12 22:06 UTC, SergeyKukhtalevV commented on src/widgets/user-card/index.tsx
> +  }, [adminPermissions]);
Привет!
Спасибо за подробное ревью.
С useEffect cогласен.
Магические значения использовать не могу, т.к. в сторре редакса объект с привилегиями сильно отличается от его же типизации в проекте:
![image](https://github.com/ya-pomogau/frontend/assets/106655509/97f91dd1-8532-40f1-addd-1fb30157c1db)

export enum AdminPermission {
  CONFIRMATION = 'confirm users',
  TASKS = 'create tasks',
  KEYS = 'give keys',
  CONFLICTS = 'resolve conflicts',
  BLOG = 'write the blog',
  CATEGORIES = 'change categories',
}

2024-01-13 05:41 UTC, SergeyKukhtalevV commented on src/widgets/user-card/index.tsx
>    role?: 'volunteer' | 'recipient' | 'admin' | 'master';
Ок

2024-01-13 06:27 UTC, kspshnik commented on src/widgets/user-card/components/recipient-actions.tsx
> +  isAdminHavePermissionApprove: boolean;
Лишние пропсы. Лишние пропсы - лишний шанс на перерендеры. Их надо вычислять в родителе из того же стора.
Зачем?

2024-01-13 06:28 UTC, kspshnik commented on src/widgets/user-card/index.tsx
> +interface IPermission {
Это всё переделается, но ОК, пока так. А вообще там `enum`

2024-01-13 06:29 UTC, kspshnik commented on src/widgets/user-card/index.tsx
> +interface IPermission {
@INextYP я бы тупо писал `Interface` в конце - @SergeyKukhtalevV прав, будут совпадения имён.

2024-01-13 06:30 UTC, kspshnik commented on src/widgets/user-card/index.tsx
> +  const adminData: any = useAppSelector((state) => state.user.data);
Попробуй выводить или вообще на задать тип и посмотри, какой тип присвоит TS?

2024-01-13 06:31 UTC, kspshnik commented on src/widgets/user-card/index.tsx
> +  }, [adminPermissions]);
Надо поменять в моковых данных. Или не надо, скоро бэкенд будет. Но там в итоге будут не записи из БД, а `enum`. В принципе, сам список разрешений - это массив строк.

2024-01-13 06:42 UTC, SergeyKukhtalevV commented on src/widgets/user-card/components/recipient-actions.tsx
> +  isAdminHavePermissionApprove: boolean;
Не хотелось дублировать один и тот же код в дочерних элементах

2024-01-13 06:46 UTC, SergeyKukhtalevV commented on src/widgets/user-card/index.tsx
> +  const adminData: any = useAppSelector((state) => state.user.data);
Пробовал, UserInfo | null. Но дальше идет ошибка уже для типизации объекта adminPermissions, т.к. есть конфликт между объектом permissions в сторе и типизацией в проекте (выше на скриншотах)

2024-01-13 06:49 UTC, SergeyKukhtalevV commented on src/widgets/user-card/index.tsx
> +interface IPermission {
Совпадения уже есть =((((

2024-01-14 15:16 UTC, INextYP commented on src/widgets/user-card/index.tsx
> +  const adminData: any = useAppSelector((state) => state.user.data);
@kspshnik @SergeyKukhtalevV  тут явно получается ошибка.
Ты пытаешься в переменную `adminPermissions` положить `Array<T> | null`
```
enum AdminPermission {
  CONFIRMATION = 'confirm users',
  TASKS = 'create tasks',
  KEYS = 'give keys',
  CONFLICTS = 'resolve conflicts',
  BLOG = 'write the blog',
  CATEGORIES = 'change categories',
}[] | null
```

НО

при этом, ты говоришь `TS` что в этой переменной у тебя якобы будет лежать `Array<T>`
```
interface Permission {
  id: number;
  name: string;
}[]
```

2024-01-14 15:16 UTC, INextYP commented on src/widgets/user-card/index.tsx
>        if (per.id === 1) {
Нет. Вот тут как раз посмотри на enum `AdminPermission`.
@kspshnik Жень. Это перечисление соответствует действительности? Можно будет написать нормальную логику проверки доступов для админа, используя `AdminPermission`?

2024-01-14 19:48 UTC, kspshnik commented on src/widgets/user-card/index.tsx
>        if (per.id === 1) {
Я бы так не делал.
Вот сниппет с бэка как-раз за проверку:

```ts
accessControl.rights.every((grant) => user.permissions.includes(grant))

```

, где `accessControl.rights` - массив **требуемых** прав ресурса, а `user.permissions` - массив *наличных* грантов юзверя.

2024-01-15 20:37 UTC, SergeyKukhtalevV commented on src/widgets/user-card/index.tsx
> +  const adminData: any = useAppSelector((state) => state.user.data);
Ок, изменил.

2024-01-16 09:51 UTC, vladko-89 reviewed
Привет! Кое-что нужно подправить

2024-01-16 09:51 UTC, vladko-89 commented on src/widgets/user-card/index.tsx
> +  useMemo(() => {
useMemo так не используют. Хук нужен для того чтобы закешировать результат функции, по сути функция должна что-то вернуть и это что-то мемоизируется и при перерендере, если зависимости хука не менялись, переменная не пересчитывается. У тебя здесь функция мутирует локальное состояние этот хук здесь вовсе не нужен. Здесь скорее можно было бы посмотреть на useCallback но и то он здесь бесполезен, поскольку будет работать только если текущая функция будет прокидываться пропсами в нижестоящий компонент завернутый в свою очередь в React.memo.

В целом, хук целесообразно использовать когда функция выполняет дорогостоящие вычисления. Когда у тебя массив перебирается из 5 значений это не совсем то. Использование хуков само по себе не бесплатное мероприятие и текущий пересчет даже менее затратный чем сама инициализация хука

https://react.dev/reference/react/useMemo

Почитай про мемоизацию и глянь вот этот видосик, сразу будет понятно о чем тут речь https://www.youtube.com/watch?v=yEPukn2rS28&t=33s

2024-01-16 09:51 UTC, vladko-89 commented on src/widgets/user-card/index.tsx
> +  const [approvePermission, setApprovePermission] = useState(false);
В карточке пользователя и в нижестоящих компонентах у тебя нет возможности менять эти параметры, а следовательно и нет необходимости держать их в локальных состояниях. Вынеси их в обычные переменные по принципу

```
const approvePermission = permission.some( item => per === AdminPermission.CONFIRMATION)
```

2024-01-16 09:51 UTC, vladko-89 commented on src/widgets/user-card/index.tsx
> +  const adminData = useAppSelector((state) => state.user.data);
Подключаешь в компонент весь объект пользователя, он огромен и при этом используешь только малую часть ключ `permissions`.  Сейчас получается что если какие то данные в user.data поменяются, у тебя будет перерендер трех компонент - текущего и пары дочерних, а такой исход это плохо. 

Из стора нужно забирать только то что собираешься использовать, а именно ключ permissions.

Кроме того, в прошлых ревью @kspshnik правильно заметил что стор в частности для того и нужен, чтобы подключится именно в компонентах использования данных, а не в их родителях чтобы потом передавать что-то лишними пропсами. 

Опять же, если ключ в сторе поменяется, то будет перерендер трех компонент. С этой точки зрения, стоит подумать над выносом `permissions` из стора в дочерних компонентах и рассчитать значения так как указал в комментарии к коду ниже.

2024-01-16 10:15 UTC, kspshnik commented on src/widgets/user-card/index.tsx
> +  const [approvePermission, setApprovePermission] = useState(false);
Я бы прямо в селекторе собрал объект с ключом-правом и значением - его наличием, с помощью `.reduce()` - и голову себе об это не морочил :)

2024-01-17 19:00 UTC, SergeyKukhtalevV commented on src/widgets/user-card/index.tsx
> +  const adminData = useAppSelector((state) => state.user.data);
Спасибо за обстоятельное ревью!
Поправил.

2024-01-17 19:27 UTC, kspshnik requested changes

2024-01-17 19:27 UTC, kspshnik commented on src/widgets/user-card/components/recipient-actions.tsx
> +  const approvePermission = adminPermissions?.some(
Точно тут не `.includes()` надо?

2024-01-17 19:27 UTC, kspshnik commented on src/widgets/user-card/components/volonteer-actions.tsx
> +  const approvePermission = adminPermissions?.some(
Аналогично предыдущему, и ко всем сомам :) в этом водоёме :)

2024-01-17 20:55 UTC, SergeyKukhtalevV commented on src/widgets/user-card/components/volonteer-actions.tsx
> +  const approvePermission = adminPermissions?.some(
готово

2024-01-18 11:55 UTC, INextYP approved these changes
Отличная работа!

2024-01-20 14:50 UTC, vladko-89 approved these changes

2024-01-22 08:25 UTC, merged