Функционал Администраторов. Отображение счетчиков на вкладках
ya-pomogau/frontend pull request #105
Opened 2024-01-02 14:42 UTC by lexanikitin

В процессе работы удалил несколько дублирующих компонентов. 
Собрал код получения, фильтрации, сортировки данных для карточек на всех вкладках в одном компоненте.

В будущем развитии задачи предлагаю изменить роутинг и оставить только одну страницу с вкладками (только /profile/requests/), тогда при переключении вкладок не будут происходить повторные запросы и перерисовка страницы. В данный момент это выходит за рамки задачи, т.к. потребует переделки и компонента вкладок. Такая

2024-01-03 15:43 UTC, SergeyKukhtalevV commented on src/pages/requests/index.tsx
> +    (user: UserProps) => user.role == 'recipient'
Здесь и ниже, лучше использовать "==="

2024-01-08 17:43 UTC, INextYP requested changes

2024-01-08 17:43 UTC, INextYP commented on src/pages/requests-tab/index.tsx
> +    <>
этот реакт фрагмент явно лишний. Напомню, что реакт фрагмент нужен, когда тебе нужно сложить 2 и более элементов в НЕявный контейнер. У тебя же есть явный контейнер `div`

2024-01-08 17:43 UTC, INextYP commented on src/pages/requests-tab/index.tsx
> +interface UserProps {
у тебя этот тип дублируется в RequestsPage. Такого быть не должно. Все переиспользуемые сушности выносим в соответствующий слой

2024-01-08 17:43 UTC, INextYP commented on src/pages/requests-tab/index.tsx
> +  role: 'volunteer' | 'recipient' | 'admin' | 'master';
Было бы круто вынести union в отдельный тип, т.к. явно они где-то будут использоваться

2024-01-08 17:43 UTC, INextYP commented on src/pages/requests-tab/index.tsx
> +  volunteerInfo?: any;
Типа any быть не должно. Либо явно определи тип, либо используй более удачный тип - unknown

2024-01-08 17:43 UTC, INextYP commented on src/pages/requests-tab/index.tsx
> +            volunteerInfo={user.volunteerInfo}
Попробуй, эту запись можно написать короче - `<UserCard key={user.userId} {...user} />`

2024-01-08 17:43 UTC, INextYP commented on src/pages/requests/index.tsx
> +interface UserProps {
Про это написал выше.

2024-01-08 17:43 UTC, INextYP commented on src/widgets/page-sub-menu/components/page-sub-menu-for-admins/page-sub-menu-for-admins.tsx
> +          {role === 'master' ? (
Все роли должны быть вынесены в `enum` тип чтобы не было случайных грамматических ошибок и косяков. Соответственно, тут поменяется на  `role === Roles.master`

2024-01-08 17:43 UTC, INextYP commented on src/pages/requests/index.tsx
> +      case 'volunteers':
Все типы вкладок должны быть вынесены в enum тип чтобы не было случайных грамматических ошибок и косяков. Соответственно, тут поменяется на `case === IncomeTab.volunteers`

2024-01-08 17:43 UTC, INextYP commented on src/pages/requests/index.tsx
> +    (user: UserProps) => user.role == 'recipient'
Аналогично замечанию по ролям в enum + не лучше ли это дело всё мемоизировать? Имеются ввиду `recipientsData, volunteersData, adminsData`

2024-01-08 17:43 UTC, INextYP commented on src/pages/requests/index.tsx
> +  const countersOnTabsRecipients = useMemo(() => {
Старайся делать отступ между логическими частями

2024-01-08 17:43 UTC, INextYP commented on src/pages/requests/index.tsx
> +        if (a.volunteerInfo.approved === false) {
ключ у объекта как-то непонятно называется. Почему у реципиента `volunteerInfo`?

2024-01-08 17:43 UTC, INextYP commented on src/pages/requests/index.tsx
> +  const countersOnTabsVolunteers = useMemo(() => {
Старайся делать отступ между логическими частями

2024-01-08 17:43 UTC, INextYP commented on src/pages/requests/index.tsx
> +    return volunteersData
Зачем тут 3 раза сортировать? Не проще через if else if сделать короче и проще?

2024-01-08 17:43 UTC, INextYP commented on src/pages/requests/index.tsx
> +        if (a.volunteerInfo.approved === false) {
Несколько повторений одних и тех же проверок не проще вынести в функцию хелпер и использовать в `.sort `методе?

2024-01-08 17:43 UTC, INextYP commented on src/widgets/page-sub-menu/components/page-sub-menu-for-admins/page-sub-menu-for-admins.tsx
> +  const { role } = useAppSelector((state) => state.user);
у нас разве пользователь не находится в системном слайсе?

2024-01-08 17:43 UTC, INextYP commented on src/pages/requests/styles.module.css
> +    margin-bottom: 30px;
Просто совет - старайся всегда использовать короткую запись маржинов паддингов и т.д. Это не повысит оптимизацию, но иногда довольно хорошо можно сократить количество кода

2024-01-11 13:28 UTC, lexanikitin commented on src/widgets/page-sub-menu/components/page-sub-menu-for-admins/page-sub-menu-for-admins.tsx
> +  const { role } = useAppSelector((state) => state.user);
поправь меня , но из слайса ничего не получил. ПОэтому использовал те данные и так , как они получаются в др элементах страницы 

`  const usertest = useAppSelector(userSelector);`

2024-01-11 13:31 UTC, lexanikitin commented on src/pages/requests/styles.module.css
> +    margin-bottom: 30px;
Моя логика была атомизировать коммиты и таски , поэтому использовал стили , которые были. 
Стили вообще не правил. 
Так то мне многое хочется поправить, но это выйдет за пределы задачи и вызовет еще большую неразбериху на проектном уровне. Я бы вообще вернулся к стадии проектирования и доделал ее , прежде чем двигаться дальше.

2024-01-11 14:03 UTC, kspshnik commented on src/pages/requests-tab/index.tsx
> +  role: 'volunteer' | 'recipient' | 'admin' | 'master';
Они местах в четырёх определены по всякому.
А по факту надо всё это брать как на бэкенде.

2024-01-11 14:03 UTC, kspshnik commented on src/pages/requests-tab/index.tsx
> +  volunteerInfo?: any;
Здесь не должно быть даже `unknown` - структура данных известна и понятна.

2024-01-11 14:04 UTC, kspshnik commented on src/pages/requests-tab/index.tsx
> +            volunteerInfo={user.volunteerInfo}
Линтер орёт, не любит спреда пропсов.

2024-01-11 14:06 UTC, kspshnik commented on src/widgets/page-sub-menu/components/page-sub-menu-for-admins/page-sub-menu-for-admins.tsx
> +  const { role } = useAppSelector((state) => state.user);
> у нас разве пользователь не находится в системном слайсе?
Там лёгкий бардак от частичного применения FSD через петушиный хвост.
Сейчас юзверь и в системном живёт, и дублируется в entity User
Это надо обсудить и принять архитектурное решение :)

2024-01-11 14:07 UTC, kspshnik commented on src/pages/requests/styles.module.css
> +    margin-bottom: 30px;
> Я бы вообще вернулся к стадии проектирования и доделал ее , прежде чем двигаться дальше.

К сожалению, сроки не пустят. Нам надо MVP выкатить :)

2024-01-11 14:11 UTC, kspshnik requested changes
В общем, @INextYP всё до меня успел сказать :)

2024-01-11 14:11 UTC, kspshnik commented on src/pages/requests/index.tsx
> +  role: 'volunteer' | 'recipient' | 'admin' | 'master';
Роли должны быть перечислением, заданным **однократно**

2024-01-11 14:23 UTC, lexanikitin commented on src/pages/requests/styles.module.css
> +    margin-bottom: 30px;
> > Я бы вообще вернулся к стадии проектирования и доделал ее , прежде чем двигаться дальше.
> 
> К сожалению, сроки не пустят. Нам надо MVP выкатить :)
офтоп, но  можно вопрос - ск групп и ск проектных месяцев делается этот проект до нас ? 
Первые стадии проектирования я так понимаю пробежали с первой группой, чтобы успеть и покодить ?

2024-01-11 15:51 UTC, marussia1996 commented on src/pages/requests-tab/index.tsx
> +  role: 'volunteer' | 'recipient' | 'admin' | 'master';
вообще в UserRole я разобралась в ветке fix/auth

2024-01-11 19:02 UTC, INextYP commented on src/pages/requests/styles.module.css
> +    margin-bottom: 30px;
Коммерческая разработка она такая. Проект нужно сдать ещё "вчера" и всё что нам остается, чтобы уложиться в сроки - доделывать чужой код, скрипя зубами :) Так было и будет всегда в разработке...

2024-01-12 14:02 UTC, lexanikitin commented on src/pages/requests-tab/index.tsx
> +  role: 'volunteer' | 'recipient' | 'admin' | 'master';
Они в этих местах еще и определены по разному, где-то с заглавной , где-то без , где-то есть мастер , где-то нету. 
Взял то , что подошло. Потом рефакторить типизацию, но вначале сделать один источник правды.

2024-01-12 14:02 UTC, lexanikitin commented on src/pages/requests-tab/index.tsx
> +    <>
Done

2024-01-12 14:32 UTC, lexanikitin commented on src/pages/requests-tab/index.tsx
> +            volunteerInfo={user.volunteerInfo}
Done

2024-01-12 14:32 UTC, lexanikitin commented on src/pages/requests-tab/index.tsx
> +  volunteerInfo?: any;
Ну почти , есть расхождения в коде. Структура нигде не типизирована, только локально. Взял из моковых данных, но и там есть лишняя переменная , которая не используется       `adminStatus: null`
Выглядит как повтор информации , который забыли убрать. 
Сделал типизацию, вынес.

2024-01-12 14:33 UTC, lexanikitin commented on src/pages/requests/index.tsx
> +interface UserProps {
Done

2024-01-12 14:49 UTC, lexanikitin commented on src/pages/requests-tab/index.tsx
> +  role: 'volunteer' | 'recipient' | 'admin' | 'master';
Есть типизация `export type UserRole = 'recipient' | 'volunteer' | 'master' | 'admin';`

Есть перечисление ролей 
`export enum UserRole {
  ADMIN = 'Admin',
  RECIPIENT = 'Recipient',
  VOLUNTEER = 'Volunteer',
}`

код из проекта

2024-01-12 14:51 UTC, lexanikitin commented on src/pages/requests-tab/index.tsx
> +  role: 'volunteer' | 'recipient' | 'admin' | 'master';
Одна часть проекта опирается на одно , вторая на другое. Нужен рефакторинг видимо. Сильно выходит за рамки таски и точно не стоит делать в этом бренче.

2024-01-12 14:53 UTC, lexanikitin commented on src/pages/requests-tab/index.tsx
> +interface UserProps {
Done

2024-01-12 14:54 UTC, lexanikitin commented on src/widgets/page-sub-menu/components/page-sub-menu-for-admins/page-sub-menu-for-admins.tsx
> +          {role === 'master' ? (
см выше. 
сделал плохо, но оставил так до рефакторинга.

2024-01-12 14:54 UTC, lexanikitin commented on src/pages/requests/index.tsx
> +      case 'volunteers':
Done

2024-01-12 15:01 UTC, lexanikitin commented on src/pages/requests/index.tsx
> +    (user: UserProps) => user.role == 'recipient'
Весь абзац кода с получением данных это заглушка на получение моковых данных из файла. 
Можно перенести в мемо, но смысл ? 
Данные будут получаться хуками с обновлением по интервалу.

2024-01-12 15:03 UTC, lexanikitin commented on src/pages/requests/index.tsx
> +        if (a.volunteerInfo.approved === false) {
вот для меня тоже загадка. пытались с коллегой Сергеем отгадать - бесполезно. 
нету единого источника правды по типам и форматам данных, сохранил то, что было до меня.

2024-01-12 15:42 UTC, lexanikitin commented on src/pages/requests/index.tsx
> +        if (a.volunteerInfo.approved === false) {
Сортировки разные.

2024-01-17 11:18 UTC, marussia1996 commented on src/pages/requests-tab/index.tsx
> +  role: 'volunteer' | 'recipient' | 'admin' | 'master';
рефакторинг этого уже есть в ветке fix/auth просто ее никак не отревьювят) UserRole берем из common файла

2024-01-17 14:19 UTC, INextYP approved these changes

2024-01-17 14:45 UTC, merged