Feature/volunteer unconfirmed message
ya-pomogau/frontend pull request #107
Opened 2024-01-10 09:20 UTC by ulbee

2024-01-11 12:22 UTC, ulbee commented
@kspshnik @Anton-Laid @ArturKaramov 
Посмотрите пр, плиз

2024-01-11 14:00 UTC, kspshnik reviewed
Добавь в ревьюверы @marussia1996 , пожалуйста

2024-01-11 14:00 UTC, kspshnik commented on src/widgets/map/Mark.tsx
Строго говоря, в `React.memo()` лучше обёртывать при экспорте: 
```ts
const MyComponent : React.FC<PropsInterface> = ({...}) => { ... };

export default React.memo(MyComponent);

```

По сути то же самое, но читается значительно лучше.

2024-01-11 15:38 UTC, marussia1996 requested changes

2024-01-11 15:38 UTC, marussia1996 commented on src/widgets/map/Mark.tsx
> +          isDisabled,
если я правильно поняла, то этот пропс отвечает за кнопку "Откликнутся", так вот у волонтера, который еще не подтвержден она хоть и серая на макете, но как я понимаю должна нажиматься, после чего пользователю будет показан попап.

2024-01-12 10:54 UTC, ulbee commented on src/widgets/map/Mark.tsx
> +          isDisabled,
Этот пропс еще и для простановки класса на кнопку используется. Но, получается, не надо прямо атрибут кнопке прописывать? И добавить проверку в обработку клика?

2024-01-12 11:05 UTC, marussia1996 commented on src/widgets/map/Mark.tsx
> +          isDisabled,
не делай кнопку Откликнутся disabled (но оставь ее серой), а при нажатии делай открытие попапа с сообщением о том, что пока волонтер не может откликнуться.  Да и вообще у этой кнопки 3 или даже больше вариантов того что может происходить после её нажатия в зависимости от разных факторов, вы с командой обсуждали этот момент?

2024-01-12 11:31 UTC, ulbee commented on src/widgets/map/Mark.tsx
> +          isDisabled,
Не обсуждали пока. На самом деле моя следующая задача как раз проработать эти варианты нажатия кнопки, когда уже одобрен волонтер. 
Попап посмотрю👍

2024-01-17 16:12 UTC, ulbee commented
Единственный вопрос: правильно ли я использовала lightPopup для своей задачи? Я добавила ему крестик и стили. Может, стоит скрыть это за модификатором, чтобы не испортить использование в другом месте?

2024-01-17 17:43 UTC, marussia1996 requested changes

2024-01-17 17:43 UTC, marussia1996 commented on src/shared/ui/light-popup/index.tsx
> +    <OverlayingPopup
OverlayingPopup используется у реципиентов еще, так что надо подумать над логикой. На первый взгляд можно в LightPopup передавать не только сообщение, но и весь этот div с кнопкой закрытия в качестве children.

2024-01-17 18:58 UTC, ulbee commented on src/shared/ui/light-popup/index.tsx
> +    <OverlayingPopup
Давай я лучше тогда дополнительный пропс прокину - модификатор, который будет добавлять крестик или нет?

2024-01-17 19:28 UTC, kspshnik requested changes

2024-01-17 19:28 UTC, kspshnik commented on src/shared/ui/light-popup/index.tsx
> +  hasClosedButton?: boolean;
А что за закрытая кнопка? :)
Может таки `hasCloseButton`?

2024-01-17 19:51 UTC, ulbee commented on src/shared/ui/light-popup/index.tsx
> +  hasClosedButton?: boolean;
минуту))

2024-01-17 19:56 UTC, kspshnik approved these changes

2024-01-18 11:28 UTC, marussia1996 commented on src/shared/ui/light-popup/index.tsx
> +    <OverlayingPopup
ну можно и так наверно)

2024-01-18 11:29 UTC, marussia1996 approved these changes

2024-01-18 11:30 UTC, merged