Яндекс карта для реципиента
ya-pomogau/frontend pull request #109
Opened 2024-01-10 15:49 UTC by AlexandrGerasimov63

В процессе работы:

Исправлено:
-  получение стартовых значений, из-за которых карта падала в ошибку
-  всплытие попапа при клике на баллун, которое приводило к блокировке приложения
-  мультизапросы при работе геосаджеста
-  сохранение состояния карты при переходе между этапами создания заявки

Добавлено:

- возможность перетаскивать баллун по карте
- получение координаты в положение DragEnd
- конвертирование координат в адрес и автозаполнение инпута

2024-01-11 14:21 UTC, kspshnik requested changes
Очень классно, что разобрались с картой!!

2024-01-11 14:21 UTC, kspshnik commented on src/config/ymaps/switches-api.ts
А стоимость этих предложений какая? Мы заказчика так на деньги не выставим радостно?
:)

2024-01-11 14:21 UTC, kspshnik commented on src/features/create-request/ui/steps/address-step/address-step.tsx
> +  const cord = useAppSelector((store) => store.user.data?.coordinates);
Формально "cord" (англ.) ближе к верёвке, чем к координатам :)
Наверное, `coords` будет лучше?

2024-01-11 14:21 UTC, kspshnik commented on src/shared/ui/input-address/index.tsx
> +    coords: GeoCoordinates | [];
Нет. Так теряется строгость типизации.

2024-01-11 14:30 UTC, AlexandrGerasimov63 commented on src/config/ymaps/switches-api.ts
![2024-01-11_18-29-40](https://github.com/ya-pomogau/frontend/assets/97280804/0178d0ad-ea95-4346-876d-a93c9afbc411)
Ваши предложения господа? =)

2024-01-11 14:33 UTC, kspshnik commented on src/config/ymaps/switches-api.ts
Кмк этот функционал сейчас **не надо** подключать. Возможно, надо закомментировать код, чтобы было легко вернуться к этому в будущем, но так мы тупо выставляем заказчика на бабло. А заказчик - НКО

@INextYP, @marussia1996 - что скажете?

2024-01-11 14:34 UTC, AlexandrGerasimov63 commented on src/config/ymaps/switches-api.ts
Та не, там учебный ключ на 1000 запросов в сутки

2024-01-11 14:36 UTC, kspshnik commented on src/config/ymaps/switches-api.ts
Это **у нас** _учебный_ ключ.
А заказчику придётся покупать боевой.

2024-01-11 14:49 UTC, AlexandrGerasimov63 commented on src/config/ymaps/switches-api.ts
![2024-01-11_18-48-53](https://github.com/ya-pomogau/frontend/assets/97280804/17a5dfa2-72b2-4c43-87a1-ec755d7e9cf4)
Тарифы Яндекс Карт Апи

2024-01-11 15:07 UTC, kspshnik commented on src/config/ymaps/switches-api.ts
Это не к нам, это к заказчику. Они ЕМНИП говорили, что нинада платных им навязывать :)

2024-01-11 15:42 UTC, marussia1996 commented on src/config/ymaps/switches-api.ts
у нас в ноушене написано, что мы использует suggest, разве это не было обговорено с заказчиком на этапе создания этого ноушена? Для чего тогда это указано в требованиях к проекту?

2024-01-11 15:46 UTC, marussia1996 requested changes

2024-01-11 15:46 UTC, marussia1996 commented on src/config/ymaps/switches-api.ts
> +export const YMAPS_SUGGEST_SWITCHER = true;
лучше установить этот фалг в false, и устанавливать true, только при показе работы или тестировании

2024-01-11 16:41 UTC, vladbarsukov commented on src/config/ymaps/switches-api.ts
Код просмотрен, со всем согласен

2024-01-11 16:41 UTC, vladbarsukov approved these changes

2024-01-11 16:47 UTC, kspshnik commented on src/config/ymaps/switches-api.ts
> +export const YMAPS_SUGGEST_SWITCHER = true;
А ещё лучше - вынести в `.env`

2024-01-11 16:48 UTC, kspshnik commented on src/config/ymaps/switches-api.ts
> у нас в ноушене написано, что мы использует suggest, разве это не было обговорено с заказчиком на этапе создания этого ноушена? Для чего тогда это указано в требованиях к проекту?


У нас же осталась запись встречи с заказчиком? Там был разговор про платное, что пока нинада. Хотя я могу ошибаться.

2024-01-11 17:29 UTC, marussia1996 commented on src/config/ymaps/switches-api.ts
так сейчас оно и не платное

2024-01-11 18:33 UTC, kspshnik commented on src/config/ymaps/switches-api.ts
Это пока 1000 бесплатных в день. Это вылетит **ОЧЕНЬ** быстро :)

2024-01-11 18:50 UTC, INextYP requested changes
Молодец! Отличная работа :)

2024-01-11 18:50 UTC, INextYP commented on src/features/create-request/model/create-request.ts
> +  coordinates: GeoCoordinates | undefined;
Мини-замечание. Необязательно писать `| undefined;`, если координаты могут быть, а могут не быть, просто поставь знак `?` вот так `coordinates?: GeoCoordinates` и тогда TS будет понимать, всё также, так и у тебя было написано.

2024-01-11 18:50 UTC, INextYP commented on src/features/create-request/ui/steps/address-step/address-step.tsx
1. Не оставляй комментарии. По коду явно видно, что он делает. 
2. Старайся структурировать код (сначала идет определение переменных, отступили, далее вытягиваем нужные данные и стора, отступили, хуки и т.д.)

2024-01-11 18:50 UTC, INextYP commented on src/widgets/map/index.tsx
> +  coordinates?: GeoCoordinates | undefined;
здесь вообще не нужен `| undefined` у тебя уже стоит знак `?`

2024-01-11 18:50 UTC, INextYP commented on src/widgets/map/Mark.tsx
> +import { useDispatch } from 'react-redux';
Используй типизированный `useAppDispatch`

2024-01-11 18:50 UTC, INextYP commented on src/widgets/map/Mark.tsx
> +    const dispatch = useDispatch();
заменить на `useAppDispatch`

2024-01-11 18:50 UTC, INextYP commented on src/shared/ui/input-address/index.tsx
>    setAddress: (address: string, coords?: [number, number] | []) => void;
тут тогда тоже `GeoCoordinates` будет типом у `coords`

2024-01-11 18:50 UTC, INextYP commented on src/widgets/map/Mark.tsx
> +import React, { useState } from 'react';
весь React не нужно тянуть, используй деструктуризацию

2024-01-12 10:58 UTC, marussia1996 commented on src/config/ymaps/switches-api.ts
я понимаю это) но какой аналог взаимодействия с картой ты предлагаешь? как мы будем узнавать правильный (существующий) ли адрес ввели или координаты этого адреса?

2024-01-12 11:13 UTC, kspshnik commented on src/config/ymaps/switches-api.ts
Падажжи, речь вообще про _suggest_ - выдачу _предложений_ по **продолжению** адреса, не про перевод в координаты :)

2024-01-13 10:29 UTC, INextYP commented on src/config/ymaps/switches-api.ts
> Падажжи, речь вообще про _suggest_ - выдачу _предложений_ по **продолжению** адреса, не про перевод в координаты :)

Не существует сервисов, которые бесплатно предоставляли бы функционал по автодополнению адресов (только если самим написать xD), всё в рамках ограниченной учебной/ платной лицензии. Мы реализуем "как можем", а клиент уже сам будет решать, как ему поступить, либо покупать, либо искать варианты отказа от данного функционала, но отказ от этой системы - потеря значительной доли функционала.
Для уменьшения количества запросов к таким сервисам обычно используются сервисы кеширования запросов, но это настолько темный лес для вас, на котором сейчас не стоит акцентировать внимание.

2024-01-13 10:35 UTC, kspshnik commented on src/config/ymaps/switches-api.ts
Я бы сделал этот функционал отключаемым по флажку в `.env`, типа `ADDRESS_SUGGESTIONS=false` по умолчанию, а по желанию может заказчик там включать :)

2024-01-16 12:20 UTC, vladko-89 approved these changes

2024-01-17 10:52 UTC, marussia1996 approved these changes

2024-01-17 14:16 UTC, INextYP approved these changes

2024-01-17 19:18 UTC, kspshnik reviewed
Супер :) Но внешним настройкам место в переменных среды :)

И попробуй при последующем рефакторинге вынести повторяющиеся участки кода, работающие с геокоординатами, в хелпер

2024-01-17 19:18 UTC, kspshnik commented on src/config/ymaps/api-keys.ts
>  export const YMAPS_API_KEY = '7b4bb7c4-4062-46a0-b7ab-f53610cc3365'; // JS APi
Выносим в `.env`

2024-01-17 19:18 UTC, kspshnik commented on src/config/ymaps/switches-api.ts
>  /* eslint-disable prettier/prettier */
зачем?

2024-01-18 11:15 UTC, kspshnik approved these changes

2024-01-18 11:15 UTC, merged