Features/recipient unconfirmed
ya-pomogau/frontend pull request #115
Opened 2024-01-14 16:40 UTC by AlexandrGerasimov63

-Добавлена новая сущность в БД
-Кнопка для выбора роли неподтвержденного реципиента
-Отрисовка компонентов неподтвержденного реципиента
-Сообщение для пользователя в шапке страницы
-Кнопка при нажатие открывающая попап

2024-01-15 17:44 UTC, INextYP requested changes

2024-01-15 17:44 UTC, INextYP commented on src/shared/ui/page-layout/index.tsx
> +  const isRole = useAppSelector((state) => state.user.data?.role);
обычно, если пишем приставку `is`, то подразумевается, что переменная будет хранить булево значение.

2024-01-15 17:44 UTC, INextYP commented on src/shared/ui/page-layout/index.tsx
> +  const isRole = useAppSelector((state) => state.user.data?.role);
+ у тебя 3 раза используется стейт пользователя. Не проще сделать деструктуризацию?
```
const { isLoading, data } = useAppSelector((state) => state.user);
```

2024-01-15 17:44 UTC, INextYP commented on src/shared/libs/statuses.ts
> +export const UNCONFIRMED = 'unconfirmed';
Явно в будущем стоит переделать на перечисление

2024-01-15 17:44 UTC, INextYP commented on src/shared/ui/page-layout/index.tsx
> +          {isUnConfirmedUser && isRole === 'recipient' && (
Роль взять из перечисления ролей

2024-01-17 06:35 UTC, INextYP requested changes

2024-01-17 06:35 UTC, INextYP commented on src/entities/task/ui/task-list/index.tsx
> +  // }, [isOpen]);
Если этот код больше не нужен, то стоит убрать его. Оставлять закомментированные куски - плохая практика

2024-01-17 09:43 UTC, marussia1996 requested changes

2024-01-17 09:43 UTC, marussia1996 commented on src/entities/user/ui/user-info/index.tsx
> +  const roleStatus = useAppSelector((state) => state.user.data?.status);
почему roleStatus? это же userStatus

2024-01-17 09:43 UTC, marussia1996 commented on src/shared/ui/page-layout/index.tsx
> +          {isUnConfirmedUser && isRole === 'recipient' && (
её нужно взять из файла common - UserRole.Recipient

2024-01-17 16:24 UTC, AlexandrGerasimov63 commented on src/shared/ui/page-layout/index.tsx
> +          {isUnConfirmedUser && isRole === 'recipient' && (
Чтобы это сделать, необходимо поменять 52 файла, которые меняла Маша в своей ветке  =)))

2024-01-17 19:19 UTC, kspshnik approved these changes
Отлично :)

2024-01-18 11:20 UTC, marussia1996 approved these changes
супер

2024-01-18 11:45 UTC, INextYP requested changes

2024-01-18 11:45 UTC, INextYP commented on src/entities/task/ui/task-list/index.tsx
> +interface Cords {
Что за веревка? :)

2024-01-18 11:45 UTC, INextYP commented on src/entities/task/ui/task-list/index.tsx
> +  const myRef = useRef<HTMLDivElement>(null);
он точно "твой реф"? :)

2024-01-18 11:45 UTC, INextYP commented on src/entities/task/ui/task-list/index.tsx
> +                  changeVisible={() => setIsOpen(false)}
`setIsOpen(false)` повторяется, вынеси в функцию
```
const имя_функции = () => setIsOpen(false) 
```

И используй тут и на 201 строке
```
onClick={имя_функции}
```

2024-01-18 11:45 UTC, INextYP commented on src/pages/profile-active/index.tsx
>    const { role } = useAppSelector((state) => state.user);
добавить data
```
const { role, data } = useAppSelector((state) => state.user);
```
И использовать ниже

```
const isConfirmed = data?.status === CONFIRMED;
```

2024-01-18 11:45 UTC, INextYP commented on src/pages/profile-completed/index.tsx
>    const { role } = useAppSelector((state) => state.user);
добавить data

const { role, data } = useAppSelector((state) => state.user);
И использовать ниже

const isConfirmed = data?.status === CONFIRMED;

2024-01-18 11:45 UTC, vladbarsukov approved these changes

2024-01-18 12:10 UTC, kspshnik requested changes

2024-01-18 12:10 UTC, kspshnik commented on src/entities/task/ui/task-list/index.tsx
> +                  changeVisible={() => setIsOpen(false)}
И не просто вынеси, а **оберни** `useCallback()`. А сам `ToolTip` в `React.memo()`, иначе будет перерендер по цепочке каждый раз.

2024-01-18 12:10 UTC, kspshnik commented on src/entities/task/ui/task-list/index.tsx
> +                      onClick={() => setIsOpen(false)}
Здесь аналогично.

2024-01-20 15:09 UTC, vladko-89 commented on src/entities/task/ui/task-list/index.tsx
> +                  changeVisible={() => setIsOpen(false)}
Тут смысла особого нет заворачивать в useCallback. У нас там Tooltip убирается из DOM когда закрыт `isOpen && <Toltip>`, а сам этот элемент всего лишь сообщение, там нет никакого функционала который ререндерить его будет. Это можно убрать.

2024-01-20 15:14 UTC, vladko-89 requested changes

2024-01-20 15:14 UTC, vladko-89 commented on src/shared/ui/tooltip/index.tsx
> +  const tooltip = useMemo(() => {
useMemo и React.memo это разные вещи. Если компонент заворачивают в React.memo, а не в хук. 

Как я уже написал в комментарии выше, useCallback в текущем случае не нужен, от него не будет смысла, а если нет useCallback то и React.memo и useMemo не нужны!.

React.memo полезен когда есть массив сущностей, скажем карточек. React устроен так, что если изменится пропс в компоненте родителе, он перерендерит всю коллекцию карточек, даже если изменится, к примеру, ключ isLiked в одной из карт. Так вот компонент карточки в React.memo перерисует только одну карту в которой произошло изменение, а не всю коллекцию.

2024-01-22 11:15 UTC, INextYP approved these changes

2024-01-22 16:04 UTC, merged