Blog-form component; #87
ya-pomogau/frontend pull request #118
Opened 2024-01-16 17:34 UTC by margo-yunanova

Форма для создания\редактирования поста.

2024-01-17 06:26 UTC, INextYP requested changes

2024-01-17 06:26 UTC, INextYP commented on src/shared/ui/post-form/PostForm.tsx
> +            accept=".png, .jpg, .jpeg"
Предлагаю небольшое улучшение: все разрешения файлов вынести в `enum`  (т.к инпут для загрузки файлов может понадобится в других местах)

2024-01-17 06:26 UTC, INextYP commented on src/shared/ui/post-form/PostForm.tsx
> +  addAttachment: (fileList: FileList | null) => void;
Не вижу, а откуда тянется тип `FileList`

2024-01-17 09:25 UTC, margo-yunanova commented on src/shared/ui/post-form/PostForm.tsx
> +  addAttachment: (fileList: FileList | null) => void;
Тип FileList стандартный тип из DomApi, доступен в TypeScript по умолчанию.

2024-01-17 09:35 UTC, marussia1996 approved these changes
Выглядит замечательно) С улучшением Саши соглашусь, у нас есть еще несколько мест где будет использоваться инпут для файлов)

2024-01-17 09:35 UTC, marussia1996 commented on src/shared/ui/post-form/PostForm.tsx
> +  addAttachment: (fileList: FileList | null) => void;
кажется это интерфейс из либы typescript, для получения списка файлов из инпута с типом file. поэтому и нет импорта

2024-01-17 10:09 UTC, margo-yunanova commented on src/shared/ui/post-form/PostForm.tsx
> +            accept=".png, .jpg, .jpeg"
Как думаешь, лучше так

```javascript
export enum FileTypes {
  IMAGES = '.jpg, .jpeg, .png',
}
```

или так

```javascript
export enum FileTypes {
  JPG = '.jpg',
  JPEG = '.jpeg',
  PNG = '.png',
}
```

2024-01-17 10:27 UTC, kspshnik commented on src/shared/ui/post-form/PostForm.tsx
> +            accept=".png, .jpg, .jpeg"
второе, 100%
Но без точек, их легко добавить.

2024-01-17 10:32 UTC, margo-yunanova commented on src/shared/ui/post-form/PostForm.tsx
> +            accept=".png, .jpg, .jpeg"
> второе, 100% Но без точек, их легко добавить.

мне кажется без точек не очень удобно, получится франкенштейн-строка

2024-01-17 10:42 UTC, kspshnik commented on src/shared/ui/post-form/PostForm.tsx
> +            accept=".png, .jpg, .jpeg"
Точка добавляется автоматом с помощью шаблонной строки, она **не несёт** информации от слова *совсем*.

@INextYP, @vladko-89 - что скажете?

2024-01-17 10:59 UTC, margo-yunanova commented on src/shared/ui/post-form/PostForm.tsx
> +            accept=".png, .jpg, .jpeg"
Точки вручную будут писать разрабочики в разных частях кода, да и строка не перестает быть франкенштейном, enum делается для того, чтобы не ошибиться и не опечататься, а точки и запятые маленькие знаки, про которые легко забыть (и не заметить их отсутствие на кодревью).

Под автоматом ты подразумеваешь такой код во всех компонентах с file input?
```javascript
<input accept={`.${FileTypes.JPEG}, .${FileTypes.JPG}, .${FileTypes.PNG}`} ...>
```
Вообще мне больше нравится вариант с IMAGES, т.к. это более высокоуровневая концепция (в каждом новом компоненте не нужно думать какие бывают расширения у картинок):
```javascript
<input accept={FileTypes.IMAGES} ...>
```

2024-01-17 11:32 UTC, kspshnik commented on src/shared/ui/post-form/PostForm.tsx
> +            accept=".png, .jpg, .jpeg"
А `accept="image/png, image/jpeg"` чем тебе не подходит? :)

P.S. `accept={Object.values(FileTypes).join(',')}`, не? :)

2024-01-17 12:27 UTC, margo-yunanova commented on src/shared/ui/post-form/PostForm.tsx
> +            accept=".png, .jpg, .jpeg"
Object.values - здесь будет не достаточно, т.к. была идея сделать enum с различными типами, не только картинки, значит, нам придётся ещё фильтровать. Сложно получается.

2024-01-17 12:28 UTC, kspshnik commented on src/shared/ui/post-form/PostForm.tsx
> +            accept=".png, .jpg, .jpeg"
Возможно, тут перечисление и не подходит в чистую? А нужен `Record<string, ["enum"]>` ?

2024-01-17 12:29 UTC, kspshnik commented on src/shared/ui/post-form/PostForm.tsx
> +            accept=".png, .jpg, .jpeg"
Можно же собрать объект и дать его `as const` ?

2024-01-17 18:47 UTC, vladko-89 commented on src/shared/ui/post-form/PostForm.tsx
> +            accept=".png, .jpg, .jpeg"
Честно говоря не знаю оправдано ли здесь слишком уходить в универсальность. Тут всегда можно переборщить с этим. 

Я бы честно говоря просто оставил enum с точками  №2 отсюда https://github.com/ya-pomogau/frontend/pull/118#discussion_r1455150288.

По поводу универсальности, не стоит забывать про `image/*` поэтому, если следовать логике что у нас есть файлы аудио, видео и т.д. тут бы следовало разбивать на несколько 

```
enum categoriesFiles = {
   AUDIO: 'audio', 
   ...
}
```

Отдельно перечисления по форматам audioTypes, imageTypes и т.д, при чем в каждом указать пункт `ALL: *`
И далее где-то все это собрать в единую какую-то структуру....

...но только вопрос, а надо ли? По-моему тут чем проще тем лучше

2024-01-17 19:17 UTC, INextYP commented on src/shared/ui/post-form/PostForm.tsx
> +            accept=".png, .jpg, .jpeg"
Полностью согласен. Пункт номер 2 самый удобный в данном случае. 
Хочу обратить внимание, что я указал на улучшение именно текущей реализации. Мы не смотрим в будущее, не делаем то, что, он не требуют. Учитесь следовать подходу KISS (не делай то, что от тебя не требуют). Вот понадобится кому-то в рамках какой-то задачи сделать доп форматы или ещё какие-то MIME типы - пусть берут и рефакторят код и дополняет/ изменяет типы.

2024-01-17 20:06 UTC, margo-yunanova commented on src/shared/ui/post-form/PostForm.tsx
> +            accept=".png, .jpg, .jpeg"
done

2024-01-18 06:28 UTC, vladko-89 approved these changes

2024-01-21 10:20 UTC, merged