Feature/admins
ya-pomogau/frontend pull request #119
Opened 2024-01-17 15:01 UTC by lexanikitin

2024-01-17 19:07 UTC, kspshnik commented on src/app/routing/router.tsx
>  export const router = createBrowserRouter(
**При дальнейшем рефакторинге** имеет смысл уйти на remix-style целиком

2024-01-17 19:14 UTC, kspshnik requested changes
Отлично в целом, но с типами надо бы навести красоту :)

2024-01-17 19:14 UTC, kspshnik commented on src/pages/requests/index.tsx
> +    (user: UserCardType) => user.role === 'recipient'
Здесь должен быть `enum` из `src/common`

2024-01-17 19:14 UTC, kspshnik commented on src/pages/requests/index.tsx
> +  const volunteersData = testUsers.filter(
См. предыдущий комментарий

2024-01-17 19:14 UTC, kspshnik commented on src/pages/requests/index.tsx
> +    (user: UserCardType) => user.role === 'admin'
См. предыдущий комментарий

2024-01-17 19:14 UTC, kspshnik commented on src/pages/requests/index.tsx
> +      .sort((a: UserCardType, b: UserCardType) => {
Эта сортировка используется _только_ здесь? Если нет - надо выносить в хелпер

2024-01-17 19:14 UTC, kspshnik commented on src/pages/requests/index.tsx
> +      volunteersData.filter(
Аналогично с предикатом здесь

2024-01-17 19:14 UTC, kspshnik commented on src/pages/requests/index.tsx
> +  const tabNotProcessedData = useMemo(() => {
Отсутствует массив зависимостей.

2024-01-17 19:14 UTC, kspshnik commented on src/pages/requests/test-users.tsx
Этот массив надо централизовать для всего приложения

2024-01-17 19:14 UTC, kspshnik commented on src/shared/types/common.types.ts
А это перечисление - использовать вместо хардкода :)

2024-01-17 19:14 UTC, kspshnik commented on src/widgets/page-sub-menu/components/page-sub-menu-for-admins/page-sub-menu-for-admins.tsx
> +export const PageSubMenuForAdmins = ({
типизацию пропсов лучше вынести

2024-01-17 20:06 UTC, vladko-89 commented on src/pages/requests/index.tsx
> +  const tabContent = useMemo(() => {
А для чего тут хук? Понимаю еще фильтрацию, да и то с натяжкой, но отрисовку. Тем более что одна из зависимостей меоизации это пропс текущего компонента, т.е. при изменении перерисует вообще все.

2024-01-21 10:03 UTC, lexanikitin commented on src/pages/requests/index.tsx
> +    (user: UserCardType) => user.role === 'recipient'
Done

2024-01-21 10:03 UTC, lexanikitin commented on src/pages/requests/index.tsx
> +  const volunteersData = testUsers.filter(
Done

2024-01-21 10:04 UTC, lexanikitin commented on src/pages/requests/index.tsx
> +    (user: UserCardType) => user.role === 'admin'
Done

2024-01-21 10:12 UTC, lexanikitin commented on src/widgets/page-sub-menu/components/page-sub-menu-for-admins/page-sub-menu-for-admins.tsx
> +export const PageSubMenuForAdmins = ({
@kspshnik 
Поясни, зачем выносить ? 
Интерфейс используется единожды, только в этом компоненте. 
Или мы во всем приложении выносим интерфейсы в отдельные файлы ?

2024-01-21 10:31 UTC, lexanikitin commented on src/pages/requests/index.tsx
> +  const tabContent = useMemo(() => {
Согласен, перемемоизировал, увлекся.

2024-01-21 10:34 UTC, lexanikitin commented on src/pages/requests/index.tsx
> +      .sort((a: UserCardType, b: UserCardType) => {
только здесь, дублей нет, смысла выносить не вижу

2024-01-21 14:21 UTC, kspshnik commented on src/pages/requests/index.tsx
> +      .sort((a: UserCardType, b: UserCardType) => {
И в волонтёре не используется, и в реципиенте?

2024-01-21 14:22 UTC, kspshnik commented on src/widgets/page-sub-menu/components/page-sub-menu-for-admins/page-sub-menu-for-admins.tsx
> +export const PageSubMenuForAdmins = ({
Если больше нигде не используется - то на текущем этапе непринципиально, перетаскать недолго.

2024-01-22 07:37 UTC, lexanikitin commented on src/pages/requests/index.tsx
> +      .sort((a: UserCardType, b: UserCardType) => {
Да, они немного разные.

2024-01-22 08:37 UTC, kspshnik commented on src/pages/requests/index.tsx
> +      .sort((a: UserCardType, b: UserCardType) => {
Насколько "немного"?
Оно не приводится к единому виду с лёгкими отклонениями?

2024-01-23 08:58 UTC, lexanikitin commented
Нужны небольшие правки по верстке карточек (их положение) и заголовка.

2024-02-27 15:05 UTC, INextYP approved these changes, later dismissed
В целом ок, но я бы сразу посоветовал избавиться от кучи комментариев и консолек в коде, дабы не тянуть их в dev

2024-02-27 15:05 UTC, INextYP commented on src/entities/task/ui/task-list/index.tsx
> +  useEffect(() => {
кажется, что это дубль

2024-02-27 15:05 UTC, INextYP commented on src/pages/requests/index.tsx
Очень много закомментированного кода. Если он не нужен, то давай вычистим его сразу

2024-02-27 15:05 UTC, INextYP commented on src/pages/requests-tab/index.tsx
> +  console.log('🚀  unconfirmed:', data3);
Можно сразу подчистить код от консолек

2024-02-27 15:05 UTC, INextYP commented on src/pages/register/index.tsx
>            pattern="^[+]7 \(\d{3}\) \d{3} \d{2} \d{2}$"
Сразу укажу, что эту регулярку лучше исправить, дабы пользователю не пришлось мучаться с добавлением скобок и пробелов

2024-02-28 16:19 UTC, INextYP submitted a review, later dismissed

2024-03-02 11:18 UTC, kspshnik submitted a review, later dismissed

2024-03-02 11:19 UTC, kspshnik approved these changes, later dismissed

2024-03-03 09:25 UTC, marussia1996 approved these changes

2024-03-03 09:37 UTC, kspshnik approved these changes

2024-03-04 13:46 UTC, merged