Feature/volunterr filter
ya-pomogau/frontend pull request #120
Opened 2024-01-17 17:16 UTC by Anton-Laid

Работают фильтры для tasks на странице активные заявки и завершенные заявки

2024-01-20 16:09 UTC, vladko-89 requested changes

2024-01-20 16:09 UTC, vladko-89 commented on src/shared/ui/time-picker/index.tsx
> +  // variant: 'start' | 'end';
Если закомментированные куски не нужно, их нужно убрать

2024-01-20 16:09 UTC, vladko-89 commented on src/features/filter/ui/sortBy-block/index.tsx
> +            checked={filter === 'decreasingPoints'}
Значения сортировок нужно вынести в enum.

Строки допустимо оставлять только контент

2024-01-20 16:09 UTC, vladko-89 commented on src/pages/profile-active/index.tsx
> +  const [infoFilterTasks, setInfoFilterTasks] = useState<IFilterValues>({
На страницах `profile-active` и `profile-complited` один и тот же функционал сортировки. Его нужно либо вынести в кастомный хук, или поднять в компонент выше по дереву

2024-01-20 16:18 UTC, kspshnik commented on src/pages/profile-active/index.tsx
> +  const [infoFilterTasks, setInfoFilterTasks] = useState<IFilterValues>({
Плюс стопиццот за кастомный хук :)

2024-02-04 08:30 UTC, INextYP approved these changes

2024-02-04 10:33 UTC, merged