Задачи волонтера: пункты 2, 3, 4
ya-pomogau/frontend pull request #121
Opened 2024-01-17 18:27 UTC by ArturKaramov

Маркер с координатами волонтера сделал просто через <Mark />, что по сути не отличает его от маркеров задач (в макете не нашел специального маркера для волонтера)

Фильтр тасок по расстоянию работает через формулу Хаверсина, масштаб карты подстраивается под координаты рассчитанные так же с этой формулой. 

поменял даты мока задач для теста фильтра, если надо будет вернуть их на место перед мерджем -- верну.

2024-01-17 19:24 UTC, kspshnik approved these changes

2024-01-18 11:25 UTC, INextYP requested changes

2024-01-18 11:25 UTC, INextYP commented on src/shared/libs/utils.ts
> +    parseInt(filterDate.split('-')[0]) * 365.25 +
Старайся не делать в коде "магических" чисел, а выносить их в переменные. Если ты понимаешь, что за 365.25, то другим явно будет не понятно, что это за число, а если ты вынесешь это число в созвучную переменную, то всем будет понятно, что это :)

2024-01-18 11:25 UTC, INextYP commented on src/shared/libs/utils.ts
> +    parseInt(filterDate.split('-')[2]) * 30 +
Аналогично, выносим 30 в переменную.

2024-01-18 11:25 UTC, INextYP commented on src/pages/profile-map/index.tsx
> +      if (query.searchRadius) {
Не проще так написать? И короче и лишние действия не выполняются, если проверка не прошла.
```
 if (query.searchRadius && typeof query.searchRadius === 'string' && user.coordinates) {
      const userCoords = Array.isArray(user.coordinates) ? user.coordinates : [user.coordinates.latitude, user.coordinates.longitude];
      result = result.filter((task: Task) => filterByDistance(userCoords, task.coordinates, parseInt(query.searchRadius, 10)));
    }
```

2024-01-18 11:25 UTC, INextYP commented on src/shared/libs/utils.ts
> +  return (rad * 180) / Math.PI;
Если я правильно понимаю логику сего процесса, то для поддержания производительности, рекомендую в функциях degrToRadians и radToDegr вынести `Math.PI / 180` и `180 / Math.PI` за пределы функции и использовать в теле функций так:

```
const КАКОЕ_ТО_НАЗВАНИЕ = Math.PI / 180;
const КАКОЕ_ТО_НАЗВАНИЕ_2 = 180 / Math.PI;

const degrToRadians = (deg: number): number => deg * КАКОЕ_ТО_НАЗВАНИЕ;

const radToDegr = (rad: number): number => rad * КАКОЕ_ТО_НАЗВАНИЕ_2;
```

2024-01-18 11:25 UTC, INextYP commented on src/shared/libs/utils.ts
> +  const earthRadius = 6371;
Вынести за пределы функции. Напомню, что при каждом вызове у тебя эта переменная будет пересоздаваться, а вынеся её за пределы функции ты заставишь функцию брать её из глобальной области видимости

2024-01-18 11:25 UTC, INextYP commented on src/shared/libs/utils.ts
> +  ];
можно использовать деструктуризацию массива в начале функции, для более понятного определения элементов массива
```
const [latitude, longitude] = coords;
```

2024-01-18 11:25 UTC, INextYP commented on src/shared/libs/utils.ts
> +  const getAngle = () =>
Почему ты решил использовать именно функцию, а не записал результат выполнения функции radToDegr в переменную getAngle?

2024-01-18 11:25 UTC, INextYP commented on src/shared/libs/utils.ts
> +    new Date(taskDate).getFullYear() * 365.25 +
new Date(taskDate) вынеси в переменную в начало тела функции, т.к. она у тебя 3 раза повторяется

2024-01-18 11:25 UTC, INextYP commented on src/shared/libs/utils.ts
> +    new Date(taskTime).getHours() * 60 + new Date(taskTime).getMinutes();
new Date(taskDate) вынеси в переменную в начало тела функции, т.к. она у тебя 2 раза повторяется

2024-01-18 12:01 UTC, kspshnik commented on src/shared/libs/utils.ts
> +  const earthRadius = 6371;
Или сделать перегрузку функции, принимающей сразу кортеж и возвращающей сразу кортеж.

2024-01-18 12:02 UTC, kspshnik commented on src/shared/libs/utils.ts
> +  ];
Или сделать перегрузку функции, принимающей сразу кортеж и возвращающей сразу кортеж.

2024-01-18 15:13 UTC, ArturKaramov commented on src/pages/profile-map/index.tsx
> +          if (typeof query.date === 'string') {
так TS ругается на query.date. Вместо этого уберу первую проверку (на 33 строке)

2024-01-18 15:42 UTC, kspshnik commented
@ArturKaramov и реши конфликты, пожалуйста

2024-01-18 15:53 UTC, ArturKaramov commented on src/pages/profile-map/index.tsx
> +      if (query.searchRadius) {
TS ругался на все эти оптимизации, но добавив деструктуризацию параметров в самом начале, перестал)

2024-01-18 16:36 UTC, ArturKaramov commented on src/shared/libs/utils.ts
> +  return (rad * 180) / Math.PI;
в целом как-будто пропадает надобность в функции, которое делает умножение на константу. может есть смысл либо оставить функции как есть, либо создать константы?

2024-01-18 16:55 UTC, INextYP commented on src/shared/libs/utils.ts
> +  return (rad * 180) / Math.PI;
> в целом как-будто пропадает надобность в функции, которое делает умножение на константу. может есть смысл либо оставить функции как есть, либо создать константы?

Функция у нас обычно какую роль выполняет? Она выполняет действия, которые повторяются. Отказаться от функции значит, что у нас появится несколько одинаковых действий в коде.

Мой совет в выносе действий исключит ненужные действия внутри функции, оставив в ней только действия для финального перевода в градусы или обратно

2024-01-18 17:37 UTC, ArturKaramov commented
@kspshnik @INextYP 

Замечания подправил, конфликты решил

2024-01-22 11:20 UTC, INextYP approved these changes

2024-01-22 13:14 UTC, merged