Добавлены два попапа для взятия заявок волонтером
ya-pomogau/frontend pull request #123
Opened 2024-01-18 13:18 UTC by ulbee

2024-01-18 14:27 UTC, kspshnik commented
@ulbee добавь коллег на peer-review, пожалуйста

2024-01-23 12:04 UTC, marussia1996 requested changes
![image](https://github.com/ya-pomogau/frontend/assets/29862392/03f22397-2e79-4dd6-944c-5f74a5822977)
почему-то при нажатии на одну из тасок происходит вот такое + ошибки в консоль 
![image](https://github.com/ya-pomogau/frontend/assets/29862392/d04987ff-3e62-47f7-8dd6-4335281cb52f)
попапы посмотрела, выглядят хорошо.

2024-01-29 12:22 UTC, marussia1996 requested changes

2024-01-29 12:22 UTC, marussia1996 commented on src/widgets/map/index.tsx
>            {coordinates && (
Если убрать эту часть кода, то ошибка уйдет и все будет работать верно) 124 - 132 строчки кода

2024-01-31 09:28 UTC, ulbee commented on src/widgets/map/index.tsx
>            {coordinates && (
М, просто это не моя часть кода, я обновляла по основной ветке фичи... Сейчас постараюсь посмотреть, как они аффектят друго друга

2024-01-31 10:09 UTC, ulbee commented on src/widgets/map/index.tsx
>            {coordinates && (
Почему-то дополнительно рисуется пин с несуществующей задачей (этого адреса нет в моках задач, но он есть у волонтера). И данных не хватает, поэтому все ломается

2024-01-31 11:59 UTC, marussia1996 approved these changes

2024-01-31 16:02 UTC, INextYP approved these changes

2024-02-01 13:20 UTC, merged