Features/recipient
ya-pomogau/frontend pull request #124
Opened 2024-01-18 13:59 UTC by AlexandrGerasimov63

Реквест реципиента

2024-01-18 14:24 UTC, kspshnik commented on src/features/create-request/ui/steps/address-step/address-step.tsx
> +    coords?: GeoCoordinates | []
А разве `GeoCoordinates` запрещают пустой кортеж?

2024-01-18 15:05 UTC, AlexandrGerasimov63 commented on src/features/create-request/ui/steps/address-step/address-step.tsx
> +    coords?: GeoCoordinates | []
Женя, я не понимаю, что ты хочешь чтобы я тебе ответил? Как выглядит Geocoordinates тип? Если ты об этом, то Geocoordinates array<number>

2024-01-18 15:34 UTC, kspshnik commented on src/features/create-request/ui/steps/address-step/address-step.tsx
> +    coords?: GeoCoordinates | []
Я хочу понять, нафига ты делаешь тут Union Type? ;o) 
`[]` соответствует типу `Array<number>`

2024-01-18 15:58 UTC, AlexandrGerasimov63 commented on src/features/create-request/ui/steps/address-step/address-step.tsx
> +    coords?: GeoCoordinates | []
Точно, можно же и без этого =)

2024-01-18 16:11 UTC, kspshnik requested changes
@AlexandrGerasimov63 и ещё в четырёх местах здорово бы лишний Union Type удавить.

2024-01-18 16:11 UTC, kspshnik commented on src/pages/register/index.tsx
> +    coords?: GeoCoordinates | [];
Та же фихня с Union Type

2024-01-18 16:11 UTC, kspshnik commented on src/pages/register/index.tsx
> +    coords?: GeoCoordinates | []
Union Type

2024-01-18 16:11 UTC, kspshnik commented on src/shared/ui/input-address/index.tsx
> +    coords?: GeoCoordinates | [];
Union Type

2024-01-18 16:11 UTC, kspshnik commented on src/shared/ui/input-address/index.tsx
> +  setAddress: (address: string, coords?: GeoCoordinates | []) => void;
Union Type

2024-01-18 17:45 UTC, kspshnik submitted a review, later dismissed
Теперь ОК :)

2024-01-19 20:16 UTC, vladko-89 reviewed
В целом ОК! Но стоит следить за чистотой кода.

Считается хорошей практикой убирать выводы в консоль, закомментированные куски кода и лишние импорты.

Также есть вопросы к экшену. Нет смысла в сторах держать слайсы для модальных окон - это элементы интерфейса, а не бизнес-логика приложения

2024-01-19 20:16 UTC, vladko-89 commented on src/features/create-request/ui/steps/date-step/date-step.tsx
> -import React, { useMemo } from 'react';
Закомментированные куски кода будут нужны в этом файле?

Если нет, то лучше все подчистить, также удалить все выводы в консоль и лишние импорты

2024-01-23 18:25 UTC, vladko-89 approved these changes, later dismissed

2024-02-04 18:03 UTC, marussia1996 approved these changes, later dismissed

2024-02-04 18:03 UTC, Anton-Laid approved these changes

2024-02-04 18:05 UTC, vladbarsukov approved these changes

2024-02-04 18:06 UTC, marussia1996 approved these changes

2024-02-04 18:10 UTC, closed without merging