Feature/volunteer
ya-pomogau/frontend pull request #125
Opened 2024-01-19 10:26 UTC by ulbee

2024-01-24 15:15 UTC, vladko-89 requested changes
В общем ок. Но есть вопросы по компонентам - все в комментариях к коду.

Также почему `task-list` лежит внутри `task/ui`? По логике, список это уже не entity, а widget по концепциям fsd

2024-01-24 15:15 UTC, vladko-89 commented on src/entities/task/ui/task/index.tsx
> -import { useState } from 'react';
Очень большой файл получился. Такого нужно избегать и и основная причина этого вот в чем:

- Сложно поддерживать - если нужно что-то добавить или вообще вылезет баг то скролить этот лапше-код и найти то место где собственно нужно модифицировать будет не просто

Каким образом это разбить смотрите комментарии

2024-01-24 15:15 UTC, vladko-89 commented on src/entities/task/ui/task/index.tsx
> +enum ButtonType {
Все типы, интерфейсы и енамы нужно выносить в отдельный скрипт и класть рядом с компонентом

2024-01-24 15:15 UTC, vladko-89 commented on src/entities/task/ui/task/index.tsx
> +const titles: ModalTitles = {
Переменные нужно также выносить

2024-01-24 15:15 UTC, vladko-89 commented on src/entities/task/ui/task/index.tsx
> +  const content: ModalContent = {
Внутри компонента не должно быть вот таких функций которые возвращают разметку. Тем более это модальные окна. У нас получается что, у каждой карточки свои окна модальные? Кнопки по которым открываются модалки, согласен, но не сама модалка с контентом

2024-01-24 15:15 UTC, vladko-89 commented on src/entities/task/ui/task/index.tsx
> +  const getModalContent = (buttonType: ButtonsTypes) => {
Тоже самое. Все вот такие штуки нужно выносить в поддиректорию components текущей entity. Что касается модальных окон, это уже скорее подкомпоненты для pages ну или widget листа с карточками.

2024-01-24 15:15 UTC, vladko-89 commented on src/entities/task/ui/task/index.tsx
>    if (isMobile) {
Наконец разметка самой карточки - по макету явно видно что карту можно разбить на три или даже 4 блока. Каждый можно вынести в отдельный подкомпонент и здесь собрать. Учитесь дробить компоненты. 

По хорошему, если глупый компонент (с одной разметкой) превышает 80 строк, это повод на выделение подкомпонентов.

Если компонент с логикой, допускается строк 120 но не больше. В идеале весь компонент должен уместиться на экране без скроллов.

2024-01-30 09:18 UTC, ArturKaramov commented on src/entities/task/ui/task/index.tsx
>    if (isMobile) {
Открыл пул реквест по этому пункту
https://github.com/ya-pomogau/frontend/pull/136
Посмотрите пожалуйста

2024-02-04 08:32 UTC, INextYP approved these changes

2024-02-04 12:23 UTC, merged