Features/recipient popup closing stage
ya-pomogau/frontend pull request #127
Opened 2024-01-21 18:25 UTC by vladbarsukov

Сделан этап закрытия попапа. Если реципиент закрывает попап на крестик или на оверлей, то отображается модальное окно "Закрыть окно сейчас и удалить ранее внесенную информацию?", где он может выбрать "Закрыть" - и данные формы будут удалены, или "Вернуться" и данные вернутся, а пользователь останется на прежнем месте.
Поправил мобильный вид попала. При публикации заявке пока что вывожу данные в консоль.

2024-01-22 16:00 UTC, marussia1996 reviewed
что за число на последнем экране появляется ? 123 ? Проверял ли ты последний экран на соответствие макету?

2024-01-22 16:00 UTC, marussia1996 commented on src/features/create-request/ui/steps/index.tsx
> +                  <div className={styles.text}>
а стили где для этого элемента?)

2024-01-22 16:00 UTC, marussia1996 commented on src/features/create-request/ui/steps/index.tsx
> +                      buttonType="primary"
Давай сделаем эту кнопочку secondary, чтобы было похоже на основной попап

2024-01-22 16:00 UTC, marussia1996 commented on src/features/create-request/ui/steps/common-step/common-step.tsx
> +    console.log(
сделай объект, который будет включать в себя все эти поля)

2024-01-23 18:31 UTC, vladko-89 commented on src/features/create-request/ui/steps/index.tsx
> +import React, { useCallback, useEffect, useRef, useState } from 'react';
Не используемые импорты также нужно убирать из кода

2024-01-25 19:19 UTC, vladbarsukov commented on src/features/create-request/ui/steps/index.tsx
> +                  <div className={styles.text}>
убрал

2024-01-25 19:19 UTC, vladbarsukov commented on src/features/create-request/ui/steps/index.tsx
> +                      buttonType="primary"
поправил

2024-01-25 19:19 UTC, vladbarsukov commented on src/features/create-request/ui/steps/common-step/common-step.tsx
> +    console.log(
добавил обьект

2024-01-25 19:19 UTC, vladbarsukov commented on src/features/create-request/ui/steps/index.tsx
> +import React, { useCallback, useEffect, useRef, useState } from 'react';
убрал

2024-01-26 10:04 UTC, AlexandrGerasimov63 approved these changes

2024-01-29 12:09 UTC, marussia1996 requested changes

2024-01-29 12:09 UTC, marussia1996 commented on src/features/create-request/ui/steps/index.tsx
> +                      buttonType="secondary"
поменяй тип кнопки на primary, чтобы она была синенькой)

2024-01-29 12:09 UTC, marussia1996 commented on src/features/create-request/ui/steps/index.tsx
> +                  <div className={styles.text}>
что ты убрал? тебе надо применить стили к этому элементу. Они у тебя были указаны (className={styles.text}), но в файле styles нет селектора text. У тебя стиль надписи не соответствуют макету.

2024-01-29 17:44 UTC, vladbarsukov commented on src/features/create-request/ui/steps/index.tsx
> +                      buttonType="secondary"
поменял

2024-01-31 12:11 UTC, marussia1996 requested changes
Видимо ты пропустил мой комментарий относящийся к Tooltip, открывающийся при нажатии на крестик. Давай еще раз посмотрим на стиль надписи в нем. У тебя в коде написан селектор, который применяется к div (className={styles.text}), однако в файле со стилями у тебя нет такого селектора, из-за этого стиля у надписи нет, а должен быть. Давай все же добавим стиль для текста (можешь для этого использовать готовые assets в папке app/assets/styles)

2024-01-31 13:35 UTC, kspshnik commented
коде написан селектор, который применяется к div (className={styles.text}), 

Вообще сама идея `div` для текста представляется мне несколько корявой.

2024-02-02 09:42 UTC, marussia1996 approved these changes
Супер

2024-02-02 09:43 UTC, merged