Механика работы с картой
ya-pomogau/frontend pull request #139
Opened 2024-01-31 20:56 UTC by ArturKaramov

Соединил функционал работы с картой волонтеров и реципиентов.
Вмерджил ветку features/recipient-Map в feature/volunteer, потестил - вроде ничего не сломалось.

2024-02-02 09:48 UTC, marussia1996 reviewed
пока не мержить этот pr

2024-02-02 16:34 UTC, AlexandrGerasimov63 approved these changes, later dismissed

2024-02-02 18:55 UTC, marussia1996 requested changes
еще по поводу радиуса вопрос, а почему при его появлении пропадают таски?)

2024-02-02 18:55 UTC, marussia1996 commented on src/widgets/map/index.tsx
> +          <Mark
привет, посмотрела карту, есть вопросы. Метка положения пользователя на карте выглядит абсолютно так же как метка таски (хотя не должна). Это может ввести пользователя в заблуждение (запишем как улучшение на будущее, сейчас править не надо). Также эта метка сейчас может двигаться, для чего? Я понимаю, что ты взял код Саши, который реализовал эту метку, для карты при создании таски, но в случае карты волонтера, у этой метки надо устанавливать значение draggable = false. Наверное стоит придумать какое-то условие для этого)

2024-02-02 18:55 UTC, marussia1996 commented on src/widgets/map/Mark.tsx
> +  const onUncomfirmedClick = () => {
Магическим образом у вас из ветки feature/volunteer а соответственно и у тебя пропал функционал, который делала Юля (у не активного пользователя кнопка Откликнуться серая и при нажатии открывается попап) 
если добавить этот код, то сможешь этот функционал восстановить
![image](https://github.com/ya-pomogau/frontend/assets/29862392/ac781f2e-d95a-4f57-ad9b-7071f836f9db)
![image](https://github.com/ya-pomogau/frontend/assets/29862392/a98b52e9-b0c9-495f-ac43-3d4e11f60f46)
Так же надо подправить db.json (укажу в отдельном комменте где)

2024-02-02 18:55 UTC, marussia1996 commented on server/db.json
> +      "role": "volunteer",
здесь надо роль указать с большой буквы "Volunteer"

2024-02-02 18:55 UTC, marussia1996 commented on src/shared/ui/page-layout/styles.module.css
Также потерялся функционал появления сообщения о том, что пока волонтера не подтвердят он не сможет откликаться. 
Если добавить этот код в page-layout.tsx, то сможешь восстановить это
![image](https://github.com/ya-pomogau/frontend/assets/29862392/7309e478-fb3e-466f-94ad-755d8c780f89)
![image](https://github.com/ya-pomogau/frontend/assets/29862392/bc8511d6-ecd0-4ffe-b31c-cbee1dc4c392)

2024-02-02 22:18 UTC, ArturKaramov commented
@marussia1996 
Привет! По поводу радиуса: фильтруются таски, которые за пределами радиуса поиска. Тут скорее вопрос: а нужно ли отображение этого круга?) (я про <Circle />)

Изначально я его добавил в надежде, что смогу зум карты подстроить под круг, но в итоге сделал это другим способом.

2024-02-04 10:08 UTC, marussia1996 commented
> @marussia1996 Привет! По поводу радиуса: фильтруются таски, которые за пределами радиуса поиска. Тут скорее вопрос: а нужно ли отображение этого круга?) (я про Circle )
> 
> Изначально я его добавил в надежде, что смогу зум карты подстроить под круг, но в итоге сделал это другим способом.

Запишу это в доработку или переработку, еще подумаем как это должно быть попозже.

2024-02-04 10:09 UTC, marussia1996 submitted a review, later dismissed

2024-02-04 10:24 UTC, AlexandrGerasimov63 approved these changes, later dismissed

2024-02-04 12:07 UTC, marussia1996 approved these changes, later dismissed

2024-02-04 12:07 UTC, Anton-Laid approved these changes, later dismissed

2024-02-04 12:07 UTC, marussia1996 approved these changes, later dismissed

2024-02-04 12:08 UTC, AlexandrGerasimov63 approved these changes, later dismissed

2024-02-04 12:11 UTC, INextYP approved these changes, later dismissed

2024-02-04 12:18 UTC, AlexandrGerasimov63 approved these changes, later dismissed

2024-02-04 12:19 UTC, Anton-Laid approved these changes

2024-02-04 12:19 UTC, closed without merging