Fix/task type
ya-pomogau/frontend pull request #144
Opened 2024-02-05 17:29 UTC by marussia1996

переделала типизацию таски

2024-02-05 17:30 UTC, AlexandrGerasimov63 submitted a review, later dismissed

2024-02-05 18:06 UTC, INextYP submitted a review, later dismissed
Отлично! Умничка 🥇

2024-02-05 18:21 UTC, kspshnik requested changes
Чуть-чуть поправить нейминг - и прекрасно :)

2024-02-05 18:21 UTC, kspshnik commented on src/entities/task/types.ts
> +  id: string;
`_id` всё-таки :)

2024-02-05 18:21 UTC, kspshnik commented on src/entities/task/types.ts
> +export type Taskschema = {
И `Task**S**chema` $)

2024-02-05 18:21 UTC, kspshnik commented on src/entities/task/types.ts
>    chat?: {
Это нинужна, убираем

2024-02-05 18:21 UTC, kspshnik commented on src/entities/task/ui/task/index.tsx
> +// TODO: сделать передачу item в TaskItem вместо тысячи пропсов
А тут нельзя брать из хранилища просто?

2024-02-05 18:21 UTC, kspshnik commented on src/entities/user/types.ts
> +  id: string;
В профиле разве есть `id`?

2024-02-05 18:24 UTC, marussia1996 commented on src/entities/user/types.ts
> +  id: string;
![image](https://github.com/ya-pomogau/frontend/assets/29862392/21136432-a2f6-4406-8ec5-6e8ae961eba2)
а это поле у тебя на бэке означает не id?)

2024-02-05 18:27 UTC, marussia1996 commented on src/entities/task/types.ts
> +export type Taskschema = {
Ох, я вообще забыла это переименовать в Task :(

2024-02-05 18:32 UTC, marussia1996 commented on src/entities/task/types.ts
> +  id: string;
И почему всё-таки?)

2024-02-05 18:34 UTC, marussia1996 commented on src/entities/task/ui/task/index.tsx
> +// TODO: сделать передачу item в TaskItem вместо тысячи пропсов
наверняка можно, но идем по курсу наименьшего сопротивления

2024-02-05 18:36 UTC, marussia1996 commented on src/entities/task/types.ts
>    chat?: {
хорошо)

2024-02-05 18:39 UTC, kspshnik commented on src/entities/task/ui/task/index.tsx
> +// TODO: сделать передачу item в TaskItem вместо тысячи пропсов
ОК, это в бэклог на "после mvp"

2024-02-05 18:40 UTC, kspshnik commented on src/entities/task/types.ts
> +  id: string;
По Мангусту :) В БД поле `_id`. В схемах/моделях Мангуста поле `_id`.

2024-02-05 18:41 UTC, kspshnik commented on src/entities/user/types.ts
> +  id: string;
Этот тип не очень актуален, тащемта. См. 

```ts
export interface GenericUserModelInterface {
  name: string;
  phone: string;
  avatar: string;
  address: string;
  vkId: string;
  role: string;
}
```

2024-02-05 18:45 UTC, marussia1996 commented on src/entities/user/types.ts
> +  id: string;
то есть в схеме указано recipient: UserProfile, но на самом деле это recipient: GenericUserModelInterface, так получается?)

2024-02-05 18:58 UTC, kspshnik commented on src/entities/user/types.ts
> +  id: string;
Маш, профиль убили недели две назад :)

```ts
export class User extends Document implements GenericUserModelInterface {
  @Prop({ required: true, type: mongoose.SchemaTypes.String })
  address: string;

  @Prop({ default: '', type: mongoose.SchemaTypes.String })
  avatar: string;

  @Prop({ required: true, type: mongoose.SchemaTypes.String })
  name: string;

  @Prop({ required: true, type: mongoose.SchemaTypes.String })
  phone: string;

  @Prop({ required: true, unique: true, type: SchemaTypes.String })
  vkId: string;

  @Prop({
    type: SchemaTypes.String,
    required: true,
    enum: Object.values(UserRole),
  })
  role: string;
}
```

2024-02-06 17:59 UTC, AlexandrGerasimov63 submitted a review, later dismissed

2024-02-08 06:36 UTC, kspshnik commented on src/pages/profile-active/index.tsx
> +  console.log(tasks);
Для сложных объектов лучше использовать `console.dir()` ;o)

2024-02-08 06:39 UTC, kspshnik reviewed
Всё верно, только мелкие очепятки типа `id` <-> `_id`.

И @marussia1996, для откладываемых на "после MVP" улучшений, классно бы сразу создавать issues, откладывая их в backlog. Дабы не потерялись с перепугу :)

2024-02-08 06:39 UTC, kspshnik commented on src/shared/ui/dropdown/index.tsx
> +  const categoryId = tasks.map((item: Task) => item.category.id);
У категории тоже будет `_id`

2024-02-08 06:39 UTC, kspshnik commented on src/widgets/map/Mark.tsx
> +  id?: string;
`_id`, не?

2024-02-08 06:39 UTC, kspshnik commented on src/widgets/map/Mark.tsx
>    fullName?: string;
Его убили в пользу `name` же?

2024-02-08 06:39 UTC, kspshnik commented on src/widgets/map/index.tsx
> +                fullName={task.recipient.name}
Надо бы избавиться от `fullName` ;o)

2024-02-08 09:49 UTC, marussia1996 commented on src/shared/ui/dropdown/index.tsx
> +  const categoryId = tasks.map((item: Task) => item.category.id);
ок

2024-02-08 09:50 UTC, marussia1996 commented on src/widgets/map/Mark.tsx
> +  id?: string;
ок

2024-02-08 09:51 UTC, marussia1996 commented on src/widgets/map/Mark.tsx
>    fullName?: string;
ну окей, будет это name, но кажется моя задача посвящена не переименованию пропсов, ты мне предлагаешь во всем коде переименовать пропсы?) так то и про coordinates можно сказать, что мы заменили их на location

2024-02-08 09:54 UTC, marussia1996 commented on src/widgets/map/index.tsx
> +                fullName={task.recipient.name}
опять же повторюсь, pr не про изменение названий пропсов:) Для этого заведены задачи на правки.

2024-02-08 10:59 UTC, kspshnik commented on src/widgets/map/index.tsx
> +                fullName={task.recipient.name}
Ну сделай issue и в backlog его :)

2024-02-08 10:59 UTC, kspshnik commented on src/widgets/map/Mark.tsx
>    fullName?: string;
Ну сделай issue и в backlog его :)

2024-02-08 11:30 UTC, kspshnik approved these changes

2024-02-08 11:33 UTC, kspshnik approved these changes
Отлично :)

2024-02-08 11:36 UTC, INextYP approved these changes
🥇

2024-02-09 13:40 UTC, merged