Fix/filter types
ya-pomogau/frontend pull request #150
Opened 2024-02-06 13:07 UTC by Anton-Laid

Поправил логики компонента

2024-02-06 13:51 UTC, INextYP reviewed
Пока в PR очень много изменений @marussia1996, т.к. они не в Develop

2024-02-06 13:53 UTC, marussia1996 requested changes

2024-02-06 13:53 UTC, marussia1996 commented on src/features/filter/filter.stories.tsx
если ты не используешь переменные mockedRecipientState и т.п, то зачем они тебе?

Добавь пожалуйста еще отображение фильтра для админа

2024-02-06 13:54 UTC, marussia1996 commented
> Пока в PR очень много изменений @marussia1996, т.к. они не в Develop

Вижу, но можно посмотреть по последнему коммиту изменения.

2024-02-07 14:48 UTC, AlexandrGerasimov63 submitted a review, later dismissed

2024-02-08 13:30 UTC, kspshnik approved these changes, later dismissed
Ага :)

2024-02-08 14:15 UTC, AlexandrGerasimov63 approved these changes, later dismissed

2024-02-10 09:32 UTC, marussia1996 submitted a review, later dismissed

2024-02-11 11:14 UTC, AlexandrGerasimov63 approved these changes, later dismissed

2024-02-11 12:30 UTC, AlexandrGerasimov63 submitted a review, later dismissed

2024-02-11 12:33 UTC, kspshnik approved these changes, later dismissed
Отлично :)

2024-02-11 12:42 UTC, marussia1996 approved these changes

2024-02-11 12:42 UTC, AlexandrGerasimov63 approved these changes

2024-02-11 12:42 UTC, merged