Fix/user types
ya-pomogau/frontend pull request #152
Opened 2024-02-07 17:34 UTC by marussia1996

2024-02-08 06:32 UTC, kspshnik requested changes

2024-02-08 06:32 UTC, kspshnik commented on src/services/system-slice.ts
> +export const isRootSelector: TCustomSelector<boolean | undefined> = (state) =>
Здесь **не может** быть `undefined`. Просто by design: селектор вернёт boolean при _любом_ наполнении `state.system.user` и/или `state.system.user.isRoot` - это логическое выражение.

2024-02-08 06:32 UTC, kspshnik commented on src/services/user-api.ts
> +        url: body.file ? `users/avatar/${body._id}` : `users/${body._id}`,
TODO: вынести все URL в константы, в идеале наполняемые из переменных окружения.

2024-02-08 06:32 UTC, kspshnik commented on src/widgets/map/Mark.tsx
> +  id?: string;
Это про таску? Тогда тоже `_id` ;o)

2024-02-08 06:32 UTC, kspshnik commented on src/widgets/page-sub-menu/components/page-sub-menu-for-admins/page-sub-menu-for-admins.tsx
> +  if (role === UserRole.USER) {
Не-а. Тут проверяем на `isRoot` ;o)

2024-02-08 06:32 UTC, kspshnik commented on src/widgets/side-menu/components/side-menu-for-authorized.tsx
> +  if (role === UserRole.USER) return <MasterSideMenu />;
Аналогично, признак суперадмина - `isRoot === true`

2024-02-08 11:19 UTC, marussia1996 commented on src/services/system-slice.ts
> +export const isRootSelector: TCustomSelector<boolean | undefined> = (state) =>
как мне это сделать если поле isRoot не обязательное? 
![image](https://github.com/ya-pomogau/frontend/assets/29862392/2aa7675c-b735-445f-bd0b-61a94ee54529)

на бэке только у админов есть это поле 
![image](https://github.com/ya-pomogau/frontend/assets/29862392/09bc27d3-3244-43ec-804a-a0270257aad9)

или я не правильно разобралась? объясни

2024-02-08 11:20 UTC, marussia1996 commented on src/services/user-api.ts
> +        url: body.file ? `users/avatar/${body._id}` : `users/${body._id}`,
зачем мне менять это, если этот код будет переписываться, когда будем писать слайсы ?)

2024-02-08 11:22 UTC, marussia1996 commented on src/widgets/page-sub-menu/components/page-sub-menu-for-admins/page-sub-menu-for-admins.tsx
> +  if (role === UserRole.USER) {
почему? для чего тогда нам userRole.User?

2024-02-08 11:22 UTC, marussia1996 commented on src/widgets/side-menu/components/side-menu-for-authorized.tsx
> +  if (role === UserRole.USER) return <MasterSideMenu />;
а роль не является признаком?)

2024-02-08 11:22 UTC, marussia1996 commented on src/widgets/map/Mark.tsx
> +  id?: string;
вынесла задачу в backlog

2024-02-08 11:38 UTC, kspshnik commented on src/services/system-slice.ts
> +export const isRootSelector: TCustomSelector<boolean | undefined> = (state) =>
Маш, это _логичекое_ выражение. Оно может дать **только** `true` или `false`.
При приведении к логическому типу `undefined` даст `false`, и результат будет `false`.

В принципе, можно записать как `!!state.system.user && (state.system.user.isRoot ?? false)` - так точно не пролезет.

2024-02-08 11:39 UTC, kspshnik commented on src/services/user-api.ts
> +        url: body.file ? `users/avatar/${body._id}` : `users/${body._id}`,
Если будем.

2024-02-08 11:40 UTC, kspshnik commented on src/widgets/page-sub-menu/components/page-sub-menu-for-admins/page-sub-menu-for-admins.tsx
> +  if (role === UserRole.USER) {
Не знаю :)
Думаю, это обломки того времени, когда мы предполагали, что обычный юзверь может быть конвертирован. На бэкенде такого значения нет.

2024-02-08 11:41 UTC, marussia1996 commented on src/services/system-slice.ts
> +export const isRootSelector: TCustomSelector<boolean | undefined> = (state) =>
спасибо за подсказку)

2024-02-08 11:41 UTC, kspshnik commented on src/widgets/side-menu/components/side-menu-for-authorized.tsx
> +  if (role === UserRole.USER) return <MasterSideMenu />;
ет. © 
И админ, и мастер имеют одинаковую роль :)

2024-02-08 11:42 UTC, kspshnik requested changes
Мастера надо определять именно по `isRoot`.

2024-02-08 11:46 UTC, marussia1996 commented on src/widgets/page-sub-menu/components/page-sub-menu-for-admins/page-sub-menu-for-admins.tsx
> +  if (role === UserRole.USER) {
всмысле нет?? а это что тогда?)
![image](https://github.com/ya-pomogau/frontend/assets/29862392/64fe51ae-27f3-47a0-b2ed-d3a32ec8c238)

2024-02-08 11:48 UTC, marussia1996 commented on src/widgets/side-menu/components/side-menu-for-authorized.tsx
> +  if (role === UserRole.USER) return <MasterSideMenu />;
Женя где это вообще написано?) для чего роль тогда четвертая есть....

2024-02-08 11:49 UTC, kspshnik commented on src/widgets/page-sub-menu/components/page-sub-menu-for-admins/page-sub-menu-for-admins.tsx
> +  if (role === UserRole.USER) {
Обломки старого с перспективой возрождения :))
Такая роль при создании присваивается примерно никогда.

2024-02-08 11:51 UTC, kspshnik commented on src/widgets/side-menu/components/side-menu-for-authorized.tsx
> +  if (role === UserRole.USER) return <MasterSideMenu />;
Эта роль была как начальная6 когда предполагалось, что юзверь выбирает себе кем быть, или не выбирает - если его производят в админы.
Потом ~~концепция~~ понимание изменилось, и просто юзверя - не волонтёра/реципиента/админа - не бывает.
А тип не почистили, поленились.

2024-02-08 11:54 UTC, marussia1996 commented on src/widgets/side-menu/components/side-menu-for-authorized.tsx
> +  if (role === UserRole.USER) return <MasterSideMenu />;
аааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааа где тут смайлик разъеренного, вот представь его и умножь на миллион. вот на столько я злюсь.

2024-02-08 12:02 UTC, kspshnik commented on src/widgets/side-menu/components/side-menu-for-authorized.tsx
> +  if (role === UserRole.USER) return <MasterSideMenu />;
Ну а зачем иначе нам отдельный признак рута-то?

2024-02-08 12:04 UTC, marussia1996 commented on src/widgets/side-menu/components/side-menu-for-authorized.tsx
> +  if (role === UserRole.USER) return <MasterSideMenu />;
всего этого можно было бы избежать, если была бы готова дока..

2024-02-09 11:27 UTC, kspshnik submitted a review, later dismissed

2024-02-09 17:44 UTC, kspshnik submitted a review, later dismissed
Всё хорошо, замечание в issue в backlog.

2024-02-09 17:44 UTC, kspshnik commented on src/shared/ui/page-layout/index.tsx
> +      {/* {isLoadingUserData && <Loader />} */}
TODO: Вот это кошмарище надо превратить будет потом в несколько компонент, оно адски плохо читается

2024-02-09 18:09 UTC, marussia1996 commented on src/shared/ui/page-layout/index.tsx
> +      {/* {isLoadingUserData && <Loader />} */}
да,  с этим Loader надо будет разбираться еще

2024-02-09 18:13 UTC, kspshnik submitted a review, later dismissed
И повторно всё ОК :)

2024-02-09 18:18 UTC, kspshnik approved these changes, later dismissed
И в третий раз ~~закинул старик невод~~ аппрувлю :)

2024-02-09 20:10 UTC, kspshnik submitted a review, later dismissed

2024-02-10 09:13 UTC, INextYP approved these changes, later dismissed

2024-02-10 12:04 UTC, kspshnik submitted a review, later dismissed

2024-02-10 12:27 UTC, kspshnik approved these changes, later dismissed

2024-02-10 12:38 UTC, kspshnik approved these changes, later dismissed

2024-02-10 12:43 UTC, kspshnik submitted a review, later dismissed
Всё отлично :)

2024-02-11 11:16 UTC, AlexandrGerasimov63 approved these changes, later dismissed

2024-02-11 12:03 UTC, merged