Uikit/buttons
ya-pomogau/frontend pull request #16
Opened 2023-05-23 17:49 UTC by TinaTezadova

2023-05-25 06:54 UTC, niksmo requested changes
Привет! Любой элемент формы это сложно и особенно кнопки. Немного доработать и будет классный сет с иконками.

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/arrow-button/index.tsx
> +  isPressed?: boolean;
Этот проп точно нужен? если мы хотим стилизовать кнопочку в нажатом состоянии, то это css псевдокласс :active

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/arrow-button/index.tsx
> +  disabled?: boolean;
Ты расширяешься от интерфейса, поэтому эти пропсы указывать не нужно

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/arrow-button/index.tsx
> +      { [styles["arrow-button--pressed"]]: isPressed },
Про псевдокласс написал выше, поэтому эта запись становится не нужна.

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/arrow-button/index.tsx
> +    disabled={disabled}
т.к. расширяемся от интерфейса этот проп явно указывать не нужно

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/button/index.tsx
> +  disabled?: boolean;
оставил коммент по этому в arrow-button

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/button/index.tsx
> +  isPressed?: boolean;
см. arrow-button

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/button/index.tsx
> +  disabled,
и так уже есть в ...props

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/button/index.tsx
> +  size?: "small" | "medium" | "large";
Проп меняет только падинги, а это можно делать и через extClassName и так будет правильней.

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/button/index.tsx
> +  isPressed,
:active

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/card-button/index.tsx
> +  isPressed?: boolean;
:active

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/card-button/index.tsx
> +  onClick?: () => void;
не нужен

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/edit-button/index.tsx
> +  onClick?: () => void;
не нужен

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/edit-button/index.tsx
> +  disabled?: boolean;
не нужен

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/edit-button/index.tsx
> +  disabled,
не нужен

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/round-button/index.tsx
> +  disabled?: boolean;
тоже самое

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/round-button/index.tsx
> +  disabled,
не нужен

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/round-button/index.tsx
> +  isPressed?: boolean;
:active

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/square-buttons/index.tsx
> +  isPressed?: boolean;
тоже самое

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/square-buttons/index.tsx
> +  icon?: ReactNode;
в round-button это был customIcon, давай придерживаться чего-то одного, чтобы другим было удобно работать с компонентом

2023-05-25 06:54 UTC, niksmo commented on src/shared/ui/vk-button/index.tsx
Это обычная кнопка + иконка. Т.к. это довольна распространённый случай, то нужно обычную кнопку научить принимать любую иконку в проекте.

2023-05-25 07:08 UTC, TinaTezadova commented on src/shared/ui/arrow-button/index.tsx
> +  isPressed?: boolean;
:active применяет стили в момент клика, а судя по макету pressed стили должны быть активны пока открыта стариница, которая привязана к кнопке (пример: figma.com/file/xYLbl9kLmcAwYCbAhCFMCy/ЯПомогаю-(Web)?type=design&node-id=416-6011&t=3tk81Rqn1fILZIxm-0). В целом этот пропс наверное имеет смысл оставить ток для этой кнопки

2023-05-25 07:10 UTC, TinaTezadova commented on src/shared/ui/arrow-button/index.tsx
> +  disabled?: boolean;
Указывала, чтобы этот пропс можно было устанавливать в сторибуке

2023-05-25 07:15 UTC, TinaTezadova commented on src/shared/ui/arrow-button/index.tsx
> +  isPressed?: boolean;
Ну или оставить такую возможность для всех кнопок, но дополнительно еще стили эти применять при :active

2023-05-25 07:25 UTC, niksmo commented on src/shared/ui/arrow-button/index.tsx
> +  isPressed?: boolean;
Именно эту кнопку можно будет стилизовать через extClassName уже на этапе сборки страницы.

2023-05-25 07:26 UTC, niksmo commented on src/shared/ui/arrow-button/index.tsx
> +  disabled?: boolean;
Ммм, сторибук очень гибкая вещь, это можно сделать и без явного объявления пропса.

2023-05-25 07:26 UTC, TinaTezadova commented on src/shared/ui/arrow-button/index.tsx
> +  isPressed?: boolean;
Действительно.. не подумала об этом. Поправлю, спасибо

2023-05-25 19:01 UTC, TinaTezadova commented on src/shared/ui/vk-button/index.tsx
Я вынесла эту кнопку в отдельный компонент, т.к по макету она отличается от стандартной кнопки по размерам + размер шрифта тоже другой

2023-05-25 19:06 UTC, TinaTezadova commented on src/shared/ui/vk-button/index.tsx
Не уверена, что будет правильно проигнорировать такое различие и модифицировать стандартную кнопку. Может этот компонент оставить, но доработать на прием любой иконки?

2023-05-25 19:08 UTC, TinaTezadova commented on src/shared/ui/vk-button/index.tsx
Ну либо просто добавлю в компонент со стандартной кнопкой новый вариант размера и прием иконки

2023-05-26 10:40 UTC, niksmo submitted a review, later dismissed
Привет! Восхитительно!

2023-05-26 10:41 UTC, niksmo approved these changes

2023-05-26 10:42 UTC, merged