Change/task type
ya-pomogau/frontend pull request #162
Opened 2024-02-15 10:49 UTC by marussia1996

изменила типизацию таски исходя из бэка. Добавила кнопку закрытия попапов на тасках

2024-02-15 11:04 UTC, INextYP submitted a review, later dismissed
Отлично!

2024-02-16 10:57 UTC, INextYP approved these changes, later dismissed

2024-02-16 12:57 UTC, kspshnik requested changes
В `vkId` может лежать **ТОЛЬКО** сам id. **Никакого** полного uri, это потребует переделки всего кода потом дважды.

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +        "vkId": "https://vk.com/id123456789",
Почему тут полный uri?

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +        "vkId": "https://vk.com/id123456789",
Почему тут полный uri?

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +        "vkId": "https://vk.com/id123456789",
Почему тут полный uri?

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +        "vkId": "https://vk.com/id123456789",
Почему тут полный uri?

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +        "vkId": "https://vk.com/id123456789",
Почему тут полный uri?

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +        "vkId": "https://vk.com/id123456789",
Почему тут полный uri?

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +        "vkId": "https://vk.com/id123456789",
Почему тут полный uri?

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +        "vkId": "https://vk.com/id123456789",
Почему тут полный uri?

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +        "vkId": "https://vk.com/id123456789",
Почему тут полный uri?

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +      "isPendingChanges": false,
Если один из отчётов не `null`, тут **должно** быть `true`

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +        "vkId": "https://vk.com/id123456789",
Почему тут полный uri?

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +      "moderator": null
Если было конфликтное закрытие (non nullish `adminResolve`, поле `moderator` **должно** быть заполнено данными администратора, модерировавшего конфликт.

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +        "vkId": "https://vk.com/id123456789",
Почему здесь полный uri?

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
>        "adminResolve": "pending",
При `adminResolve === ResolveStatus.PENDING` модератор конфликта *уже определён*, соответственно поле `moderator` **должно быть заполнено**

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +      "moderator": null
И почему задача с `status === TaskStatus.CONFLICTED && (adminResolve === ResolveStatus.PENDING || adminResolve === ResolveStatus.VIRGIN)` относится к  "завершённым"? Для этого надо `adminResolve === ResolveStatus.FULFILLED || adminResolve === ResolveStatus.REJECTED`, не?

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +        "vkId": "https://vk.com/id123456789",
Почему здесь полный uri?

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +        "vkId": "https://vk.com/id123456789",
Почему здесь полный uri?

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +        "vkId": "https://vk.com/id123456789",
Почему здесь полный uri?

2024-02-16 12:57 UTC, kspshnik commented on server/db.json
> +      "isPendingChanges": false,
А что задача со статусом `TaskStatus.CREATED` делает в завершённых? :)

2024-02-16 12:57 UTC, kspshnik commented on src/entities/task/ui/task-list/task-list.stories.tsx
> +          vkId: 'https://vk.com/id123456789',
Почему здесь полный uri?

Нинада ориентировать код на то, чего нет на бэкенде.

2024-02-16 12:57 UTC, kspshnik commented on src/entities/task/ui/task-list/task-list.stories.tsx
> +          vkId: 'https://vk.com/id123456789',
Почему здесь полный uri?

2024-02-16 12:57 UTC, kspshnik commented on src/entities/task/ui/task-list/task-list.stories.tsx
> +          vkId: 'https://vk.com/id123456789',
Почему здесь полный uri?

2024-02-16 14:11 UTC, marussia1996 commented on src/entities/task/ui/task-list/task-list.stories.tsx
> +          vkId: 'https://vk.com/id123456789',
я не ориентирую код на то чего нет в бэке. это просто строка. для примера. я понимаю что будут там циферки. Если тебе будет так спокойней я поменяю это на циферки.

2024-02-16 14:32 UTC, INextYP approved these changes, later dismissed

2024-02-16 14:46 UTC, kspshnik submitted a review, later dismissed
Поправь, пожалуйста, ещё одно несовпадение - и ОК. Даже просто отлично ;)

2024-02-16 14:46 UTC, kspshnik commented on server/db.json
> +      "isPendingChanges": false,
Если отчёты совпадают, `adminResolve` и `moderator` **должны** быть `null`, а `status`- `TaskStatus.COMPLETED`

2024-02-16 17:14 UTC, Anton-Laid approved these changes

2024-02-16 17:17 UTC, INextYP approved these changes

2024-02-16 17:21 UTC, kspshnik approved these changes
Вмёрживай!

2024-02-16 19:02 UTC, merged