Request/create task
ya-pomogau/frontend pull request #164
Opened 2024-02-18 10:52 UTC by marussia1996

сделаны основные запросы к серверу для работы волонтеров и реципиентов

2024-02-18 17:04 UTC, kspshnik requested changes
Опять же - работа огромная, но предложу две вещи:
1. Косяк с эффектом **надо** поправить сразу.
2. Этот PR вмёрживать _после_ #166.

Вынесение повторяющегося кода - выносим в issue и делаем после показа MVP.

2024-02-18 17:04 UTC, kspshnik commented on src/features/create-request/ui/steps/index.tsx
> +  }, []);
А вот `dispatch(setCategoryList(categories))` надо вынести в **другой** эффект.

2024-02-18 17:04 UTC, kspshnik commented on src/pages/profile-completed/index.tsx
> +  let query = '';
Этот код встречается повсеместно. **После демонстрации MVP** его надо вынести в хелпер.

2024-02-27 15:09 UTC, INextYP approved these changes, later dismissed

2024-02-28 11:12 UTC, Anton-Laid approved these changes, later dismissed

2024-02-28 16:21 UTC, INextYP approved these changes, later dismissed

2024-03-02 11:10 UTC, kspshnik submitted a review, later dismissed

2024-03-04 16:20 UTC, AlexandrGerasimov63 submitted a review, later dismissed

2024-03-04 16:20 UTC, INextYP submitted a review, later dismissed
💯

2024-03-04 16:21 UTC, AlexandrGerasimov63 submitted a review, later dismissed

2024-03-04 16:46 UTC, AlexandrGerasimov63 approved these changes

2024-03-04 16:49 UTC, INextYP approved these changes
🥇

2024-03-04 16:49 UTC, merged