Исправление ошибки 401
ya-pomogau/frontend pull request #176
Opened 2024-03-12 13:32 UTC by AlexandrGerasimov63

Ребята, у меня вопросы остались по этой задаче.
Есть ли нормальное решение или это и есть нормальное решение?

2024-03-13 07:08 UTC, INextYP commented
Привет! А если токен вынести в файл с константами и оттуда дергать? Обычно так делаем, дабы избежать дублирования кода и если токен понадобится в других местах

2024-03-13 07:18 UTC, kspshnik commented
> Привет! А если токен вынести в файл с константами и оттуда дергать? Обычно так делаем, дабы избежать дублирования кода и если токен понадобится в других местах

А ничего, что токен на каждой авторизации новый выдаётся? :)

2024-03-13 08:51 UTC, INextYP commented
> > Привет! А если токен вынести в файл с константами и оттуда дергать? Обычно так делаем, дабы избежать дублирования кода и если токен понадобится в других местах
> 
> А ничего, что токен на каждой авторизации новый выдаётся? :)

Не так написал.

Я имею ввиду, что можно сделать что-то типа такого:
```
export const LOCAL_STORAGE_TOKEN_ACCESS = "token_access";

export const getTokenAccess = () => {
  return localStorage.getItem(LOCAL_STORAGE_TOKEN_ACCESS);
};

export const setTokenAccess = (token: string) => {
  return localStorage.setItem(LOCAL_STORAGE_TOKEN_ACCESS, token);
};
```

2024-03-13 09:39 UTC, kspshnik commented
> Я имею ввиду, что можно сделать что-то типа такого:
> 
> ```js
> export const LOCAL_STORAGE_TOKEN_ACCESS = "token_access";
> 
> export const getTokenAccess = () => {
>   return localStorage.getItem(LOCAL_STORAGE_TOKEN_ACCESS);
> };
> 
> export const setTokenAccess = (token: string) => {
>   return localStorage.setItem(LOCAL_STORAGE_TOKEN_ACCESS, token);
> };
> ```

Не можно, а **НУЖНО**!
Согласен полностью.

2024-03-18 16:05 UTC, INextYP requested changes

2024-03-18 16:05 UTC, INextYP commented on src/shared/libs/permissions-names.ts
Странно, что ты положил эту переменную именно сюда)

2024-03-18 16:05 UTC, INextYP commented on src/services/user-task-api.ts
> +          // headers,
Давай не будем оставлять закомментированный код!?)

2024-03-18 16:22 UTC, marussia1996 reviewed
токен запихни в файл \frontend\src\config\api-config.ts, а файла permissions у нас по-идеи не должно быть, там не актуалььная информация

2024-03-18 16:44 UTC, INextYP approved these changes

2024-03-18 17:03 UTC, marussia1996 approved these changes

2024-03-18 17:05 UTC, merged