Fix/admin pages bags
ya-pomogau/frontend pull request #177
Opened 2024-03-13 15:33 UTC by Anton-Laid

Исправление стилей у карточек и контейнеров в desktop и module, добавил фильтр по имени для карточек

2024-03-18 16:19 UTC, INextYP requested changes

2024-03-18 16:19 UTC, INextYP commented on src/widgets/user-card/components/user-info.tsx
> +          className={classnames(
Вот со всеми такими вычислениями я бы посоветовал поступить следу.щим образом:
1. Вынести все выражения вида:
```js
classnames(classes.id, 'm-0 text text_size_small text_type_regular')
```
в переменные до возврата разметки.

2. Заиспользовать эти переменные в разметке.

Что мы этим добьёмся?
1. Приводим код к чистому виду, когда в разметке только теги и пропсы к ним, без высчитываний стилей.
2. Иногда устраняем дублирование

2024-03-18 16:24 UTC, marussia1996 approved these changes

2024-03-31 13:26 UTC, INextYP approved these changes

2024-04-02 18:41 UTC, merged