Fix/recipient tasks
ya-pomogau/frontend pull request #178
Opened 2024-03-14 09:57 UTC by jsapro

#168
- исправлено отображение аватарки
- откорректирован текст при валидации и исправлена вёрстка для отображения длинного текста
- исправлено отображение карты при редактировании 
- настроено позиционирование тултипа относительно модалки чтобы он не смещался при разной высоте модалки
- исправлено редактирование таски
- настроена отмена заявки (с учётом количества времени до окончания)

2024-03-26 13:18 UTC, marussia1996 requested changes

2024-03-26 13:18 UTC, marussia1996 commented on src/widgets/task-buttons-content/index.tsx
> +  const [deleteTask] = useDeleteTaskMutation();
я правильно понимаю, что ты удалил использование функции на установку таски в состояние "волонтер/реципиент считает что таска не выполнена" и заменил на удаление? Не нашла у тебя в коде применение этого запроса. Получается что изменить состояние выполнения/не выполнения таски мы не можем. На сколько помню,  при нажатии на воскл. знак у нас должен происходить запрос на изменение reject, а при нажатии на крестик как раз происходит удаление. А в твоем коде я вижу, что удаление происходит и при нажатии на крестик и при нажатии на конфликт) Верни пожалуйста вызов функции rejectTask в код)

2024-04-03 14:34 UTC, marussia1996 approved these changes

2024-04-03 16:00 UTC, INextYP commented
Все основные правки будут в PR https://github.com/ya-pomogau/frontend/pull/186

2024-04-03 16:00 UTC, closed without merging