UI/info container
ya-pomogau/frontend pull request #18
Opened 2023-05-24 07:04 UTC by AlenaIsmagilova

2023-05-25 07:22 UTC, niksmo requested changes
Привет! Оставил комментарии. Правки небольшие.

2023-05-25 07:22 UTC, niksmo commented on src/shared/ui/info-container-content/index.tsx
> +interface IInfoContainerContent {
нужен extClassName чтобы стилизовать

2023-05-25 07:22 UTC, niksmo commented on src/shared/ui/info-container-content/index.tsx
> +  <>
Т.к. будет extClassName, нужен див. +- 1 обёртка погоды нам не сделает

2023-05-25 07:22 UTC, niksmo commented on src/shared/ui/info-container/index.tsx
> +  link: string;
Кажется что можно сделать link опциональным и его уже использовать в тернарном выражении

2023-05-25 07:22 UTC, niksmo commented on src/shared/ui/info-container/index.tsx
> +  avatarName: string;
Предлагаю его хардкоднуть сразу внутри компонента

2023-05-25 07:22 UTC, niksmo commented on src/shared/ui/info-container/index.tsx
> +      className={classNames(styles["info-container-image"], extClassName)}
extClassName давай сделаем только основной обёртке, а то если передать какой-нибудь margin, то он примениться везде где указан extClassName

2023-05-25 07:22 UTC, niksmo commented on src/shared/ui/info-container/info-container.stories.ts
Давай сделаем комбинированный сторис вместе с info-content, как раз будет видно как они стыкуются и работают

2023-05-29 07:11 UTC, AlenaIsmagilova commented on src/shared/ui/info-container/info-container.stories.ts
Коля, привет. Не могу сделать комбинированную сторю, долго сижу с ошибкой ts, нужна помощь

2023-05-29 19:28 UTC, niksmo approved these changes
Огонь! Здорово всё прям классненько!🚀

2023-05-29 19:28 UTC, merged