Fix/use permission
ya-pomogau/frontend pull request #201
Opened 2024-06-09 19:01 UTC by AlexeyKrutyakov

2024-06-09 19:36 UTC, AlexeyKrutyakov commented
- Добавил проверку на isRoot пользователя
- выполнил сравнение длины массива requirments (она должна быть равна длине hasPermission. Если да, то isAllowed = true иначе isAllowed = false)
- исправил орфографические ошибки в слове requirements
- добавил комментарий о проверке на isRoot

2024-06-10 15:49 UTC, INextYP requested changes
Привет! Работа хорошая, но я бы посоветовал упростить код. Оставил комментарии ниже :)

2024-06-10 15:49 UTC, INextYP commented on src/shared/hooks/use-permission.tsx
>      if (userRole) {
Давай все-таки приведем к более читабельному виду:

1. Если пользователь `isRoot` то сразу вернем true (нам тут всё-равно на роль).

```js
if (userIsRoot) {
    return true;
  }
```

2. Проверяeм совпадение ролей, если первый пункт не сработал:
```js
if (userRole !== role) {
    return false;
  }
```

3. Если первый два пункта не сработали, то остается только проверить, чтобы все права совпали. Тут нет смысла фильтровать, а зачем ещё и проверять длину отфильтрованного массива, у нас же есть великий и неподражаемый `every`.
4.  В методе `.some` нет смысла в приведении к строке с помощью  `JSON.stringify`. Достаточно будет просто сравнить `element === requirement`;
5. Нет смысла формировать объект `userRights`. Проще сделать так (меньше действий):

```js
const hasPermission = requirements.every((requirement) =>
    [userStatus, ...userPermissions].some((element) => element === requirement)
  );
```

p.s. чтобы конструкция выше сработала, нужно сделать так:
```js
const userPermissions =
    useAppSelector((state) => state.user.data?.permissions) || [];

// или

const hasPermission = requirements.every((requirement) =>
    [userStatus, ...(userPermissions || [])].some(
      (element) => element === requirement
    )
  );

```

По итогу, в `hasPermission` будет содержаться `true`, если права пользователя или статусы совпадают с переданными в хук  `requirements`

2024-06-10 15:49 UTC, INextYP commented on src/shared/hooks/use-permission.tsx
>  // TODO: возможно нужно будет дописать условие на isRoot тк админ и мастер имею одну и туже роль
TODO комментарии после завершения реализации можно удалить

2024-06-10 17:28 UTC, kspshnik commented on src/shared/hooks/use-permission.tsx
>      if (userRole) {
> Давай все-таки приведем к более читабельному виду:
> 
> 1. Если пользователь `isRoot` то сразу вернем true (нам тут всё-равно на роль).

Я бы тут всё-таки на админа проверил:

```ts

if (userRole === UserRoles.ADMIN && userIsRoot) {
    return true;
  } 
```

иначе дырочкой пахнет :)

2024-06-10 18:44 UTC, AlexeyKrutyakov commented
@INextYP , @kspshnik 
поправил всё, удалил todo, добавил в конце проверку на наличие хотя бы одного requirement, помимо userStatus

2024-06-12 01:02 UTC, kspshnik requested changes
@AlexeyKrutyakov это вопрос(ы) не к твоей реализации, но возможно имеет смысл поправить :)

2024-06-12 01:02 UTC, kspshnik commented on src/shared/hooks/use-permission.tsx
> +  return hasPermission && requirements.length > 1;
А в чём тогда смысл передавать роль и контролировать статус? При такой проверке она может быть только `UserRoles.ADMIN`, а статус сразу теряет своё значение для администратора - у них другое мерило активности, или мы пропустим условно волонтёру изменение категорий, например.
Возможно, надо заложить требование именно `UserRoles.ADMIN` и активности, и проверять дополнительные разрешения только в этом случае, а любому не админу - сразу отлуп давать?

А именно контроль ролей/статусов - сделать отдельным хуком/хуками?
@INextYP что скажешь?

2024-06-12 01:02 UTC, kspshnik commented on src/shared/hooks/use-permission.tsx
>  type Role = UserRole.VOLUNTEER | UserRole.RECIPIENT | UserRole.ADMIN;
И, раз уж мы этого коснулись, давай заменим `enum`-ы оба в `'shared/types/common.types'` на следующие конструкции:

```ts
export const EnumLike = {
  prop: 'prop',
  numProp: 22,
// ну и так далее :)
} as const;

export type EnumLike = keyof typeof EnumLike;
```

2024-06-12 05:56 UTC, INextYP commented on src/shared/hooks/use-permission.tsx
> +  return hasPermission && requirements.length > 1;
@kspshnik Разделение в отдельные хуки - отличная идея, но уж слишком болезненно на текущий момент и неприоритетно. Как говорится - "работает - не трогай" :) Чтобы никто не накосячил с передачей в хук нужных значений, могу предложить такой вариант:

```
type UserRequirements =
  | UserStatus.CONFIRMED
  | UserStatus.UNCONFIRMED
  | UserStatus.ACTIVATED
  | UserStatus.VERIFIED
  | UserStatus.BLOCKED;

type AdminRequirements = `${AdminPermission}` // если админу статусы не нужны, то и не будем передавать их ему

type Role = UserRole.VOLUNTEER | UserRole.RECIPIENT | UserRole.ADMIN;

type Requirements<R extends Role> = R extends UserRole.ADMIN
  ? AdminRequirements
  : UserRequirements;

export default function usePermission<R extends Role>(
  requirements: <Requirements<R>[],
  role: R
)
```

При этом, менять в других местах не потребуется:

![image](https://github.com/ya-pomogau/frontend/assets/70805943/7437c73a-3299-4a07-9f61-7017dff933b6)

А при передаче например волонтеру админского разрешения мы получим:
![image](https://github.com/ya-pomogau/frontend/assets/70805943/d87285ec-30d1-4b07-adb4-cd6855065cd8)

2024-06-12 06:00 UTC, INextYP commented on src/shared/hooks/use-permission.tsx
>  type Role = UserRole.VOLUNTEER | UserRole.RECIPIENT | UserRole.ADMIN;
В рамках задачи это не требуется. Если менять, то менять всё, но отдельной задачей. Не старайтесь исправить всё. Разработка должна быть модульной

2024-06-14 11:50 UTC, AlexeyKrutyakov commented
@kspshnik , @INextYP привет
я правильно понял, `userStatus` передается в хук в любом случае, не смотря на то, обычный это пользователь или админ?

2024-06-14 12:29 UTC, AlexeyKrutyakov commented
@kspshnik , @INextYP 
я поправил, посмотрите, всё ли так

2024-06-14 18:47 UTC, INextYP approved these changes
Всё хорошо

2024-06-14 18:49 UTC, merged