Fix/admin menu
ya-pomogau/frontend pull request #204
Opened 2024-06-10 19:53 UTC by LatyshevDD

- исправлено отображение кнопки "написать администратору" в компоненте DropDownMenu
- исправлено отображение элемента title__background  у кнопки выхода в компоненте DropDownMenu

2024-06-11 13:16 UTC, marussia1996 requested changes
Логика отображения для разных ролей работает корректно, молодец:) Однако есть недочеты по верстке, посмотри пожалуйста повнимательнее на расположение меню на макете и у нас в проекте, оно различается 
![image](https://github.com/ya-pomogau/frontend/assets/29862392/40594e13-db8a-454c-a4ca-276efb152646)
![image](https://github.com/ya-pomogau/frontend/assets/29862392/e3009a8e-cff6-4915-89f3-e7b9664d2163)
Также обрати внимание, что при смене разрешения менюшка уплывает куда-то не туда) Надо подумать над тем как это решить, будут предложения - пиши, обсудим.
![image](https://github.com/ya-pomogau/frontend/assets/29862392/e80ef690-d190-424e-bdfc-5868397b816f)

2024-06-12 07:20 UTC, LatyshevDD commented
Все поправил. Насчет плавности пока предлагаю просто установить значения отступов в относительной величине (реализовал в коде).

2024-06-12 07:26 UTC, INextYP commented
@LatyshevDD Привет! Касательно логики  работы - всё отлично!

@marussia1996 желательно, если есть косяки, которые не относятся к задаче (в рамках этой задаче нужно было убрать кнопку у админа и всё) заводить в беклог задачку с указанием проблемы. Давайте идти модульными шагами.

На текущий момент проблема с позиционированием сохраняется, так абсолютные величины жестко завязаны в коде.
@LatyshevDD если есть желание, то давай я создам тебе отдельную задачку (а этот пулл-реквест вмержим) в которой опишу, как лучше сделать позиционирование меню? :)

2024-06-12 07:39 UTC, marussia1996 approved these changes

2024-06-12 08:52 UTC, LatyshevDD commented
Да мне все равно что делать) Готов добить позиционирование в рамках отдельной задачи.

2024-06-12 09:50 UTC, INextYP approved these changes

2024-06-12 09:51 UTC, INextYP commented
@LatyshevDD Можешь мержить) 

По следующей задаче, возьми задачу с бекенда, а то несбалансирован ход разработки проекта)

2024-06-12 11:17 UTC, merged