Правка верстки чатов + Добавлена вкладка "В работе"
ya-pomogau/frontend pull request #205
Opened 2024-06-11 16:49 UTC by ArtPsycho

2024-06-12 08:28 UTC, INextYP requested changes
Привет!
1. Не в уровень верстка
![image](https://github.com/ya-pomogau/frontend/assets/70805943/2afeacb5-f767-413b-93a9-4a04861b67c0)
2. На странице "Ждут ответа" сейчас отображается "У Вас пока нет конфликтов"
3. На странице "В работе" сейчас отображается "У Вас пока нет конфликтов в работе"

Два раздела выше - это не конфликтные чаты, а просто общение админа/ов c пользователями

4. При переходе на вкладки "В работе" и "Конфликтное закрытие" подчеркивание у ссылки "Чат" в меню удаляется.

5. Хотелось бы увидеть всё-таки для начала моковый вариант чатов на каждой вкладке

2024-06-12 08:28 UTC, INextYP commented on src/pages/section-chats-conflict/index.tsx
> +          />
Практически 3 одинаковых действия:

```jsx
{dataMessage?.length === 0 && location.pathname === '/chat-hub' && (
          <Informer
            text="У Вас пока нет конфликтов в работе"
            extClassName={styles.informer}
          />
        )}

{dataMessage?.length === 0 && location.pathname === '/chat' && (
          <Informer
            text="У Вас пока нет конфликтов"
            extClassName={styles.informer}
          />
        )}

{dataMessage?.length === 0 && location.pathname ==='/chat-progress' && (
          <Informer
            text="У Вас пока нет конфликтов в работе"
            extClassName={styles.informer}
          />
)}
```

Предлагаю тут подумать, как можно объединить эту логику в одну функцию (подсказка: воспользуйся switch case) ^)

2024-06-12 08:28 UTC, INextYP commented on src/shared/ui/tooltip/styles.module.css
Тут момент вот в чём - когда меняется ui-компонент, то желательно проверить, не сломалось ли отображение в других местах. 
Чтобы не рисковать, лучше передавать доп.классы через `extClassName` пропс :)

2024-06-12 13:37 UTC, ArtPsycho commented
Внес правки)

2024-06-19 08:50 UTC, ArtPsycho commented
Переделал отрисовку tooltip

2024-07-04 14:46 UTC, INextYP submitted a review, later dismissed

2024-07-04 14:48 UTC, INextYP approved these changes

2024-07-04 14:48 UTC, merged