Fix/contacts
ya-pomogau/frontend pull request #206
Opened 2024-06-12 11:25 UTC by IvannaBalanyuk

- Реализовала получение данных о контактах с бэка.

- Редактирование доступно только для root-администратора (обеспечено сокрытием блоков от остальных пользователей + дублирующая проверка на этапе сабмита).

- Не нашла ручку для редактирования контактов (есть метод сервиса, но нет соответствующего метода в контроллере, скрины ниже), поэтому реализовала на фронте пока в черновом варианте.

В `ContactsService` есть метод для редактирования:

![image](https://github.com/ya-pomogau/frontend/assets/124444858/03a6056f-7b66-4f44-b0d6-23148d62d23f)

В контроллере только GET-метод для роута /contacts:

![image](https://github.com/ya-pomogau/frontend/assets/124444858/58ea7584-1907-4de1-aa02-5322cfb2d1e7)

- Вёрстку поправила, адаптивность обеспечила.

2024-06-12 12:04 UTC, kspshnik commented
> В контроллере только GET-метод для роута /contacts:
Создал задачу [#99](https://github.com/ya-pomogau/backend/issues/99) в репозитории бэкенда.

2024-06-12 15:23 UTC, INextYP requested changes
Привет! Хорошая работа!

По верстке есть ещё косяк на этой странице
![image](https://github.com/ya-pomogau/frontend/assets/70805943/825284cd-62b2-4cd3-be4c-a77a7f470ed2)

2024-06-12 15:23 UTC, INextYP commented on src/pages/contacts/contacts.tsx
> +                Изменить данные
Обрати внимание, в дизайне указаны надписи - Изменить эл.почту и Изменить соцсети

2024-06-12 15:23 UTC, INextYP commented on src/pages/contacts/contacts.tsx
> +          {isEditAllowed && (
Обрати внимание, что у тебя дублируется (за исключением пары вещей) этот блок:
```jsx
{isEditAllowed && (
  <div
    onClick={emailHandler}
    className={
      editingInput === 'email'
        ? styles.edit_box_hidden
        : styles.edit_box
    }
  >
    <Icon color="blue" icon="EditIcon" />
    <p
      className={classNames(
        'text',
        'text_size_small',
        'text_type_regular',
        'm-0'
      )}
    >
      Изменить данные
    </p>
  </div>
)}
```

Давай создадим функцию, которая будет принимать тип изменяемого инпута и возвращать готовый блок

2024-06-12 15:23 UTC, INextYP commented on src/pages/contacts/contacts.tsx
> +  const [contactsData, setContactsData] = useState<TContacts>({
По-хорошему, тут должен быть хук useForm

2024-06-12 15:23 UTC, INextYP commented on src/pages/contacts/contacts.tsx
>    const onChange = (e: ChangeEvent<HTMLInputElement>) => {
Этот метод можно удалить, т.к. вместо него идет метод `handleChange` из хука `useForm`

2024-06-12 15:23 UTC, INextYP commented on src/pages/contacts/contacts.tsx
> +  const { email, socialNetwork } = useAppSelector((state) => state.contacts);
Вообще не вижу смысла в этом. У нас контакты на одной странице, они никак не передаются на другие страницы. Я бы убрал слайс для контактов

2024-06-12 15:23 UTC, INextYP commented on src/pages/contacts/contacts.tsx
> +  const getContactsResult = useGetContactsQuery();
если применить деструктуризацию, то в `data` будут лежать данные с сервера по этой странице

2024-06-12 15:23 UTC, INextYP commented on src/pages/contacts/contacts.tsx
> +  useEffect(() => {
Тоже можно убрать. У RTK Query есть прекрасная штука - инвалидация тегов. Т.е, при изменении данных будет выполнен запрос за новыми данными

2024-06-12 15:23 UTC, INextYP commented on src/pages/contacts/contacts.tsx
> +    if (isEditAllowed) {
если доступа нет, то пользователь и кнопок не увидит. Это явно можно убрать

2024-06-12 15:23 UTC, INextYP commented on src/pages/contacts/contacts.tsx
> +        const resultAction = await updateContacts(contactsData);
достаточно будет await updateContacts(<тут будет values из useForm хука>);

2024-06-12 16:20 UTC, IvannaBalanyuk commented on src/pages/contacts/contacts.tsx
> +                Изменить данные
Привет!
Да, я обратила внимание, но посчитала, что это намеренно изменили в верстке, т.к. в макете много опечаток и нестыковок в части текста. Впредь буду уточнять на ходу)

В части скрина выше - там идет нестыковка из-за компонента SmartHeader. Он должен иметь меньшую высоту. В рамках этой задачи же не стоит трогать "посторонние" компоненты? Если будет создана соответствующая задача, то с удовольствием возьмусь)

2024-06-12 19:17 UTC, IvannaBalanyuk commented on src/pages/contacts/contacts.tsx
> +                Изменить данные
- [x] вёрстку поправила

2024-06-12 19:19 UTC, IvannaBalanyuk commented on src/pages/contacts/contacts.tsx
> +          {isEditAllowed && (
- [x] вынесла повторяющийся фрагмент в функцию `getContactContainer`

2024-06-12 19:22 UTC, IvannaBalanyuk commented on src/pages/contacts/contacts.tsx
> +  const [contactsData, setContactsData] = useState<TContacts>({
- [x] переписала код с использованием хука `useForm`

Не смогла решить такую проблему - при обновлении страницы инпуты опустошаются и значения снова отображаются только после ререндера (например, после нажатия на кнопку редактирования или перехода между вкладками)

2024-06-12 19:25 UTC, IvannaBalanyuk commented on src/pages/contacts/contacts.tsx
>    const onChange = (e: ChangeEvent<HTMLInputElement>) => {
- [x] удалила метод `handleChange`

2024-06-12 19:26 UTC, IvannaBalanyuk commented on src/pages/contacts/contacts.tsx
> +  const { email, socialNetwork } = useAppSelector((state) => state.contacts);
- [x] слайс и всё сопутствующее удалила

2024-06-12 19:27 UTC, IvannaBalanyuk commented on src/pages/contacts/contacts.tsx
> +  const getContactsResult = useGetContactsQuery();
- [x] применила, спасибо)

2024-06-12 19:29 UTC, IvannaBalanyuk commented on src/pages/contacts/contacts.tsx
> +  useEffect(() => {
- [x] useEffect убрала, прекрасная штука прекрасно работает)

2024-06-12 19:32 UTC, IvannaBalanyuk commented on src/pages/contacts/contacts.tsx
> +    if (isEditAllowed) {
- [x] бессмысленную "перестраховку" убрала

2024-06-12 19:33 UTC, IvannaBalanyuk commented on src/pages/contacts/contacts.tsx
> +        const resultAction = await updateContacts(contactsData);
- [x] поправила строку + убрала условную конструкцию if... else... ниже

2024-06-13 16:37 UTC, INextYP commented on src/pages/contacts/contacts.tsx
> +                Изменить данные
По SmartHeader создам сейчас задачку)

2024-06-13 16:38 UTC, INextYP commented on src/pages/contacts/contacts.tsx
> +  const [contactsData, setContactsData] = useState<TContacts>({
> * [x]  переписала код с использованием хука `useForm`
> 
> Не смогла решить такую проблему - при обновлении страницы инпуты опустошаются и значения снова отображаются только после ререндера (например, после нажатия на кнопку редактирования или перехода между вкладками)

Проблема актуальна?

2024-06-13 17:06 UTC, IvannaBalanyuk commented on src/pages/contacts/contacts.tsx
> +  const [contactsData, setContactsData] = useState<TContacts>({
Да, корректно в этом плане работало только когда обращение за данными на бэк и setContsctsData были обернуты в UseEffect (по отдельности). Тогда при обновлении происходил запрос к бэку и после этого отрабатывал второй useEffect (с setContsctsData), так как у него в зависимостях были данные, получаемые с бэка.

2024-06-13 18:44 UTC, INextYP commented on src/pages/contacts/contacts.tsx
> +  const [contactsData, setContactsData] = useState<TContacts>({
Да, так  в принципе можно сделать, только вынести за пределы компонента:
```jsx
const initialContactsValues = {
    email: null,
    socialNetwork: null,
  }

export function ContactsPage() {
...
,...
....
const { values, handleChange, isValid, setValues } = useForm<TContacts>(initialContactsValues);
```

Чуть позже мы перейдем на нормальный хук)

Как исправишь - пингани, я исправлю

2024-06-13 18:51 UTC, kspshnik commented on src/pages/contacts/contacts.tsx
> +  const [contactsData, setContactsData] = useState<TContacts>({
> Да, корректно в этом плане работало только когда обращение за данными на бэк и setContsctsData были обернуты в UseEffect (по отдельности). Тогда при обновлении происходил запрос к бэку и после этого отрабатывал второй useEffect (с setContsctsData), так как у него в зависимостях были данные, получаемые с бэка.

@INextYP слушай, а может просто завести слайс `system` в хранилище, и туда прям на монтировании `App` затягивать конфиденциальность, контакты и всё прочее такое?

А потом по WS сделаем апдейты при изменении.

2024-06-13 21:09 UTC, IvannaBalanyuk commented
> вынести за пределы компонента

@INextYP , готово)
- [x] вынесла начальное значение за пределы компонента
- [x] добавила возврат setValue из useForm
- [x] поместила в useEffect присвоение values значений, полученных с бэка

2024-06-14 05:04 UTC, INextYP approved these changes
Отлично;)

2024-06-14 18:49 UTC, merged