[Fix] Added a check if recipient isUnConfirmed in requesting complete…
ya-pomogau/frontend pull request #265
Opened 2024-07-26 10:28 UTC by KuzmichevaES

При работе с неподтвержденным реципиентом добавлено исключение запросов на сервер за завершенными заявками.

2024-07-26 18:19 UTC, INextYP reviewed
Было бы здорово, если бы и вот эти запросы не уходили, если реципиент неподтвержден...

![image](https://github.com/user-attachments/assets/6c58e1ac-b718-498a-beed-5bb508311db1)

2024-07-26 19:11 UTC, KuzmichevaES commented
Добавила skip, чтобы не уходил запрос.

2024-07-28 16:59 UTC, INextYP requested changes
Запрос всё также уходит :)

Обрати внимание, как работает `skip`.
Он пропустит запрос, если условие равно `true`.

Если детально посмотреть процесс записи в `isUnConfirmedSelector` селектор данных, то можно увидеть, что в селектор сначала запишется `false` (из-за этого и полетит запрос), а только потом `true`

Условие нужно дополнить. Добавить (как вариант) проверку, что пока у нас нет пользователя И статус неподтвержден - запрос делать мы не будем

2024-07-29 20:03 UTC, KuzmichevaES commented
Добавила проверку User, но т.к. запросы не уходили, выполнялось условие !data и рендерился loader. Не знаю, насколько это корректное решение, но убрала проверку data, создала новую переменную, в которой или data или пустой массив, чтобы карта отрисовывалась даже если не ушел запрос и пока не пришла data.

2024-07-30 19:11 UTC, INextYP approved these changes
Отлично. Задача выполнена!

2024-07-30 19:11 UTC, merged