Fix/page container
ya-pomogau/frontend pull request #266
Opened 2024-07-28 14:33 UTC by Elena-Orekhova

2024-07-28 16:32 UTC, INextYP requested changes
Привет! Обрати внимание, что некоторые страницы сломались(

Страница: контакты.
![image](https://github.com/user-attachments/assets/4644af9e-7d5c-4509-a0d2-d94beebe42bb)

Страница: блог.
![image](https://github.com/user-attachments/assets/6bfd718f-b812-4be5-9e53-d6c1d58ed735)

Футер должен быть всегда прижатым к нижней части экрана, а он у нас теперь начал прыгать :(

2024-07-28 16:32 UTC, INextYP commented on src/pages/layout/index.tsx
> +      <div className={styles.wrapper}>
Давай всё-таки сделаем это в формате UI компонента для более явного разграничения на компоненты

2024-07-28 16:32 UTC, INextYP commented on src/pages/layout/styles.module.css
> +
Старайся не оставлять комментарии в коде, это ни к чему

2024-07-29 19:29 UTC, Elena-Orekhova commented
https://github.com/ya-pomogau/frontend/pull/266

2024-07-30 11:18 UTC, INextYP requested changes
Обрати внимание на мобильное разрешение у реципиента

![image](https://github.com/user-attachments/assets/b6f587e2-0bfe-4d46-9316-7193a633f4eb)

Пожалуйста, постарайся проверить все страницы по всем ролям. Это очень важно

2024-07-30 11:28 UTC, INextYP requested changes

2024-07-30 11:28 UTC, INextYP commented on src/widgets/header/styles.module.css
> +    height: 60px;
У тебя выше уже есть свойство `height`. Оставь что-то одно)

2024-07-30 11:28 UTC, INextYP commented on src/widgets/header/styles.module.css
> +  margin: 5px;
Для чего это?

2024-07-30 11:28 UTC, INextYP commented on src/shared/ui/main-wrapper/index.tsx
> +  return <div className={`${styles.wrapper} ${extClassName}`}>{children}</div>;
Вот тут воспользуйся пожалуйста функцией из библиотеки classnames чтобы не было такого:
![image](https://github.com/user-attachments/assets/4a4f0c40-8ade-406a-ae0b-f338566b81e0)

2024-07-30 11:28 UTC, INextYP commented on src/pages/layout/styles.module.css
> +    bottom: -22px;
Оверлей покрывает не всю ширину контентной области
![image](https://github.com/user-attachments/assets/d40c9ebc-b172-4a62-b8f9-28669eb7209c)

2024-08-05 09:18 UTC, Elena-Orekhova commented
https://github.com/ya-pomogau/frontend/pull/266

2024-08-05 10:00 UTC, INextYP approved these changes
Задача выполнена. Умничка!

2024-08-05 10:00 UTC, merged