Fix/use permission tests
ya-pomogau/frontend pull request #268
Opened 2024-07-28 19:11 UTC by AlexeyKrutyakov

2024-07-30 18:37 UTC, AlexeyKrutyakov commented
добавил тесты, исправил ошибки

2024-07-30 19:15 UTC, INextYP requested changes

2024-07-30 19:15 UTC, INextYP commented on tsconfig.app.json
> +  "include": ["src", "vitest.config.ts"]
У тебя в природе нет этого файла. Можно удалить отсюда это

2024-07-30 19:32 UTC, AlexeyKrutyakov commented on tsconfig.app.json
> +  "include": ["src", "vitest.config.ts"]
спасибо, что нашёл. я поправил

2024-07-31 07:07 UTC, INextYP approved these changes

2024-07-31 07:07 UTC, merged