Feat/socket middleware
ya-pomogau/frontend pull request #269
Opened 2024-07-29 06:16 UTC by gvozdenkov

2024-07-29 06:44 UTC, kspshnik requested changes
Почти всё готово :)
Чуть-чуть архитектуру в нужную сторону повернуть - и порядок!

2024-07-29 06:44 UTC, kspshnik commented on src/app/store/index.ts
> +    [socketSlice.name]: socketSlice.reducer,
Эта middleware должна работать с `systemSlice`

2024-07-29 06:44 UTC, kspshnik commented on src/entities/chat/model/socket.ts
> +const initialState: SocketState = {
Перенеси в `systemSlice`, пожалуйста;

2024-07-29 06:44 UTC, kspshnik commented on src/services/websocket-middleware.ts
А как мы получение обрабатываем? Неплохо бы и `.on('message')` сделать :)

2024-07-29 07:09 UTC, INextYP requested changes

2024-07-29 07:09 UTC, INextYP commented on src/services/websocket-middleware.ts
> +    const socketUrl = import.meta.env.VITE_APP_API_HOST;
Лучше вынести в конфиг файл (config/api-config) и тянуть оттуда для более удобного управления :)

2024-07-30 18:34 UTC, gvozdenkov commented on src/app/store/index.ts
> +    [socketSlice.name]: socketSlice.reducer,
@kspshnik Не совсем понял, что значит должна работать с `systemSlice`

2024-07-30 18:35 UTC, gvozdenkov commented on src/entities/chat/model/socket.ts
> +const initialState: SocketState = {
@kspshnik В смысле создание слайса перенести тотже файл, где `systemSlice` создаётся? Или надо эти 2 слайса объединить?

2024-07-30 18:51 UTC, kspshnik commented on src/entities/chat/model/socket.ts
> +const initialState: SocketState = {
`src/services/system-slice.ts`:

```ts
import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { authApi } from './auth';
import {
  ErrorDto,
  TAdminLoginDto,
  TNewUserRequestDto,
  TVKLoginRequestDto,
} from './auth.types';
import {
  TCustomSelector,
  TSystemSliceState,
} from '../shared/types/store.types';
import { RootState } from '../app/store';
import { TUser, TVKUser } from '../entities/user/types';
import { AdminPermission } from '../shared/types/common.types';
import { setTokenAccess } from 'shared/libs/utils';

export const isPendingSelector: TCustomSelector<boolean> = (state: RootState) =>
  state.system.isPending;

export const isNewSelector: TCustomSelector<boolean> = (state: RootState) =>
  state.system.isNew;

export const userSelector: TCustomSelector<TUser | null> = (state) =>
  state.system.user;

export const vkUserSelector: TCustomSelector<TVKUser | null> = (state) =>
  state.system.vkUser;

export const hasPrivilegesSelector: TCustomSelector<boolean> = (state) =>
  !!state.system.user &&
  !!state.system.user.permissions &&
  state.system.user.permissions.length > 0;

export const isRootSelector: TCustomSelector<boolean> = (state) =>
  !!state.system.user && (state.system.user.isRoot ?? false);

export const permissionsSelector: TCustomSelector<
  Array<AdminPermission> | null
> = (state) =>
  !!state.system.user &&
  !!state.system.user.permissions &&
  state.system.user.permissions.length > 0
    ? state.system.user.permissions
    : null;

export const userLoginThunk = createAsyncThunk(
  'user/login',
  async (userLoginDto: TVKLoginRequestDto, { rejectWithValue }) => {
    try {
      const tmpRes = await authApi.vkLogin(userLoginDto);
      const { token, user, vkUser: vkUserResponse } = tmpRes;
      const vkUser = vkUserResponse ? vkUserResponse : null;

      if (token && !!user) {
        setTokenAccess(token);
      }
      return { user, vkUser };
    } catch (error) {
      const { message } = error as ErrorDto;
      console.log(`Error message: ${message}`);
      rejectWithValue(message as string);
    }
  }
);

export const adminLoginThunk = createAsyncThunk(
  'admin/login',
  async (adminLoginDto: TAdminLoginDto, { rejectWithValue }) => {
    try {
      const { token, user } = await authApi.adminLogin(adminLoginDto);
      if (!token || !user) {
        throw new Error('Ошибка регистрации администратора');
      }
      if (token && !!user) {
        setTokenAccess(token);
      }
      return { user };
    } catch (error) {
      const { message } = error as ErrorDto;
      return rejectWithValue(message as string);
    }
  }
);

export const newUserThunk = createAsyncThunk(
  'user/new',
  async (newUserDto: TNewUserRequestDto, { rejectWithValue }) => {
    try {
      const { token, user } = await authApi.createNewUser(newUserDto);
      if (!token || !user) {
        throw new Error('Ошибка регистрации пользователя');
      }
      if (token && !!user) {
        setTokenAccess(token);
      }
      return { user };
    } catch (error) {
      const { message } = error as ErrorDto;
      rejectWithValue(message as string);
    }
  }
);

export const checkTokenThunk = createAsyncThunk(
  'user/token',
  async (token: string, { rejectWithValue }) => {
    try {
      const user = await authApi.checkToken(token);
      console.dir(user);
      if (!user) {
        throw new Error('Ошибка получения пользователя по токену');
      }
      return { user };
    } catch (error) {
      const { message } = error as ErrorDto;
      rejectWithValue(message as string);
    }
  }
);
const systemSliceInitialState: TSystemSliceState = {
  user: null,
  vkUser: null,
  isPending: false,
  isNew: false,
};

const systemSlice = createSlice({
  name: 'system',
  initialState: systemSliceInitialState,
  reducers: {
    resetUser: () => systemSliceInitialState,
  },
  extraReducers: (builder) =>
    builder
      .addCase(userLoginThunk.pending, (state, _) => ({
        ...state,
        error: null,
        isPending: true,
      }))
      .addCase(userLoginThunk.fulfilled, (state, action) => {
        if (!action.payload) {
          return state;
        }
        // eslint-disable-next-line @typescript-eslint/naming-convention
        const { user = null, vkUser = null } = action.payload;
        return {
          ...state,
          user,
          vkUser: vkUser,
          isPending: false,
          isNew: !user && !!vkUser,
        };
      })
      .addCase(userLoginThunk.rejected, (state) => ({
        ...state,
        isPending: false,
      }))
      .addCase(newUserThunk.pending, (state, _) => ({
        ...state,
        error: null,
        isPending: true,
      }))
      .addCase(newUserThunk.fulfilled, (state, action) => {
        if (!action.payload) {
          return state;
        }
        // eslint-disable-next-line @typescript-eslint/naming-convention
        const { user = null } = action.payload;
        return {
          ...state,
          user,
          vk_user: null,
          isPending: false,
          isNew: false,
        };
      })
      .addCase(newUserThunk.rejected, (state) => ({
        ...state,
        isPending: false,
        isNew: false,
      }))
      .addCase(checkTokenThunk.pending, (state) => ({
        ...state,
        error: null,
        isPending: true,
      }))
      .addCase(checkTokenThunk.fulfilled, (state, action) => {
        if (!action.payload) {
          return state;
        }
        // eslint-disable-next-line @typescript-eslint/naming-convention
        const { user = null } = action.payload;
        return {
          ...state,
          user,
          isPending: false,
        };
      })
      .addCase(checkTokenThunk.rejected, (state) => ({
        ...state,
        isPending: false,
      }))
      .addCase(adminLoginThunk.pending, (state) => ({
        ...state,
        error: null,
        isPending: true,
      }))
      .addCase(adminLoginThunk.fulfilled, (state, action) => {
        if (!action.payload) {
          return state;
        }
        // eslint-disable-next-line @typescript-eslint/naming-convention
        const { user = null } = action.payload;
        return {
          ...state,
          user,
          isPending: false,
        };
      })
      .addCase(adminLoginThunk.rejected, (state) => ({
        ...state,
        isPending: false,
      })),
});

export const { resetUser } = systemSlice.actions;
export default systemSlice.reducer;

export const actions = {
  ...systemSlice.actions,
  adminLoginThunk,
};
```

2024-07-30 18:52 UTC, kspshnik commented on src/entities/chat/model/socket.ts
> +const initialState: SocketState = {
> @kspshnik В смысле создание слайса перенести тотже файл, где `systemSlice` создаётся? Или надо эти 2 слайса объединить?


Не должно быть отдельного слайса :) Миддлвара будет работать **только** с системными сообщениями типа замены токена после изменения статусов у юзверя и т.п.

2024-08-05 13:43 UTC, IvannaBalanyuk commented on src/services/websocket-middleware.ts
> +    const socketUrl = import.meta.env.VITE_APP_API_HOST;
Вынесла, но не уверена, что корректно

2024-08-05 14:34 UTC, IvannaBalanyuk commented on src/services/websocket-middleware.ts
Сделала:
- для msg 'connect_user', которое сервер отправляет клиенту после подключения;
- для гипотетического msg 'message' (сервер у нас пока ничего такого не шлёт).

2024-08-05 14:35 UTC, IvannaBalanyuk commented on src/entities/chat/model/socket.ts
> +const initialState: SocketState = {
Влила SocketSlice в SystemSlice.

2024-08-05 14:35 UTC, IvannaBalanyuk commented on src/app/store/index.ts
> +    [socketSlice.name]: socketSlice.reducer,
Влила SocketSlice в SystemSlice.

2024-08-05 14:50 UTC, IvannaBalanyuk commented
@INextYP @kspshnik
- прошлась по замечаниям, вроде бы всё поправила;
- добавила старт ws-подключения для реципиента (в `ProfileActivePage`);
- добавила инициацию закрытия ws-подключения в случае выхода юзера (в `DropDownMenu`).

2024-08-08 11:24 UTC, kspshnik approved these changes, later dismissed
Отлично, начало положено!!

2024-08-08 16:46 UTC, INextYP approved these changes
Всё отлично! :)

2024-08-08 16:47 UTC, merged