refactor(edit-profile-popup): new markup and styles
ya-pomogau/frontend pull request #277
Opened 2024-07-30 16:09 UTC by gvozdenkov

Change html & css. Add image upload preview

TODO: add avatar image input to ReactHookForm controls

[Figma design](https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=16043-14219&t=0RqrcQCUQWNjcPoW-0)

Issue: https://github.com/ya-pomogau/frontend/issues/272

2024-07-30 20:04 UTC, INextYP requested changes
Поступили доп. корректировки по дизайну - https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=16153-15150&t=VL3XB5ZZPoG6IQCf-4

2024-07-31 07:58 UTC, gvozdenkov commented
> Поступили доп. корректировки по дизайну - https://www.figma.com/design/xYLbl9kLmcAwYCbAhCFMCy/%D0%AF%D0%9F%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%8E-(Web)?node-id=16153-15150&t=VL3XB5ZZPoG6IQCf-4

Готово

![image](https://github.com/user-attachments/assets/555cdb39-8428-4ce2-84d4-0d45861d84aa)

2024-07-31 09:24 UTC, INextYP requested changes
Есть некоторые проблемы:
- [x] Перестало заполняться имя пользователя
![image](https://github.com/user-attachments/assets/d795de1c-a4af-4396-ae88-f5612f67f50a)
- [ ] Есть нестыковки по вёрстке
![image](https://github.com/user-attachments/assets/338ccbe1-b4d3-406c-86cc-146aef3b1514)

2024-07-31 10:51 UTC, gvozdenkov commented
> Есть некоторые проблемы:
> 
> * [x]  Перестало заполняться имя пользователя
>   ![image](https://private-user-images.githubusercontent.com/70805943/353774277-d795de1c-a4af-4396-ae88-f5612f67f50a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjI3ODUsIm5iZiI6MTcyMjQyMjQ4NSwicGF0aCI6Ii83MDgwNTk0My8zNTM3NzQyNzctZDc5NWRlMWMtYTRhZi00Mzk2LWFlODgtZjU2MTJmNjdmNTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEwNDEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MzdiMjZkN2Q4OTUxMTAxNzFkMmIyYThlZDg3OTM0Mjc5MDk5MWQ4N2NlZjBlODAyYzk2NGJjYzUyYzQwNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ib6ejreXmTFi5gZPfye0HJpeaMfCs9YvqRaYIomERTo)
> * [ ]  Есть нестыковки по вёрстке
>   ![image](https://private-user-images.githubusercontent.com/70805943/353775338-338ccbe1-b4d3-406c-86cc-146aef3b1514.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjI3ODUsIm5iZiI6MTcyMjQyMjQ4NSwicGF0aCI6Ii83MDgwNTk0My8zNTM3NzUzMzgtMzM4Y2NiZTEtYjRkMy00MDZjLTg2Y2MtMTQ2YWVmM2IxNTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEwNDEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZDM4ZTVjNjJkYTJkNjM3ZTI5OWQ1ZjM0NDQ4NzYzZDljOWY3ODU1ZDIwODY3OTE1OTVmNDYzMjlkZTUxODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.49Zrcz8QpdEZLEkFr6gabNClRJAKcfrlcVe_5y5AF4w)

Чуть вёрстку подправил, но у нас интересные дизайнеры %) Один этот попап довольно рандомно свёрстан. Разная высота инпутов, нечётный отступ кружка аватара, хотя сетка чётная. `line-height` у типа плейсхолдеров случайный 19.4, отличается от стандартного 22.4px в `.text_size_medium`. Случайный красный цвет, которого нет в палитре и которым они предлагают сделать ошибочный текст в инпуте. Ширина кнопки 105 и её невозможно отцентровать по центру при 260 ширине. В общем я чуть причесал, но радикально непонятно под что ровняться, всё разъезжается в макете.

![image](https://github.com/user-attachments/assets/64a885b4-2365-4dcc-9030-adbc6131d8f2)

2024-07-31 10:56 UTC, INextYP commented
Дизайнер-новичек %) Скорее всего бесплатный...А каком качестве тут речь :)

2024-07-31 11:06 UTC, INextYP approved these changes
Не буду больше мучать) Всё хорошо!

2024-07-31 11:06 UTC, merged

2024-07-31 11:46 UTC, gvozdenkov commented
> Дизайнер-новичек %) Скорее всего бесплатный...А каком качестве тут речь :)

Да я не против. Я ж моушен дизайнер в прошлом. Для меня правки по визуалу очень обычное явление %)