Feat/add shared UI imports
ya-pomogau/frontend pull request #294
Opened 2024-08-03 16:26 UTC by Yurii-M76

2024-08-03 17:36 UTC, INextYP requested changes

2024-08-03 17:36 UTC, INextYP commented on .env.dev.example
Не трогаем .env.* файлы. Верни обратно предыдущий файл

2024-08-03 17:36 UTC, INextYP commented on src/shared/ui/index.ts
Тут ок, но было бы хорошо, если бы ты разделил дефолтные импорты и обычные, чтобы было проще их разобрать позже

```
// Просто импорты

... разделитеть

// Импорты с использованием default as
```

2024-08-03 17:50 UTC, Yurii-M76 commented on src/shared/ui/index.ts
Поправил

2024-08-04 14:54 UTC, INextYP approved these changes
То, что нужно! Отлично.

2024-08-04 14:54 UTC, merged