на ревью
ya-pomogau/frontend pull request #317
Opened 2024-08-05 15:20 UTC by DavidKhlutkov

учтены все задачи а так же переработан admin-actions дабы не превращать его в god component

2024-08-07 18:16 UTC, INextYP requested changes
Привет. В твой ветке карточки сломаны

![image](https://github.com/user-attachments/assets/39af799b-52b4-4779-9acd-362666971794)


В `develop` всё ок.

![image](https://github.com/user-attachments/assets/cf993547-3ba0-41a9-a879-1e4485c29cd7)


Обязательно проверяй другие разделы если правишь что-то.

Дальнейшую проверку PR буду проводить после исправления косяков выше.

2024-08-07 18:16 UTC, INextYP commented on src/shared/ui/user-cards/styles.module.css
> +/* .buttons_div > :first-child {
Комментарий удалить!

2024-08-07 20:49 UTC, DavidKhlutkov commented on src/shared/ui/user-cards/styles.module.css
> +/* .buttons_div > :first-child {
очень классно получается, стили которые начинаются на админ, влияют на стили карточек волонтеров, почему бы не обозвать его врапер контент , просто так даже интуитивно не поймешь

2024-08-10 16:02 UTC, INextYP commented
На текущий момент верстка сломана.

![image](https://github.com/user-attachments/assets/c96c752f-f4fa-4be8-b4ea-23acf577564d)

![image](https://github.com/user-attachments/assets/75d754e7-008f-4f49-b30b-3ffbe1590449)

2024-08-14 16:15 UTC, INextYP approved these changes
Все ошибки будут исправляться в рамках отдельного PR

2024-08-14 16:15 UTC, merged