Fix/map
ya-pomogau/frontend pull request #321
Opened 2024-08-06 13:17 UTC by TankaShwed

[ссылка на задачу](https://github.com/orgs/ya-pomogau/projects/1/views/1?pane=issue&itemId=73054327)

https://github.com/orgs/ya-pomogau/projects/1/views/1?pane=issue&itemId=73054327

2024-08-07 08:48 UTC, gvozdenkov commented on src/widgets/map/styles.css
> +  /* margin: 10px 0 0 0; */
Комменты лучше удалять. Этот код есть в предыдущих коммитах. А так эти мёртвые скуски закомментированного кода будут оставаться висеть %)

2024-08-07 08:48 UTC, gvozdenkov commented on src/widgets/map/styles.css
> +  line-height: 16.8px; /* ! */
Странный коммент %)

2024-08-07 08:48 UTC, gvozdenkov commented on src/widgets/map/styles.css
> +  /* margin: 3px; */
Тоже лучше удалить

2024-08-07 08:52 UTC, INextYP requested changes
- [x] `Если волонтер не подтвержден и кликает на "откликнуться" то не нужно отправлять запрос на /accept` - запрос всё также уходит. Если волонтер неподтвержден , то НЕ нужно отправлять запрос
![image](https://github.com/user-attachments/assets/55bd55eb-9811-436e-886e-15490d6721e2)
- [x] Есть ошибка в Mark компоненте
![image](https://github.com/user-attachments/assets/eccbc01e-8f22-4daa-ac6a-b18d1dbf1dfb)
- [x] Проверь настройки линтера

2024-08-07 08:52 UTC, INextYP commented on src/widgets/map/styles.css
> +  /* margin: 3px; */
Не оставляем комментарии в коде.

2024-08-07 08:52 UTC, INextYP commented on src/widgets/map/styles.css
> +  /* margin: 10px 0 0 0; */
Не оставляем комментарии в коде

2024-08-07 08:52 UTC, INextYP commented on src/widgets/map/Mark.tsx
> +          if ([...description].length < 125) {
1. Что такое 125?
2. У String есть также `length`, так что преобразование в массив ни к  чему

2024-08-14 14:52 UTC, INextYP approved these changes
💯

2024-08-14 14:52 UTC, merged