Fix/create edit task
ya-pomogau/frontend pull request #324
Opened 2024-08-06 17:35 UTC by Elena-Orekhova

2024-08-06 17:39 UTC, Elena-Orekhova commented
https://github.com/ya-pomogau/frontend/pull/324


По изменениям в UI-компонентах: TaskList 
Index.tsx
- добавила текст для админки на реципиента и волонтера и добавила условие, чтобы в админке не отображалось “хотите добавить заявку?” (ведь там есть “создать заявку”). Зашла в заявки от роли реципиента – там ничего не изменилось.
- добавила дополнительный класс для высоты контейнера заявок с роли админа. Также проверила через реципиента – там ничего не меняется.
styles.module.css 
- убрала height: 106px – чтобы кнопка отображалась не “срезанной”, 
- добавила border-top по макету

2024-08-08 09:34 UTC, INextYP requested changes

2024-08-08 09:34 UTC, INextYP commented on src/widgets/user-card/components/user-info.tsx
> +  userRole,
Зачем роль, если она не используется?

2024-08-08 09:34 UTC, INextYP commented on src/pages/layout/styles.module.css
Изменения в лейауте строго запрещены

2024-08-08 09:34 UTC, INextYP commented on src/app/routing/components/routes-group/index.tsx
> +  const [isFirstLoading, setIsFirstLoading] = useState(true);
Какая роль у этого стейта?

2024-08-08 09:34 UTC, INextYP commented on src/entities/task/ui/task-list/index.tsx
> +            role === UserRole.ADMIN ? styles.contentAdmin : styles.content,
Почитай, как с помощью classNames лучше сформировать стили. Тернарники - это некрасиво. Мы вычищаем код от них

2024-08-08 09:34 UTC, INextYP commented on src/widgets/user-card/components/user-info.tsx
>  import classes from '../styles.module.css';
Вот это прям очень странно. Понимаю, что не ты писала, но давай исправим

2024-08-08 09:34 UTC, INextYP commented on src/widgets/user-card/components/user-info.tsx
>    <div className={styles.user_info}>
Не знаю, кто додумался, но этот селектор не работает, т.к в стилях вот такое:
![image](https://github.com/user-attachments/assets/a43f4b84-a862-43f1-a4f1-50dab1bdbec0)

2024-08-08 09:34 UTC, INextYP commented on src/pages/tasks-profile/index.tsx
> +  incomeTab: string;
Остальные ключи точно нужны?

2024-08-08 09:34 UTC, INextYP commented on src/entities/task/ui/task-list/styles.module.css
> +.contentAdmin {
Дублируем кучу стилей. Не проще навешивать класс `.content`, а отдельный класс с отличающимися стилями навешивать по условию?)

2024-08-08 09:34 UTC, INextYP commented on src/entities/task/ui/task-list/index.tsx
> +              isMobile ? styles.content_empty_mobile : styles.content_empty,
Аналогичное замечание, что я писал про селектор `content`

2024-08-10 15:57 UTC, INextYP approved these changes
Остальные правки будут вноситься в рамках отдельных задач

2024-08-10 15:57 UTC, merged