added schema validation for Contacts
ya-pomogau/frontend pull request #326
Opened 2024-08-06 21:29 UTC by Jelena-Ershova

При добавлении схемы валидации, состояние формы isValid становиться false.

2024-08-07 07:10 UTC, INextYP requested changes

2024-08-07 07:10 UTC, INextYP commented on src/pages/contacts/components/contacts-form/index.tsx
> +  //console.log('isValid', isValid, 'isDirty', isDirty, 'errors', errors);
Консоли не оставляем

2024-08-07 07:10 UTC, INextYP commented on src/pages/contacts/index.tsx
>    const isEditAllowed = usePermission([UserStatus.VERIFIED], UserRole.ADMIN);
А нам ещё где-то на этой странице это надо? Если нет, то уносим в компонент формы

2024-08-07 07:10 UTC, INextYP commented on src/pages/contacts/components/contacts-form/index.tsx
> +import { Controller, SubmitHandler, useForm } from 'react-hook-form';
Сделай плз тут нормальный порядок импортов

2024-08-07 07:10 UTC, INextYP commented on src/pages/contacts/components/ContactInput/index.tsx
> +            !isEditable && !error
Считается плохим тоном в разметке вот такую колбасу из тернарников строить, давай вынесем это в константу:

```tsx
const errorTextStyles = classNames({
  [styles.edit_box_hidden]: !isEditable && !error,
  [styles.error_contacts]: isEditable || error
});
```

и просто заиспользуем

className={errorTextStyles}


2. Зачем нам 2 раза проверять `isEditAllowed` если можно поместить всё в одно месте?

2024-08-07 07:10 UTC, INextYP commented on src/pages/contacts/components/contacts-form/schema.ts
> +export const schema = Joi.object<TContacts>({
Текущая схема валидации не работает.

Добавь дженериком `ContactsForm` а также
```ts
editableInputs: Joi.any()
```

Обязательно проверь, что после изменения хотя бы одного инпута у тебя кнопка становится доступной для нажатия

2024-08-07 07:10 UTC, INextYP commented on src/pages/contacts/components/contacts-form/index.tsx
> +            errorText={errors.socialNetwork?.message}
Обрати внимание, что пропсы error и errorText - это по сути одно и тоже. Давай просто передадим что-то одно, например `errorText={errors.socialNetwork?.message}` а в компоненте просто будем выполнять булево преобразование

2024-08-07 07:10 UTC, INextYP commented on src/pages/contacts/components/ContactInput/styles.module.css
> +    font-weight: 400;
У нас есть переменные + готовые селекторы. Давай лучше воспользуемся ими

2024-08-07 20:57 UTC, Jelena-Ershova commented on src/pages/contacts/components/contacts-form/index.tsx
> +  //console.log('isValid', isValid, 'isDirty', isDirty, 'errors', errors);
Done

2024-08-07 20:57 UTC, Jelena-Ershova commented on src/pages/contacts/index.tsx
>    const isEditAllowed = usePermission([UserStatus.VERIFIED], UserRole.ADMIN);
Done

2024-08-07 20:57 UTC, Jelena-Ershova commented on src/pages/contacts/components/contacts-form/index.tsx
> +import { Controller, SubmitHandler, useForm } from 'react-hook-form';
Done

2024-08-07 20:58 UTC, Jelena-Ershova commented on src/pages/contacts/components/ContactInput/index.tsx
> +            !isEditable && !error
Done

2024-08-07 20:59 UTC, Jelena-Ershova commented on src/pages/contacts/components/contacts-form/schema.ts
> +export const schema = Joi.object<TContacts>({
Может лучше не any, а editableInputs: Joi.object()

2024-08-07 20:59 UTC, Jelena-Ershova commented on src/pages/contacts/components/contacts-form/index.tsx
> +            errorText={errors.socialNetwork?.message}
Done

2024-08-07 20:59 UTC, Jelena-Ershova commented on src/pages/contacts/components/ContactInput/styles.module.css
> +    font-weight: 400;
Удалила из css

2024-08-07 21:51 UTC, INextYP commented on src/pages/contacts/components/contacts-form/schema.ts
> +export const schema = Joi.object<TContacts>({
Мы добавляем .any чисто для галочки. Тут абсолютно не важен результат валидации)

2024-08-08 12:44 UTC, INextYP approved these changes

2024-08-08 12:44 UTC, merged