Рефакторинг navigation #339
ya-pomogau/frontend pull request #344
Opened 2024-08-10 16:07 UTC by iTrishka

#339

2024-08-10 16:11 UTC, INextYP requested changes

2024-08-10 16:11 UTC, INextYP commented on src/widgets/header/navigation/sidebar-item/styles.module.css
> +@import '../../../../app/assets/styles/common.css';
Удали этот импорт, забыл в задаче указать :) У нас все переменные итак в главный модуль стилей экспортируется

2024-08-10 16:11 UTC, INextYP commented on src/widgets/header/navigation/types.tsx
> +export interface NavLinkRenderProps {
Не не не, этот тип достается из библиотеки react-router-dom

2024-08-10 22:09 UTC, iTrishka commented on src/widgets/header/navigation/sidebar-item/styles.module.css
> +@import '../../../../app/assets/styles/common.css';
Готово!

2024-08-10 22:09 UTC, iTrishka commented on src/widgets/header/navigation/types.tsx
> +export interface NavLinkRenderProps {
Спасибо, поправила!

2024-08-11 15:15 UTC, INextYP approved these changes
Всё отлично :)

2024-08-11 15:15 UTC, merged