to review
ya-pomogau/frontend pull request #38
Opened 2023-06-01 20:08 UTC by niksmo

2023-06-05 17:34 UTC, gennady-bars reviewed
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)


К сожалению, работу придется отклонить без потери итерации


* В `Readme` должна быть ссылка на бриф. Эта ссылка должна быть доступной ревьюеру тоже
* При запуске проекта ничего не отображается https://disk.yandex.ru/i/eMvjNS-1JcQmOA 
* Как будто нет кода проекта в пулл-реквесте. Нужно перепроверить, что запушили изменения

2023-06-05 19:21 UTC, niksmo commented
> Привет! Мы всё верно запушили - страницы только-только начали собираться, до этого мы занимались компонентами.

2023-06-06 22:01 UTC, gennady-bars reviewed
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)

Посмотрите на **гитхабе** все комментарии к коду (нужно прокрутить вниз страницу там)

Работа проделана огромная:



* Отлично, что почти нет типов `any`
* Хорошо сделана часть для волонтера


но есть некоторые недочеты:



* При запуске проекта в консоли ошибка `key` https://disk.yandex.ru/i/rADNb0n6CNb0BA
* Тег `header` уже есть внутри `Header`, поэтому не нужно еще раз его указывать снаружи

2023-06-06 22:01 UTC, gennady-bars commented on src/pages/layout/index.tsx
> +      <header><Header/></header>
`      <header><Header/></header>
`


Тег `header` уже есть внутри `Header`, поэтому не нужно еще раз его указывать снаружи

2023-06-06 22:01 UTC, gennady-bars commented on src/entities/chat/ui/chat/index.tsx
> +  const handleInputChange = ({ target }: ChangeEvent<HTMLInputElement>) => {
const handleInputChange = ({ target }: ChangeEvent<HTMLInputElement>) => {

2023-06-07 07:34 UTC, niksmo commented on src/entities/chat/ui/chat/index.tsx
> +  const handleInputChange = ({ target }: ChangeEvent<HTMLInputElement>) => {
Так не сработает 
<img width="426" alt="image" src="https://github.com/YaPomogayu/frontend/assets/96130492/f2e7b930-3e5a-415a-a603-82d5c0778a45">
<img width="559" alt="image" src="https://github.com/YaPomogayu/frontend/assets/96130492/79f9e2ba-c43f-4873-98bd-39bf5b730128">

2023-06-08 09:39 UTC, gennady-bars commented on src/entities/chat/ui/chat/index.tsx
> +  const handleInputChange = ({ target }: ChangeEvent<HTMLInputElement>) => {
> Так не сработает

Коммент неправильно скопировался у меня. Не заметил, что он такой остался


Вот это хотел

**Можно лучше**

Можно сделать универсальный **кастомный** хук для контроля любого количества инпутов в любых формах:

```js
export function useForm(inputValues={}) {
  const [values, setValues] = useState(inputValues);

  const handleChange = (event) => {
    const {value, name} = event.target;
    setValues({...values, [name]: value});
  };
  return {values, handleChange, setValues};
}

```

Этот код помещают в отдельный файл `useForm.js` в папке `hooks` и импортируют функцию туда, где нужно контролировать инпуты

И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:

```jsx
  const {values, handleChange, setValues} = useForm({});

```

2023-06-08 10:26 UTC, gennady-bars approved these changes
Поздравляю! Ваша работа принята.

Вы отлично потрудились.


* Отлично сделан `Storybook`
* Хорошая верстка страниц (хоть немного неполная)

Удачного дальнейшего обучения.


но есть некоторые недочеты: 

* Скрин https://disk.yandex.ru/i/1DXmArCZq2NFkA Выпадающее меню сливается с контентом 
* При клике на логотип нужно было сделать переход на главную, где я можно было переключиться с волонтера на админа и тд (4 типа пользователей на сайте), а то в урле приходится менять данные вручную, чтобы проверить
* Надо было реализовать фильтр https://disk.yandex.ru/i/QWXQItgIp4pVgQ (хотя бы просто он должен появляться) 
* `MasterAdminPage` нужно было тоже сверстать
* В админе нужно было моковых карточек добавить в раздел **Подтверждение/Блокировка**, чтобы показать верстку
* `ProfileReducer` нужно было назвать как-то по-другому, так как `Reducer` обычно используется для редакса. 
* Вам нужно дополнить все страницы тем, что указано в макете . Моковые данные нужно поместить в блг, контакты и тд, чтобы видеть верстку этого контента
* Кастомные типы `typescript` принято называть в `PascalCase` (с **большой буквы**)
* `(state: RootState)` уже не нужно будет типизировать вручную стейт, когда замените везде хук `useSelector`. Нужно будет удалить дублирование типизации
* `CreateRequest` является компонентом реакта, а их называют в виде **существительных**, а не глаголов

2023-06-08 10:26 UTC, gennady-bars commented on src/pages/master-admin/index.tsx
> +  return <div>master admin page</div>;
`MasterAdminPage` нужно было тоже сверстать

2023-06-08 10:26 UTC, gennady-bars commented on src/entities/viewer/hoc/route-reducer/index.tsx
> +export function ProfileReducer() {
`ProfileReducer` нужно было назвать как-то по-другому, так как `Reducer` обычно используется для редакса.

2023-06-08 10:26 UTC, gennady-bars commented on src/shared/ui/avatar/index.tsx
> +interface imageProps extends ImgHTMLAttributes<HTMLImageElement> {
`imageProps`


Кастомные типы `typescript` принято называть в `PascalCase` (с **большой буквы**)

2023-06-08 10:26 UTC, gennady-bars commented on src/features/create-request/ui/steps/index.tsx
> +      <OverlayingPopup isOpened={isPopupOpen}>
Внутри `OverlayingPopup` уже есть `Portal, поэтому вокруг не нужно еще раз создавать портал

2023-06-08 10:26 UTC, gennady-bars commented on src/features/create-request/ui/steps/task-step/task-step.tsx
> +    (state: RootState) => state.createRequest
`(state: RootState)` уже не нужно будет типизировать вручную стейт, когда замените везде хук `useSelector`. Нужно будет удалить дублирование типизации

2023-06-08 10:26 UTC, gennady-bars commented on src/features/create-request/ui/steps/index.tsx
> +export const CreateRequest = ({
`CreateRequest` является компонентом реакта, а их называют в виде **существительных**, а не глаголов

2023-06-08 10:59 UTC, niksmo commented
> Поздравляю! Ваша работа принята.
> 
> Вы отлично потрудились.
> 
> * Отлично сделан `Storybook`
> * Хорошая верстка страниц (хоть немного неполная)
> 
> Удачного дальнейшего обучения.
> 
> но есть некоторые недочеты:
> 
> * Скрин https://disk.yandex.ru/i/1DXmArCZq2NFkA Выпадающее меню сливается с контентом
> * При клике на логотип нужно было сделать переход на главную, где я можно было переключиться с волонтера на админа и тд (4 типа пользователей на сайте), а то в урле приходится менять данные вручную, чтобы проверить
> * Надо было реализовать фильтр https://disk.yandex.ru/i/QWXQItgIp4pVgQ (хотя бы просто он должен появляться)
> * `MasterAdminPage` нужно было тоже сверстать
> * В админе нужно было моковых карточек добавить в раздел **Подтверждение/Блокировка**, чтобы показать верстку
> * `ProfileReducer` нужно было назвать как-то по-другому, так как `Reducer` обычно используется для редакса.
> * Вам нужно дополнить все страницы тем, что указано в макете . Моковые данные нужно поместить в блг, контакты и тд, чтобы видеть верстку этого контента
> * Кастомные типы `typescript` принято называть в `PascalCase` (с **большой буквы**)
> * `(state: RootState)` уже не нужно будет типизировать вручную стейт, когда замените везде хук `useSelector`. Нужно будет удалить дублирование типизации
> * `CreateRequest` является компонентом реакта, а их называют в виде **существительных**, а не глаголов

Геннадий, спасибо за ревью! Буду вспоминать ваши советы и подсказки, вы больше других ревьюили мои работы. Спасибо и удачи!

2024-02-16 19:45 UTC, kspshnik requested changes
Проверь ещё все stories на предмет корректности указания `isPendingChanges`, и т.п.

2024-02-16 19:45 UTC, kspshnik commented on server/db.json
> +      "isPendingChanges": false,
При заполненном `recipientReport` в `isPendingChanges` должно быть `true`

2024-02-16 19:45 UTC, kspshnik commented on server/db.json
> +      "status": "completed",
Всё-таки так быть не должно :(

2024-05-25 18:50 UTC, INextYP commented
Пока что нет смысла в этом PR. В main будем создавать после полного функционала

2024-05-25 18:50 UTC, closed without merging