Header
ya-pomogau/frontend pull request #39
Opened 2023-06-01 20:38 UTC by Danila4191

2023-06-02 08:50 UTC, niksmo requested changes
Привет! Здорово! Есть небольшие правки

2023-06-02 08:50 UTC, niksmo commented on src/hooks/dist/hooks.js
интересно как тут образовалась папка dist и транспилированный tsx в js
тут и в других папках надо это почистить

2023-06-02 08:50 UTC, niksmo commented on src/shared/ui/navigation/dist/side-bar.stories.js
удалить файл и папку dist

2023-06-02 08:50 UTC, niksmo commented on src/widgets/header/dist/header.stories.js
удалить файл и папку dist

2023-06-02 08:50 UTC, niksmo commented on package-lock.json
убрать этот файлик из коммита, странно что он изменен(
можно сделать софт резет чтобы передвинуть указатель и потом сделать все по красоте
```shell
git reset --soft 676a8b29e12c253b17be9f72528d2b03a8ef67fd
```
у тебя передвинется указатель на первый комит в ветке при этом файлики будут последней версии.
теперь нужно добавить нужные файлы в stage
```shell
git add src/shared/ui/navigation/* src/shared/hooks/* src/widgets/header/*
```
проверить `git status` что в stage нет ничего лишнего
далее сделать комит
а вот пушить на github придется форсированно `git push -f`

2023-06-02 08:50 UTC, niksmo commented on src/hooks/hooks.tsx
переместить на общий слой shared `shared/hook/media-query.ts` (можно ts, т.к. в нем нет jsx элементов)
в папке создать файл index.ts `shared/hook/index.ts` в котором будет запись
```javascript
export * from "./media-query.ts"
```

2023-06-02 08:50 UTC, niksmo commented on src/shared/ui/navigation/dist/side-bar.stories.js
> +    title: "SideBar",
`title: "widgets/SideBar"`

2023-06-02 08:50 UTC, niksmo commented on src/widgets/header/header.stories.tsx
> +  title: "Header",
`title: "widgets/Header"`

2023-06-02 12:09 UTC, Danila4191 commented on package-lock.json
Попробовал несколько раз поправить комит. В итоге либо файлы дублировались, либо происходил откат до первого комита и все файлы оставались без исправлений

2023-06-03 21:51 UTC, niksmo approved these changes

2023-06-03 21:51 UTC, merged