Fix/storybook stage 1
ya-pomogau/frontend pull request #420
Opened 2024-09-02 17:39 UTC by Elena-Orekhova

2024-09-20 05:44 UTC, INextYP requested changes

2024-09-20 05:44 UTC, INextYP commented on src/shared/ui/checkbox/index.tsx
> +  const [isChecked, setIsChecked] = useState(defaultChecked || false);
Нет, UI-компонет должен контролироваться извне.

Если ты хотела добавить поведения для сторибука, то там спокойно можно работать с состояниями. Но тут придется вернуть в исходное состояние

2024-09-20 05:44 UTC, INextYP commented on src/shared/ui/input/styles.module.css
Этот файл тоже возвращаем в исходное положение

2024-09-20 05:44 UTC, INextYP commented on src/shared/ui/input/index.tsx
Вернуть в исходное положение! Это специальная логика для резервирования места под ошибку

2024-09-20 05:44 UTC, INextYP commented on src/shared/ui/input-phone/index.tsx
> +          {(error || !isValid) && (
Вернуть в исходное положение! Это специальная логика для резервирования места под ошибку

2024-09-20 05:44 UTC, INextYP commented on src/shared/ui/input-phone/index.tsx
> +    const [isValid, setIsValid] = useState<boolean>(true);
Это всё делается извне!

2024-09-26 14:37 UTC, Elena-Orekhova commented on src/shared/ui/input/index.tsx
Если вернуть в исходное положение, текст ошибки в сторибуке виден даже если error = false, изменила на:           
<span className={cn(styles.error, 'text')}>
    {errorText && !error ? <span>&nbsp;</span> : errorText}
</span>

2024-09-30 11:33 UTC, Elena-Orekhova commented on src/shared/ui/input-phone/index.tsx
> +    const [isValid, setIsValid] = useState<boolean>(true);
Не могу понять, как должна происходить валидация. через Joi, через родительский компонент? какие параметры нужно передавать?

2024-10-30 13:52 UTC, INextYP submitted a review, later dismissed

2024-10-30 13:56 UTC, INextYP approved these changes

2024-10-30 13:56 UTC, merged