Feat/volonteer confirmation
ya-pomogau/frontend pull request #433
Opened 2024-09-16 20:10 UTC by Valeria375

В рамках задачи исправлено отображение кнопки "Подтвердить" у волонтера

Исправлено отображение в карточке:
Подтвержден (минимум 30 выполненных заявок)
Карточка с бело/синей кнопкой “Подтвердить”
На карточке пользователя и у раздела “Волонтеры” появляется оповещение

Подтвержден и проверен (минимум 60 заявок):
Карточка с серой кнопкой “Подтвердить”
Кнопка "Выдать ключи" активна
На карточке пользователя и у раздела “Волонтеры” появляется оповещение

2024-09-20 05:45 UTC, INextYP requested changes
Привет. Для начала исправь комментарии в коде

2024-09-20 16:58 UTC, Valeria375 commented
> Привет. Для начала исправь комментарии в коде

конфликты исправлены

2024-09-21 15:39 UTC, INextYP requested changes
Привет. Хорошо, но некоторые моменты нужно исправить:
- [x] Кнопка не активна - это значит у неё нет ховер эффекта вообще. У нас сейчас можно навестись на выключенную кнопку 
![image](https://github.com/user-attachments/assets/b60cf76f-ccf9-41c7-9089-ce2fba0d6dc0)
- [x] Необходимо переместить бэйджи на их законные места
![image](https://github.com/user-attachments/assets/ee92ffd9-483a-41b3-a927-cbb4c345dc29)
- [x] Если ключ у волонтера есть, то кнопка должна быть заблокирована
![image](https://github.com/user-attachments/assets/e16945b9-c02f-471a-acfb-b8f0ac47c0af)

- [x] Обязательно! Если меняешь что-то в ui-компоненте, то тебе нужно проверить, что ничего нигде не сломалось

2024-09-21 15:39 UTC, INextYP commented on src/shared/ui/user-cards/user-card-tiles/index.tsx
> +          // isAcceptButtonExclamationPointIcon={true}
Комментарии не оставляем

2024-09-21 15:39 UTC, INextYP commented on src/widgets/user-card/index.tsx
> +    if (score < 30 || score >= 60  && status === userStatus.CONFIRMED && role === userRole.VOLUNTEER)
Вынеси плз цифры в созвучные константы чтобы было понятно за что они отвечают

2024-09-24 06:14 UTC, INextYP approved these changes

2024-09-24 06:15 UTC, merged