fix/edit-task
ya-pomogau/frontend pull request #434
Opened 2024-09-17 10:22 UTC by YuriyZanin

Добавил PATCH метод в user-task-api для эндпойнта /recipient/tasks/${id}. Почему то сервер возвращает 500-ую ошибку, в чем проблема я не смог понять. Пытался локально, через докер, поднять бэк чтобы посмотреть логи, но у меня не получилось, ругается на ssl.

2024-09-19 14:55 UTC, INextYP commented
Привет, исправь конфликт в коде

2024-09-20 07:36 UTC, YuriyZanin commented
Поправил конфликт мерджа

2024-09-21 15:47 UTC, INextYP requested changes
Задача пока на паузе. Сначала разберемся с бэкендом

2024-09-21 15:47 UTC, INextYP commented on src/features/create-request/ui/steps/common-step/common-step.tsx
> +            {[...description].length > 160 && (
Зачем? Если у строки есть свойство `.length`

2024-09-21 15:58 UTC, INextYP commented
Сюда же в список исправлений - нужно блокировать кнопку обновления данных если ничего не поменялось

2024-09-23 05:34 UTC, YuriyZanin commented on src/features/create-request/ui/steps/common-step/common-step.tsx
> +            {[...description].length > 160 && (
это не моя правка

2024-10-21 08:41 UTC, INextYP approved these changes

2024-10-21 08:41 UTC, merged