Refactor/tasklist
ya-pomogau/frontend pull request #446
Opened 2024-09-21 20:52 UTC by makc67891

[Чистка компонента TaskList #439](https://github.com/ya-pomogau/frontend/issues/439)

2024-09-22 06:35 UTC, INextYP requested changes

2024-09-22 06:35 UTC, INextYP commented on src/entities/task/ui/task-list/index.tsx
> +  const [isOpen, setIsOpen] = useState(false);
Давай заменим этот стейт на использование хука `useControlModal`

2024-09-22 06:35 UTC, INextYP commented on src/entities/task/ui/task-list/index.tsx
>    const { role } = useAppSelector((state) => state.user);
Вот тут заменить на использования хука `useUser`

2024-09-22 06:35 UTC, INextYP commented on src/entities/task/ui/task-list/index.tsx
> +  const popupClose = () => {
Эта функция не понадобится после того, как мы возьмем useControlModal

2024-09-22 06:35 UTC, INextYP commented on src/entities/task/ui/task-list/index.tsx
>                className={classNames({
ВСЕ стили, которые через `classNames` собираются в этом файле нужно вынести в созвучные константы. Это нужно для очистки разметки, а также для более удобного процесса декомпозиции стилей в дальнейшем

2024-09-22 06:35 UTC, INextYP commented on src/entities/task/ui/task-list/index.tsx
>          !isLoading &&
вот такой "колбасы" быть в разметке не должно быть. Вынеси в константу

2024-09-22 12:05 UTC, makc67891 commented
Вроде всё исправил...

2024-09-24 06:50 UTC, INextYP approved these changes

2024-09-24 06:50 UTC, merged