Fix/chats types
ya-pomogau/frontend pull request #448
Opened 2024-09-23 16:22 UTC by Gottgunst

Текущее состояние задачи.
Последние два коммита (wip) не являются законченными решениями по рефакторингу и нуждаются в дальнейшей работе.

2024-09-23 17:23 UTC, kspshnik requested changes
Некорректно перенесена типизация Websockets.

И была ли оттестирована замена `keyof typeof T` на `ValueOf<T>` для const ... as const? Если да, вопрос к этой типизации снимается.

2024-09-23 17:23 UTC, kspshnik commented on src/shared/types/chat.types.ts
> +export const chatTypes = {
Причина изменения именования и типизации по сравнению с бэкендом? :)

2024-09-23 17:23 UTC, kspshnik commented on src/shared/types/chat.types.ts
> +export interface WSChatsResponseInterface {
Типизацию, связанную с WebSockets, необходимо перенести с бэкенда (берём в `src/common/types/websockets.types.ts`).

2024-09-23 17:50 UTC, Gottgunst commented on src/shared/types/chat.types.ts
> +export const chatTypes = {
Согласно прошлой задаче с enum пришли к решению, что константы с маленькой буквы будут, как и все переменные, а её тип с большой.

2024-10-06 09:41 UTC, INextYP approved these changes
Отлично!

2024-10-06 09:41 UTC, merged