Feat/tests hooks
ya-pomogau/frontend pull request #463
Opened 2024-09-26 22:42 UTC by Vasyankin-Alexander-Henchfiend

2024-10-12 15:14 UTC, INextYP requested changes
Необходимы некоторые доработки

2024-10-12 15:14 UTC, INextYP commented on src/shared/hooks/useTruncatedText.test.tsx
> +    expect(result.current.isTruncated).toBe(false);
Зачем два раза одно и тоже?

2024-10-12 15:14 UTC, INextYP commented on src/shared/hooks/useTruncatedText.test.tsx
> +    act(() => result.current.toggleIsShowingMore());
перед вызовом функции нужно для начала проверить, что состояние `false`

2024-10-12 15:14 UTC, INextYP commented on src/shared/hooks/useControlModal.test.tsx
> +    act(() => result.current.handleOpen());
перед вызовом функции нужно показать, что изначальное состояние равно `false`

2024-10-12 15:14 UTC, INextYP commented on src/shared/hooks/useControlModal.test.tsx
> +    act(() => result.current.handleClose());
перед вызовом функции нужно показать, что изначальное состояние равно `true`

2024-10-12 15:14 UTC, INextYP commented on src/shared/hooks/use-user.test.tsx
> +  it('should return actual user data', () => {
Хотелось бы увидеть кейс, когда пользователь не найден и хук  возвращает `null`

2024-10-12 15:14 UTC, INextYP commented on src/shared/hooks/use-form.test.tsx
> +    console.log(result);
Консоли сразу вычищаем

2024-10-13 13:02 UTC, Vasyankin-Alexander-Henchfiend commented on src/shared/hooks/useTruncatedText.test.tsx
> +    expect(result.current.isTruncated).toBe(false);
я вижу что хук возвращает два отдельных флага isExpanded и isTruncated, поэтому здесь проверяю что оба они возвращаются с корректных значением

2024-10-15 14:56 UTC, INextYP approved these changes

2024-10-15 14:56 UTC, merged