Refactor/filter stage 2
ya-pomogau/frontend pull request #479
Opened 2024-10-08 17:34 UTC by ZaytsevAlexanderGit

Поставленные задачи выполнил. 

Увидел, что Filter есть и на RequestPage, там немного по-другому сделал, чтобы он работал (почти ничего в изначальном не поменял). Так же для этого сделал в дефолтный state filterData - userCategories "all", что думаю не критично.

2024-10-13 12:17 UTC, INextYP requested changes
Привет! Отлично, но есть ещё некоторые моменты, которые желательно исправить

2024-10-13 12:17 UTC, INextYP commented on src/shared/libs/utils.ts
>    const handleTasksFilter = (arr: Task[]) =>
Функция в функции, если это не замыкание - это просто некрасиво выглядит. Лучше повыноси все функции за пределы функции handleFilterTasks

2024-10-13 12:17 UTC, INextYP commented on src/features/filter/components/filter-cover/filter-cover.tsx
В этом компоненте в двух местах ошибки TS

![image](https://github.com/user-attachments/assets/eaa8bb13-ec84-4fa4-94f7-b8a5908702df)

![image](https://github.com/user-attachments/assets/7db41543-c189-4d6c-9078-b8e4997ad57f)

- [ ] defaultValues и getDefaultValues лучше вынести из компонента. Незачем пересоздавать ссылки при каждом рендере

2024-10-13 12:17 UTC, INextYP commented on src/pages/profile-active/index.tsx
> +  const currentTask: Task[] = useMemo(() => {
Тут ошибка типизации

2024-10-13 12:17 UTC, INextYP commented on src/pages/profile-completed/index.tsx
> +  const currentTask: Task[] = useMemo(() => {
Также ошибка типизации
![image](https://github.com/user-attachments/assets/85f98642-e22b-4e7d-9e69-dec0b1d4c835)

2024-10-13 12:17 UTC, INextYP commented on src/pages/requests/index.tsx
> +  useEffect(() => {
для хранения вычислений лучше подойдет useMemo

2024-10-14 15:13 UTC, ZaytsevAlexanderGit commented on src/shared/libs/utils.ts
>    const handleTasksFilter = (arr: Task[]) =>
Исправлено

2024-10-14 16:23 UTC, ZaytsevAlexanderGit commented on src/pages/profile-completed/index.tsx
> +  const currentTask: Task[] = useMemo(() => {
Исправлено.

2024-10-14 16:23 UTC, ZaytsevAlexanderGit commented on src/pages/profile-active/index.tsx
> +  const currentTask: Task[] = useMemo(() => {
Исправлено.

2024-10-14 16:37 UTC, ZaytsevAlexanderGit commented on src/pages/requests/index.tsx
> +  useEffect(() => {
Заманено.

2024-10-15 11:38 UTC, ZaytsevAlexanderGit commented on src/features/filter/components/filter-cover/filter-cover.tsx
Поправлено. Сильно изящно в некоторых местах побороться с ошибками TypeScript не вышло.

2024-11-02 09:14 UTC, INextYP approved these changes

2024-11-02 09:15 UTC, merged