Переработан BalanceSettings и formData #490
ya-pomogau/frontend pull request #498
Opened 2024-10-14 15:49 UTC by ShinTerrible

2024-10-21 08:17 UTC, INextYP requested changes

2024-10-21 08:17 UTC, INextYP commented on .env.development.example
Верни файл обратно. Мы не меняем енв файлы для примера

2024-10-21 08:17 UTC, INextYP commented on docker-compose.dev.yml
верни файл обратно

2024-10-21 11:49 UTC, ShinTerrible commented on .env.development.example
Сделано.

2024-10-21 11:49 UTC, ShinTerrible commented on docker-compose.dev.yml
Сделано

2024-10-22 12:34 UTC, INextYP requested changes
Осталась ещё одна доработка

2024-10-22 12:34 UTC, INextYP commented on src/widgets/balance-settings/index.tsx
> +    const formattedData = Object.keys(formData).map((title, points) => {
некорректное выражение. Обрати внимание на  `map((title, points)`. Первый аргумент `tilte` - это ключ объекта, а `points` - это индекс массива

2024-10-23 11:51 UTC, ShinTerrible commented on src/widgets/balance-settings/index.tsx
> +    const formattedData = Object.keys(formData).map((title, points) => {
Готово.

2024-10-29 10:51 UTC, INextYP approved these changes
Хорошая работа :) Я внёс некоторые правки, обязательно посмотри как можно было ещё оптимизировать код, чтобы не проходить несколько раз по массиву :)

2024-10-29 10:52 UTC, merged