#486 Декомпозиция Mark и UserMark компонентов
ya-pomogau/frontend pull request #500
Opened 2024-10-16 14:32 UTC by AlinaBrode

* основные пункты из задачи выполнены
* обнаружена ошибка: в компоненте Mark используется признак срочности, которого там по логике быть не должно. Поставлена временная заглушка и TODO пометка
* Протестировать не получилось. Были три идеи:
  * посмотреть на компонент в сторибуке - не получилось, т.к. сторибук в development сломан
  * зайти в компонент YandexMap в приложении - не получилось, т.к., видимо, нужна авторизация. Если есть какой-то способ запуска и авторизации, буду рада его узнать.

2024-10-19 06:26 UTC, AlinaBrode commented
# Найденные вопросы
* В авторизованном доступе для метки таски показывается настоящий телефон заказчика таски. В неавторизованном доступе показывается заглушка "+7 (000) ***-**-**". 
* В task description в неавторизованном случае показывается properties.description, в авторизованном - properties.category.title. Должно ли так быть, или нужно и в том и в другом случае брать данные из одного источника?

# Тестирование

## Понятия
* маркеры
  * маркер пользователя (UserMark)
  * маркер задания (Mark)
    * маркер воздушного шара (balloonMarker)
* режимы
  * срочный / не срочный заказ
  * авторизованный /   не авторизованный пользователь

## Что нужно проверить
* маркер пользователя отображается как маркер не срочного задания (цвет 2E3192) в любых режимах
* режим не авторизованного пользователя, отображение в разных режимах метки задания 
  * div, class task_bio, аватар, имя получателя
  * <p class="${urgencyDateClass}">{{properties.date}}</p>: должно быть либо task_date_text либо task_date_text_urgent
  * class="${urgencyCountClass}": task_count либо task_count_urgent
* режим авторизованного пользователя; метка содержит дополнительную информацию:
  * div, class task_bio, аватар, имя получателя 
  * в task_icon_box проставлен правильный класс срочности task_count или task_count_urgent

## Методика тестирования
* вставляем console.log("someTaskText =", someTaskText) после вызова фукции; в логе смотрим на сформированное описание стиля

2024-10-21 08:29 UTC, INextYP requested changes

2024-10-21 08:29 UTC, INextYP commented on src/widgets/map/icons.tsx
> +        <svg width="53" height="53" viewBox="0 0 53 53" fill="${colorFill}" xmlns="http://www.w3.org/2000/svg">
1. Вынеси все `svg` теги из этого файла. Там явно есть повторяющиеся куски.
2. Не особо понятно, зачем нужно было выносить разметку целиком в функцию...
3. Никаких `any` в коммерческих проектах не должно быть

2024-10-21 08:29 UTC, INextYP commented on src/widgets/map/UserMark.tsx
> +  const isUrgentTask = false; // TODO: разобраться с тем, что имелось в виду. Кажется что для пользовательской метки срочность таски не релевантна.
Никакого хардкода быть не должно.

Проверь, нужно ли вообще передавать этот параметр в класс, если нет, то вычисти его

2024-10-22 06:02 UTC, AlinaBrode commented on src/widgets/map/UserMark.tsx
> +  const isUrgentTask = false; // TODO: разобраться с тем, что имелось в виду. Кажется что для пользовательской метки срочность таски не релевантна.
Параметр в класс передавать не нужно, так как у пользователя нет понятия "срочный/не срочный". Параметр вычещен.

2024-10-22 07:05 UTC, AlinaBrode commented on src/widgets/map/icons.tsx
> +        <svg width="53" height="53" viewBox="0 0 53 53" fill="${colorFill}" xmlns="http://www.w3.org/2000/svg">
1. Теги вынесены
2. Разметка в функции позволяет сосредоточить в одном месте логику выбора цветов и классов
3. any убран

2024-11-02 08:39 UTC, INextYP approved these changes
Отличная работа!

2024-11-02 08:39 UTC, merged