Fix/map task click
ya-pomogau/frontend pull request #514
Opened 2024-10-23 10:10 UTC by Romzes82

2024-10-30 13:28 UTC, INextYP requested changes

2024-10-30 13:28 UTC, INextYP commented on .eslintrc.json
> +    "project": "frontend/tsconfig.app.json"
Не нужно трогать файлы конфигурации. Всё итак прекрасно работает.

Верни файл в исходное состояние

2024-10-30 13:28 UTC, INextYP commented on src/pages/profile-map/index.tsx
> +            height={mediaQuery ? '75vh' : '709px'}
Будет ли в такой вариации контейнер тянуться?

2024-10-30 13:28 UTC, INextYP commented on src/pages/profile-map/index.tsx
> +  // const containerHeight = isUnconfirmed
Не нужно оставлять закомментированный код, если он не несёт смысловой нагрузки

2024-10-30 13:28 UTC, INextYP commented on src/shared/hooks/use-geolocation.tsx
> +      longitude: 37.61771,
Чьи это координаты?

2024-10-30 13:28 UTC, INextYP commented on src/widgets/map/Mark.tsx
> +  // const handleBallonClick = (e) => {
Если этот код не нужен - убрать

2024-10-30 13:28 UTC, INextYP commented on src/widgets/map/index.tsx
> +  const handeleBallonclick = (e: ymaps.IEvent) => {
`handleBallonClick`

2024-11-01 07:43 UTC, Romzes82 commented on src/pages/profile-map/index.tsx
> +            height={mediaQuery ? '75vh' : '709px'}
Контейнер YandexMap растягивается по вертикали в мобильной версии(когда меню слева скрыто), а в десктопной версии изменение высоты, я так понял, не требуется, в данном случае его высота определяется по нижнему краю меню слева, соблюдая пропорции.

2024-11-01 07:56 UTC, Romzes82 commented on .eslintrc.json
> +    "project": "frontend/tsconfig.app.json"
локально все было красным) вернул

2024-11-01 07:56 UTC, Romzes82 commented on src/pages/profile-map/index.tsx
> +  // const containerHeight = isUnconfirmed
удалил

2024-11-01 07:57 UTC, Romzes82 commented on src/shared/hooks/use-geolocation.tsx
> +      longitude: 37.61771,
это координаты нулевого километра в Москве. Обнулил обратно

2024-11-01 07:58 UTC, Romzes82 commented on src/widgets/map/Mark.tsx
> +  // const handleBallonClick = (e) => {
убрал

2024-11-01 07:58 UTC, Romzes82 commented on src/widgets/map/index.tsx
> +  const handeleBallonclick = (e: ymaps.IEvent) => {
переименовал на handleBalloonClick

2024-11-02 09:07 UTC, INextYP requested changes
На текущий момент при клике по пустому месту на карте точка пользователя перемещается на место клика. Так быть не должно + при клике на маркер заявки он не центруется как надо.

https://disk.yandex.ru/d/_yWnMflQuoHr9w

2024-11-09 07:50 UTC, INextYP requested changes

2024-11-09 07:50 UTC, INextYP commented on src/widgets/map/index.tsx
> +// import YMapsMap from '@pbe/react-yandex-maps/typings/Map';
Зачем эти 5 строчек ДУБЛЕЙ?

2024-11-09 07:50 UTC, INextYP commented on src/widgets/map/index.tsx
> +          // console.log(geoObject.getAddressLine());
Консоли в коде не нужны, особенно закоментированные

2024-11-09 07:50 UTC, INextYP commented on src/widgets/map/index.tsx
> +          onClick={() => 1}
Почему была закомментирована основная функциональность при клике на карту?

2024-11-09 07:50 UTC, INextYP commented on src/widgets/map/index.tsx
> +  const handeleBalloonClick = (e: ymaps.IEvent) => {
Название так и не исправлено

2024-11-09 07:50 UTC, INextYP commented on src/widgets/map/index.tsx
> +    const arr = [
Если у тебя в коде есть массив или объект, которые не изменяются, то лучше вынести их в конфстанты ДО создания компонента + нужно дать нормальное название. Комментарии тут не нужны

2024-11-09 09:58 UTC, Romzes82 commented on src/widgets/map/index.tsx
> +          onClick={() => 1}
именно эта функция (handleMapClick) вызывала перемещение точки пользователя при клике на карте. В прошлом ревью была поставлена задача избежать это

2024-11-09 13:06 UTC, INextYP requested changes
Всё ещё есть замечания.

2024-11-09 13:06 UTC, INextYP commented on src/widgets/map/index.tsx
> +  const [mapCenterSettings, setMapCenterSettings] = useState(mapSettings);
Почему была удалена функциональность из `develop`? Нужно вернуть.

2024-11-09 13:06 UTC, INextYP commented on src/widgets/map/index.tsx
> -  const onMapLoad = useCallback((refApi: YMapsApi) => {
Это тоже очень важная функциональность. Нужно вернуть.

При мёрже ВСЕГДА сначала смотри, что в `develop` а только потом вноси свои изменения

2024-11-09 13:06 UTC, INextYP commented on src/widgets/map/index.tsx
> +          onClick={() => 1}
Без этой функциональности не будет работать другой функционал, когда при создании заявки реципиент кликает на карту.

2024-11-09 13:06 UTC, INextYP commented on src/widgets/map/index.tsx
> +import { number } from 'joi';
Зачем тут `joi`?

2024-11-09 13:06 UTC, INextYP commented on src/widgets/map/index.tsx
> +const arrayValuesForCenteringPlacemark = [
Из структуры итак видно, что это `array`

2024-11-10 10:15 UTC, INextYP approved these changes

2024-11-10 10:15 UTC, merged