Fix/conflict chat types
ya-pomogau/frontend pull request #519
Opened 2024-11-01 10:15 UTC by Gottgunst

Work in progress

2024-11-03 18:18 UTC, kspshnik requested changes
Сразу: необходимо решить конфликт объединения, то есть вытянуть все изменения в `development`, вмёржить его в твою ветку, решить все конфликты и запушить исправленное.

2024-11-03 18:32 UTC, kspshnik reviewed
И прошелся по твоим замечаниям.
Ещё попросим @INextYP пройтись и посмотреть.

2024-11-03 18:32 UTC, kspshnik commented on src/entities/chat/mock-conflict.ts
> +// NOTE: Лишние типы, лучше сделать универсальный, который хранить в соответствующем поле в метаданных, а не кортеже.
Это и есть метаданные :)

2024-11-03 18:32 UTC, kspshnik commented on src/entities/chat/mock-conflict.ts
> +// NOTE: Кортеж не удобное решение, лучше отдельными полями передавать
В конфликтном чате у администратора открываются сразу оба, и подтягиваться будут сразу оба.

2024-11-03 18:32 UTC, kspshnik commented on src/entities/chat/mock-conflict.ts
> +  // NOTE: Зачем именовать поле в волонтёра?
В смысле? В типе есть такое свойство. Туда передаётся константа.

2024-11-03 18:32 UTC, kspshnik commented on src/pages/section-chats-conflict/index.tsx
> +    // NOTE: Избыточная сложность добычи этих данных в текущей структуре
ЕМНИП тут будет замена на `EntityAdapter` из `redux-toolkit`

2024-11-03 18:32 UTC, kspshnik commented on src/entities/chat/mock-conflict.ts
> +// NOTE: Имеет смысл перенести taskId в этот слой объекта?
Нет, это усложнит типизацию в целом - оба интерфейса чатов конфликтных (админ-волонтёр и админ-реципиент) порождаются от общего, где собраны все поля.

2024-11-03 18:32 UTC, kspshnik commented on src/widgets/profile-chats/index.tsx
> +// NOTE: для чего этот импорт?
А он используется где-то?

2024-11-03 20:18 UTC, Gottgunst commented on src/entities/chat/mock-conflict.ts
> +// NOTE: Лишние типы, лучше сделать универсальный, который хранить в соответствующем поле в метаданных, а не кортеже.
Такая логика заставляет делать монструозные конструкции, чтобы присвоить нужные данные в типовое поле:
```
(chat as RecipientConflictChatMetaInterface).recipient ??
(chat as VolunteerConflictChatMetaInterface).volunteer
 ```
 не вижу в этом решении профита.
 Лучше сделать типовую историю, 
 
 ```
 export const volunteerMetaConflictChat: userConflictChatMetaInterface = {
  type: chatTypes.CONFLICT_CHAT_WITH_VOLUNTEER,
  _id: '112',
  isActive: true,
  user: mockVolunteer,
  createdAt: new Date(2024, 7, 15, 0, 0, 0),
  updatedAt: new Date(2024, 7, 16, 31, 0, 0),
  unreads: 2,
  watermark: '0',
};
```
один тип вместо двух подобных

2024-11-03 20:29 UTC, Gottgunst commented on src/entities/chat/mock-conflict.ts
> +// NOTE: Кортеж не удобное решение, лучше отдельными полями передавать
Куда они будут подтягиваться, когда зритель видит только один чат в один момент времени? Ты хочешь держать сразу два вебсокет соединения? А что это даст?
Чтобы выводить эти данные приходится бегать по массиву, и искать нужные поля.
Лучше сразу сделать эти поля для чтения, чтобы получив клик на карточку типа — ```chatTypes.CONFLICT_CHAT_WITH_RECIPIENT```

обратится в соответствующее поле:
```
export const mockConflict: ConflictChatInfo = {
  meta: mockMetaConflictChatsMessage,
  chatVolunteer: mockConflictVolunteerMessages,
  chatRecipient: mockConflictRecipientMessages,
};
```
вариант с кортежем это явное усложнение. Если только ты не предполагаешь, что участников конфликта может стать больше двух (массив, а не кортеж).

Даже тут, бегать по массиву лишняя морока:
```
export const mockMetaConflictChatsMessage: ConflictChatsTupleMetaInterface = {
  moderator: mockAdmin,
  taskId: '222',
  adminVolunteerWatermark: 'string',
  adminVolunteerUnreads: 2,
  adminRecipientWatermark: 'string',
  adminRecipientUnreads: 1,
  volunteerMeta: volunteerMetaConflictChat,
  recipientMeta: recipientMetaConflictChat,
};
```
в таком варианте можно спокойно сразу вывести обе карточки с чатами не гоняя по кортежу с проверками.

2024-11-03 20:31 UTC, Gottgunst commented on src/entities/chat/mock-conflict.ts
> +  // NOTE: Зачем именовать поле в волонтёра?
Зачем спецификация имени? 
```
(chat as RecipientConflictChatMetaInterface).recipient ??
(chat as VolunteerConflictChatMetaInterface).volunteer
```

2024-11-03 20:32 UTC, Gottgunst commented on src/widgets/profile-chats/index.tsx
> +// NOTE: для чего этот импорт?
Уже нет)

2024-11-16 10:24 UTC, INextYP approved these changes
Отличная работа! Все основные косяки будем править в рамках отдельных задач

2024-11-16 10:24 UTC, merged