Создание заявки. Шаг с выбором места #539
ya-pomogau/frontend pull request #548
Opened 2024-11-16 18:49 UTC by winterlena

2024-11-20 19:07 UTC, INextYP requested changes
На текущий момент проблема в том, что инпут НЕ заполнен, хоть кнопка и активна

![image](https://github.com/user-attachments/assets/8e8dc1fc-ac96-4929-98d4-fda78c693f8d)

2024-11-20 19:07 UTC, INextYP commented on src/shared/ui/input/styles.module.css
> +  /* height: 32px; высота инпута по верстке */
стили для UI компонентов меняем ИСКЛЮЧИТЕЛЬНО через `extraClass`

2024-11-20 19:07 UTC, INextYP commented on src/features/create-request/ui/steps/address-step/address-step.tsx
> +      {showError && (
Место под ошибку должно быть заранее зарезервировано чтобы не было "прыжков" контента

2024-11-21 06:54 UTC, winterlena commented on src/shared/ui/input/styles.module.css
> +  /* height: 32px; высота инпута по верстке */
а что если он и есть extraClass?

2024-11-30 12:59 UTC, INextYP requested changes
Осталось исправить последний баг

2024-11-30 12:59 UTC, INextYP commented on src/features/create-request/ui/steps/address-step/address-step.tsx
> +import { add } from 'date-fns';
Зачем это тут, если нигде не используется в коде?

2024-11-30 12:59 UTC, INextYP commented on src/features/create-request/ui/steps/address-step/address-step.tsx
> +          disabled={(isEmptyAddress || !hasCoordinates) && !isEmptyAddress}
Перепроверь это условие. Сейчас если в инпуте пусто то:

![image](https://github.com/user-attachments/assets/6915c60f-efee-407d-a158-755b60f67bbd)

2024-11-30 17:41 UTC, INextYP approved these changes
Отлично! Задача выполнена!

2024-11-30 17:41 UTC, merged