Fix/create task select category
ya-pomogau/frontend pull request #549
Opened 2024-11-18 11:31 UTC by winterlena

2024-11-20 19:12 UTC, INextYP requested changes
Необходимо исправить...

2024-11-20 19:12 UTC, INextYP commented on src/shared/ui/dropdown/index.tsx
> +            Такая заявка уже существует. <br />
Тут явно не нужен `br` - в современной вёрстке можно спокойно обойтись без этого костыля

2024-11-20 19:12 UTC, INextYP commented on src/shared/ui/tooltip/styles.module.css
> +  width: 370px;
Изменение размеров в UI компоненте может повлечь за собой ошибки с размерами в других компонентах, где этот тултип используется. Рекомендую передавать доп стили через пропсы

2024-11-21 15:55 UTC, winterlena commented on src/shared/ui/tooltip/styles.module.css
> +  width: 370px;
можно через экстра-класс сделать?

2024-11-30 13:19 UTC, INextYP requested changes

2024-11-30 13:19 UTC, INextYP commented on src/shared/ui/dropdown/index.tsx
> +            {'Такая заявка уже существует.\nДождитесь ее выполнения.'}
В комбинации `Такая заявка уже существует. Дождитесь ее выполнения.` надобность в `\n` и дополнительном селекторе `preWrap` полностью отпадает

2024-11-30 13:19 UTC, INextYP commented on src/shared/ui/dropdown/styles.module.css
> +.paragraphResize {
Зачем? Мы UI компоненту передаём `variant="paragraphResize"`, который уже содержит эти стили 

![image](https://github.com/user-attachments/assets/455ff6ef-a906-4308-8e36-276846fe649d)

2024-11-30 13:19 UTC, INextYP commented on src/shared/ui/tooltip/styles.module.css
> -    display: none;
Любые изменения UI компонента только через `extraClass`

2024-11-30 13:19 UTC, INextYP commented on src/shared/ui/dropdown/index.tsx
>            pointerPosition={'right'}
По дизайну `pointerPosition={'center'}` но в мобилке он в левом части, это явный косяк дизайнера. Давай просто изменим тут и всё

2024-11-30 13:19 UTC, INextYP commented on src/shared/ui/tooltip/index.tsx
> +        setPointerPositionState('center');
Логику UI компонента не трогаем!

2024-12-07 10:58 UTC, INextYP approved these changes
Отличная работа!

2024-12-07 10:58 UTC, merged