Frontend #557: Исправлена верстка в панели администратора, исправлены скачки контента
ya-pomogau/frontend pull request #563
Opened 2024-11-25 15:55 UTC by Daviddov1496

Верстка панели администратора подогнана в соответствии с фигмой, отображение кнопок проверено во всех состояниях и во всех табах

2024-11-30 14:21 UTC, INextYP requested changes
Привет. Пожалуйста повнимательней ещё раз проверь всю вёрстку.

Сейчас ещё имеются расхождения в карточках.

Из того, что вижу:

- не совпадают отступы с дизайном

![image](https://github.com/user-attachments/assets/70388870-5f04-4a76-a9dd-bd321f865c12)

- иконка неккоректного размера. Если баллов у пользователя нет, то там должнен быть 0, а у тебя пустота

![image](https://github.com/user-attachments/assets/b76d76a6-b55c-4fb7-994b-1f020a0803eb)

- на кнопке "подтвердить", где рядом есть бейдж, при наведении происходят прыжки
![image](https://github.com/user-attachments/assets/54baa0ce-7af2-459f-8e6d-df64c36fb47f)

- кнопки должны всегда находиться на одном месте. Сейчас они съезжают
![image](https://github.com/user-attachments/assets/f4298e84-9844-4226-9061-9c3ea1edd8b2)

- отсуп между id и кнопками не совпадает с дизайном
![image](https://github.com/user-attachments/assets/b765a03e-2847-4530-b895-043f291b15f2)

- карточки админов сломаны
![image](https://github.com/user-attachments/assets/132ff251-f8b3-441d-974e-464d9b9a7eef)

2024-11-30 14:21 UTC, INextYP commented on .storybook/main.ts
> +    '@storybook/addon-interactions'
Не нужно удалять никакие пакеты. Если такая надобность появится, то этим займется тимлид или техлид.

Сейчас попрошу вернуть на место.

2024-11-30 14:21 UTC, INextYP commented on src/shared/ui/button/styles.module.css
> +  min-width: 69px;
ИЗМЕНЕНИЯ В UI КОМПОНЕНТАХ ТОЛЬКО ЧЕРЕЗ EXTRACLASS

2024-12-04 11:01 UTC, Daviddov1496 commented
Исправлены замечания по верстке: 1) отступы теперь соответствуют макету; 2)на кнопке подтвердить, где рядом есть бейдж, при наведении больше происходят прыжки, а так же бейдж больше не мешает разметке; 3) Карточки админов отображаются с правильными отступами; 4) счетчик баллов работает;

2024-12-07 12:55 UTC, INextYP approved these changes

2024-12-07 12:55 UTC, merged