Remove Tooltip from Phone Icon on task card. Add link with tel property.
ya-pomogau/frontend pull request #568
Opened 2024-11-29 13:30 UTC by ZaytsevAlexanderGit

PR по задаче #544.

Сейчас сделано первое задание. Насколько я его понял, необходимо заменить Tooltip на просто ссылку с возможностью звонить (согласно брифу я так-же это понял).

По второму task - задача состоит в проверке, что логика работает так? 
Вопрос задается, так как Issue - https://github.com/ya-pomogau/frontend/issues/522 как раз о том, чтобы сделать как надо.
Этот PR пока в проверке.

Плюс по вопросам из этого PR в пачке согласно метода reject который, для волонтеров должен отменять назначение.
Я посмотрел на backend, ну и собственно использовал сам этот метод и он делает в Task пункт volounteerReport в статус rejected. Такая таска подкрашивается красным, но остается в активных у волонтера, и во взятых у реципиента. Соответственно и другие волонтёры её не видят (так как она accepted, а на карте, я так понимаю created).
Подскажи, не там смотрю, или нужно доделать?

2024-11-30 12:42 UTC, INextYP requested changes

2024-11-30 12:42 UTC, INextYP commented on src/entities/task/ui/task/components/task-user/index.tsx
> +        {user ? (
В теории тут можно было один раз написать 

```tsx
<a href={`tel:${user.phone}`} style={{ borderRadius: '50%' }}>
            <RoundButton
              buttonType={taskButtonType.phone}
              disabled={isPageCompleted}
            />
</a>
```

А у ссылки просто подставлять номер телефона если пользователь есть ну и выключать нажатия через css

2024-11-30 12:44 UTC, INextYP commented
> PR по задаче #544.
> 
> Сейчас сделано первое задание. Насколько я его понял, необходимо заменить Tooltip на просто ссылку с возможностью звонить (согласно брифу я так-же это понял).
> 
> По второму task - задача состоит в проверке, что логика работает так? Вопрос задается, так как Issue - #522 как раз о том, чтобы сделать как надо. Этот PR пока в проверке.
> 
> Плюс по вопросам из этого PR в пачке согласно метода reject который, для волонтеров должен отменять назначение. Я посмотрел на backend, ну и собственно использовал сам этот метод и он делает в Task пункт volounteerReport в статус rejected. Такая таска подкрашивается красным, но остается в активных у волонтера, и во взятых у реципиента. Соответственно и другие волонтёры её не видят (так как она accepted, а на карте, я так понимаю created). Подскажи, не там смотрю, или нужно доделать?

Да, не углядел, тогда в целом можно не проверять. Но если уже провирил, то только плюс будет, так как одна голова хорошо, а две ещё лучше)

2024-12-01 11:37 UTC, ZaytsevAlexanderGit commented on src/entities/task/ui/task/components/task-user/index.tsx
> +        {user ? (
Поправлено.

2024-12-01 11:42 UTC, ZaytsevAlexanderGit commented
Поправил ссылку.

Насчет второго пункта тогда не буду проверять, так как задача делается другим. Но по поводу возможности отказаться волонтером от задачи, посмотрим, действительно ли получается, что на бэкенде нет такого метода, только volounteerReport в статус rejected переводится. Возможно админ потом может переводить, но это я тоже не нашел.

2024-12-01 12:10 UTC, kspshnik commented
> что на бэкенде нет такого метода, только volounteerReport в статус rejected переводится. Возможно админ потом может переводить, но это я тоже не нашел.

Действительно нет, по ТЗ отказ волонтёра или снятие задачи реципиентом после взятия волонтёром - **только** через переписку с администраторами.

2024-12-01 13:00 UTC, ZaytsevAlexanderGit commented
> Действительно нет, по ТЗ отказ волонтёра или снятие задачи реципиентом после взятия волонтёром - **только** через переписку с администраторами.
И это вполне логично, на мой взгляд.
Однако, тогда получается несоответствие с заданием как будто. В https://github.com/ya-pomogau/frontend/issues/522 вторая таска предполагает, что задача отменится просто по желанию волонтера.

2024-12-01 18:29 UTC, INextYP commented
> > Действительно нет, по ТЗ отказ волонтёра или снятие задачи реципиентом после взятия волонтёром - **только** через переписку с администраторами.
> 
> И это вполне логично, на мой взгляд. Однако, тогда получается несоответствие с заданием как будто. В #522 вторая таска предполагает, что задача отменится просто по желанию волонтера.

@kspshnik в чём вопрос? По ТЗ как раз волонтер может отказаться от задачи, если до её старта более 24 часов

![image](https://github.com/user-attachments/assets/0826ccd3-9aec-4986-8cac-5855d126a446)

2024-12-07 12:46 UTC, INextYP approved these changes

2024-12-07 12:46 UTC, merged