adds ui-kit logo and bottom-bar
ya-pomogau/frontend pull request #8
Opened 2023-05-19 20:20 UTC by AlenaIsmagilova

2023-05-19 21:23 UTC, niksmo requested changes

2023-05-19 21:23 UTC, niksmo commented on src/shared/ui/bottom-bar/bottom-bar.stories.ts
> +  title: "Bottom-bar",
Алёна, давай будем делать тайтл таким же как и название компонента - это упростит его поиск в проекте.

2023-05-20 07:41 UTC, AlenaIsmagilova commented on src/shared/ui/bottom-bar/bottom-bar.stories.ts
> +  title: "Bottom-bar",
ok,done

2023-05-20 13:50 UTC, niksmo approved these changes

2023-05-20 13:51 UTC, merged