[Sync]
ya-pomogau/frontend pull request #90
Opened 2023-11-28 13:33 UTC by kspshnik

2023-11-28 13:34 UTC, marussia1996 approved these changes, later dismissed

2023-11-29 12:56 UTC, INextYP requested changes

2023-11-29 12:56 UTC, INextYP commented on src/shared/libs/utils.ts
> +const BASE_URL = 'http://localhost:3000';
Про это уже писал в одном из PR. Такие штуки лучше выносить в .env

2023-11-29 12:56 UTC, INextYP commented on src/services/user-api.ts
> -import { API_URL } from '../config/api-config';
Вот эта переменная как раз и нужна будет на 12-й строчке в качестве значения baseUrl

2023-11-29 14:14 UTC, marussia1996 commented on src/shared/libs/utils.ts
> +const BASE_URL = 'http://localhost:3000';
в 148 PR форка исправила - посмотри)

2023-11-29 14:14 UTC, marussia1996 commented on src/services/user-api.ts
> -import { API_URL } from '../config/api-config';
в 148 PR форка исправила - посмотри)

2023-12-11 17:36 UTC, INextYP requested changes

2023-12-11 17:36 UTC, INextYP commented on src/shared/libs/utils.ts
> +  window.location.href = `https://oauth.vk.com/authorize?client_id=${process.env.REACT_APP_CLIENT_ID}&display=page&redirect_uri=${cbLink}&scope=email&response_type=code&v=5.120&state=4194308`;
`process.env.REACT_APP_CLIENT_ID` вынести в config

2023-12-11 17:36 UTC, INextYP commented on src/pages/profile-map/index.tsx
> +                  : 30.315644,
Я бы все "магические" числа посоветовал бы вынести в константы

2023-12-11 17:36 UTC, INextYP commented on src/widgets/user-card/index.tsx
>      scores >= 30 && !checked && scores < 60;
Опять "магические" числа. Было бы более понятнее, если было бы не 60, а MAX_SCORES_COUNT как пример и так со всеми числами

2023-12-13 18:47 UTC, INextYP approved these changes

2023-12-14 12:18 UTC, kspshnik reviewed
ОК

2023-12-14 12:19 UTC, merged