forms validated with rhf+joi
ya-pomogau/frontend pull request #92
Opened 2023-12-10 22:52 UTC by YuliaMenachoPages

Перевела на react-hook-form+joi формы регистрации, логина и обратной связи
Прошу обратить внимание на встроенную валидацию пароля в joi, пропускает значения с 1 символом после точки
Паттерн для номера телефона, на мой взгляд, может вызвать трудности, особенно у людей с ОВЗ и пожилых (пробелы, скобки)

2023-12-11 08:05 UTC, kspshnik requested changes
Юля, огромная работа, спасибо огромное!
Всё хорошо, надо только поправить три основных момента везде:

1. Вынеси, пожалуйста, все схемы в отдельную папку `src/shared/joi-schemes`, по файлу на каждое поле своего типа (инпут текста, инпут телефона и т.д.) или на аналогичные формы, а схему для каждой формы уже надо собирать из них в папке страницы/виджета с этой формой в файл типа `<page-or-widget-name>.joi-scheme.ts`. Другими словами, надо максимально выделить общие/аналогичные схемы (возможно, не "построчно" а более крупными формами) и вынести их в общее.
2. Вся работа с извлечением переменных окружения (с `proccess.env` и т.п.) происходит в файлах, лежащих в `src/config`. Создание fallback-значений должно происходить там же. Во всех остальных местах мы только импортируем константы/переменные из `src/config/<config-name>.ts`.
3. Использование типа `any` **строго и категорически запрещено** без **прямого требования** документации сторонней библиотеки типизировать  конкретную переменную/свойство/аргумент как `any` или доказательства абсолютной невозможности типизировать конкретную переменную/свойство/аргумент, в т.ч. с использованием дженериков. 

Ну и конкретные мелкие вещи тоже отметил.

2023-12-11 08:05 UTC, kspshnik commented on src/config/api-config.ts
> -  'Content-Type': 'application/json',
А это точно не сломает остальные запросы? 
Ключи (названия свойств) в заголовках запроса - **стандартизованы в RFC**, все эти *"lowerCamelCase"* тут не роялят.

2023-12-11 08:05 UTC, kspshnik commented on src/entities/user/types.ts
> +  id: number | string;
Не-а :) База - Mongo, `_id` (оно же `id`) - строго `string`. Тут надо наоборот - разыскать, где `number` (это legacy, в первой версии база была PostgreSQL, а там `id` числовые) и заменить на строку.

2023-12-11 08:05 UTC, kspshnik commented on src/features/edit-viewer-info/ui/index.tsx
> +// Юлия М.-П. изменила тип valueId с string на string | number, чтобы убрать ошибки при запуске
Аналогично замечанию к `user.types.ts`

2023-12-11 08:05 UTC, kspshnik commented on src/pages/feedback/feedback.tsx
> +const schema = Joi.object({
Вынеси, пожалуйста, все схемы в отдельную папку `src/shared/joi-schemes`, по файлу на каждое поле своего типа (инпут текста, инпут телефона и т.д.), а схему для каждой формы уже надо собирать из них в папке страницы/виджета с этой формой в файл типа `<page-or-widget-name>.joi-scheme.ts`.
Другими словами, надо максимально выделить общие/аналогичные схемы (возможно, не "построчно" а более крупными формами) и вынести их в общее.

2023-12-11 08:05 UTC, kspshnik commented on src/pages/feedback/feedback.tsx
> +      /* eslint-disable */
Не допускается отключение правил линтера без обоснования причин.

2023-12-11 08:05 UTC, kspshnik commented on src/pages/login/index.tsx
> +const schema = Joi.object({
Аналогично предыдущему замечанию, и про отключение линтера тоже.

2023-12-11 08:05 UTC, kspshnik commented on src/pages/login/index.tsx
>    const [login, { isLoading }] = useLoginMutation();
Нет. Для страниц входа мы **НЕ ИСПОЛЬЗУЕМ** `RTK Query`, это нецелесообразно: получаемый объект используется *всеми* страницами.
Обращение на сервер будет производиться с помощью `asyncThunk`. Посмотри `src/services/system-slice.ts` в части получения юзверя. Админ будет аналогично, это тот же юзверь, просто у него поля будут правовыдающие :)

2023-12-11 08:05 UTC, kspshnik commented on src/pages/register-form/index.tsx
> +    /* eslint-disable */
Аналогично см. выше про схемы и отключения.

2023-12-11 08:05 UTC, kspshnik commented on src/services/auth.ts
> +export const authApi = new Auth(API_URL || '', AUTH_ROUTES, DEFAULT_HEADERS);
Не-а. Такую штуку можно делать максимум в `src/config/api-config.ts` писать - все изменения и подкладки делаем в **одном** месте, во всех остальных - **только** импорт.

2023-12-11 08:05 UTC, kspshnik commented on src/services/user-api.ts
> +  baseQuery: fetchBaseQuery({ baseUrl: process.env['REACT_APP_FRONT_LOCAL '] }),
Нет. Используем **ТОЛЬКО** импортированные из `src/config/api-config.ts` константы, все извлечения из переменных окружения можно делать строго и только в этом файле.

2023-12-11 08:05 UTC, kspshnik commented on src/shared/ui/info-container-content/index.tsx
> +  id?: number | string;
`id: string`

2023-12-11 08:05 UTC, kspshnik commented on src/shared/ui/input-address/index.tsx
> +  errorText?: string | any;
Тип `any` **ЗАПРЕЩЁН** кроме прямо предписанных (сторонней) библиотекой случаев.
В данном случае нам нужен `string | null` ;o)

2023-12-11 08:05 UTC, kspshnik commented on src/shared/ui/input/index.tsx
> +  errorText?: string | any;
`any` запрещён к использованию.

2023-12-11 08:05 UTC, kspshnik commented on src/shared/ui/password-input/index.tsx
> +  errorText?: string | any;
`any` запрещён к использованию

2023-12-11 08:05 UTC, kspshnik commented on src/shared/ui/password-input/index.tsx
> +  register: any;
Здесь нельзя обойтись разве без `any`?
Что предписывает библиотека? Точно нет варианта типизации через generics?

2023-12-27 22:13 UTC, YuliaMenachoPages commented on src/entities/user/types.ts
> +  id: number | string;
Исправила

2023-12-27 22:14 UTC, YuliaMenachoPages commented on src/features/edit-viewer-info/ui/index.tsx
> +// Юлия М.-П. изменила тип valueId с string на string | number, чтобы убрать ошибки при запуске
Исправила

2023-12-27 22:16 UTC, YuliaMenachoPages commented on src/config/api-config.ts
> -  'Content-Type': 'application/json',
Исправила

2023-12-27 22:17 UTC, YuliaMenachoPages commented on src/pages/feedback/feedback.tsx
> +      /* eslint-disable */
Исправили вместе на созвоне

2023-12-27 22:18 UTC, YuliaMenachoPages commented on src/pages/login/index.tsx
> +const schema = Joi.object({
Исправили (правильно закомментировали и описали причину) вместе на созвоне

2023-12-27 22:20 UTC, YuliaMenachoPages commented on src/pages/register-form/index.tsx
> +    /* eslint-disable */
Исправили вместе на созвоне

2023-12-27 22:32 UTC, YuliaMenachoPages commented on src/services/auth.ts
> +export const authApi = new Auth(API_URL || '', AUTH_ROUTES, DEFAULT_HEADERS);
Исправили вместе на созвоне

2023-12-27 22:34 UTC, YuliaMenachoPages commented on src/services/user-api.ts
> +  baseQuery: fetchBaseQuery({ baseUrl: process.env['REACT_APP_FRONT_LOCAL '] }),
Исправили вместе на созвоне

2023-12-27 22:44 UTC, YuliaMenachoPages commented on src/shared/ui/info-container-content/index.tsx
> +  id?: number | string;
Исправила

2023-12-27 22:46 UTC, YuliaMenachoPages commented on src/shared/ui/input-address/index.tsx
> +  errorText?: string | any;
Исправила

2023-12-27 22:46 UTC, YuliaMenachoPages commented on src/shared/ui/input/index.tsx
> +  errorText?: string | any;
Исправила

2023-12-27 22:46 UTC, YuliaMenachoPages commented on src/shared/ui/password-input/index.tsx
> +  errorText?: string | any;
Исправила

2023-12-27 23:37 UTC, YuliaMenachoPages commented on src/shared/ui/password-input/index.tsx
> +  register: any;
Исправила

2023-12-28 09:35 UTC, marussia1996 reviewed
разреши пожалуйста конфликты

2023-12-28 13:04 UTC, YuliaMenachoPages commented on src/pages/login/index.tsx
>    const [login, { isLoading }] = useLoginMutation();
На созвоне договорились, что этот участок поправит хозяйка этого кода

2023-12-28 17:12 UTC, YuliaMenachoPages commented
Исправила, готово к проверке

2024-01-11 14:46 UTC, marussia1996 requested changes

2024-01-11 14:46 UTC, marussia1996 commented on src/shared/joi-schemes/name-required.ts
> +const nameRequiredJoi = Joi.string().required().messages({
а можно ли указать, что только буквы могут использоваться.. Просто при вводе ФИО получается, что пользователь может ввести цифры, символы и этот никак не является именем

2024-01-16 16:00 UTC, YuliaMenachoPages commented on src/shared/joi-schemes/name-required.ts
> +const nameRequiredJoi = Joi.string().required().messages({
добавила

2024-05-25 18:48 UTC, INextYP commented
На текущий момент лишняя функциональность

2024-05-25 18:48 UTC, closed without merging