feature: верстка страницы администратора для чатов
ya-pomogau/frontend pull request #94
Opened 2023-12-20 11:10 UTC by Anton-Laid

2023-12-20 11:37 UTC, kspshnik requested changes
В целом хорошо. Но историю с константами надо поправить. 
И здорово бы разобраться таки с `API_URL`

2023-12-20 11:37 UTC, kspshnik commented on src/app/routing/router.tsx
> +          <Route path="/test" element={<ProfileChatsPages />} />
Откуда такой странный роут? :)

2023-12-20 11:37 UTC, kspshnik commented on src/services/tasks-api.ts
> +  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:3001' }),
Так и не удалось победить?

2023-12-20 11:37 UTC, kspshnik commented on src/widgets/conversation-widget/constants.ts
Это же мок для проверки вёрстки?

Такие файлы надо вынести из компонент в какое-то специально обученное место, типа `src/mock-data` или подобное. Иначе большой шанс эту чебурашку оставить до передачи заказчику, тупо забыв :)

2023-12-20 11:44 UTC, kspshnik requested changes

2023-12-20 11:44 UTC, kspshnik commented on src/services/tasks-api.ts
> +  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:3001' }),
Необходимо вернуть на `API_URL`. Проблема в твоей локальной настройке: я сейчас выкачал ветку, заменил на `API_URL` - у меня всё работает. Проверь наличие `.env` в **корне проекта** (**не** в `src/`).

2023-12-20 12:07 UTC, Anton-Laid commented
я еще ничего не сделал) Но подправлю)

2023-12-20 12:08 UTC, Anton-Laid commented on src/app/routing/router.tsx
> +          <Route path="/test" element={<ProfileChatsPages />} />
я еще в релиз не отправлял, запушил только для того, чтобы с другого пк делать проект дальше

2023-12-20 12:08 UTC, Anton-Laid commented on src/services/tasks-api.ts
> +  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:3001' }),
Увы, нет, буд Александру писать

2023-12-20 15:04 UTC, kspshnik commented on src/app/routing/router.tsx
> +          <Route path="/test" element={<ProfileChatsPages />} />
А PR зачем создал??
Может его закрыть как созданный ошибочно?

2024-01-12 14:02 UTC, Anton-Laid commented
Поправил стили, можно проверить верстку страниц с чатами

2024-01-13 13:55 UTC, INextYP reviewed
Первая проверка. 
Пока что прошелся по коду, не запуская его и не вникая в общую логику.

2024-01-13 13:55 UTC, INextYP commented on src/widgets/window-interaction-users/styles.module.css
> +  .container-modile {
А что значит `modile`?

2024-01-13 13:55 UTC, INextYP commented on src/widgets/window-interaction-users/styles.module.css
> +  -webkit-line-clamp: 1; /* Количество строк */
Удаляй сразу комментарии. По коду видно, что он делает

2024-01-13 13:55 UTC, INextYP commented on src/widgets/window-interaction-users/index.tsx
> +  onClick: (text: string, func?: boolean) => void;
что за `func` и какую роль он выполняет?

2024-01-13 13:55 UTC, INextYP commented on src/widgets/window-interaction-users/index.tsx
> +import React, { ReactElement, ReactNode } from 'react';
Не нужно тянуть весь React, используй деструктуризацию

2024-01-13 13:55 UTC, INextYP commented on src/widgets/window-interaction-users/index.tsx
> +export const WindowInteractionUsers: React.FC<IWindowInteractionUsers> = (
Вместо `React.FC` используй просто `FC` (деструктуризация from "React")

2024-01-13 13:55 UTC, INextYP commented on src/widgets/window-interaction-users/index.tsx
> +              onClick={() => props.onClick('close')}
У тебя 3 раза повторяется `onClick={() => props.onClick('close')}` . Разумнее всего было бы вынести это в отдельную функцию и использовать её во всех местах.

2024-01-13 13:55 UTC, INextYP commented on src/widgets/window-interaction-users/index.tsx
> +                styles.name
Для улучшения общей читабельности кода я бы посоветовал вынести все действия по работе с clsx в переменные. А тут использовать сами переменные, например, определяем переменную 
```
const chatName = cn('text-inter', 'm-0', 'text_size_large', 'text_type_regular', styles.name)
```

А в этом месте ты заиспользуешь эту переменную:

```
<p className={chatName}>{props.chatmateInfo?.name}</p>
```

И так во всех местах, где используется clsx. Ты сразу увидишь, насколько чище становится разметка :)

2024-01-13 13:55 UTC, INextYP commented on src/widgets/window-interaction-users/index.tsx
> +  props
Таки не забываем деструктуризировать пропсы :)

2024-01-13 13:55 UTC, INextYP commented on src/widgets/profile-chats/index.tsx
> +export const ProfileChatsPages = ({ children }: ProfileChatsPagesProps) => {
Нужно придерживаться какой-то единой типизации компонента. Или так или через `FC<InterfaceProps>`. Обращу внимание, когда ты типизируешь через `FC`, то `children` идёт из `коробки` и необходимость интерфейса `ProfileChatsPagesProps` пропадает

2024-01-13 13:55 UTC, INextYP commented on src/pages/section-chat-hub/index.tsx
> +    messages: IMessage[];
Лучше вынести в отдельный интерфейс, так как на 39-й строке у тебя повторяется это всё + в `src/pages/section-chat-picker/index.tsx`

2024-01-13 13:55 UTC, INextYP commented on src/shared/types/conflict.ts
> +  specialization: 'valanter' | 'recipient';
Тут используй типы пользователя. В названии волонтера явно ошибка

2024-01-13 13:55 UTC, INextYP commented on src/shared/ui/conflict-card/index.tsx
> +  specialization: 'valanter' | 'recipient';
у тебя же уже большинство свойств используются в типе IConflictUser, не проще от него унаследоваться?

2024-01-13 13:55 UTC, INextYP commented on src/shared/ui/conflict-card/index.tsx
> +        buttonType={optionCard === 'conflict' ? 'conflict' : 'confirm'}
Не знаю, как остальные разработчики, но я не люблю висящие строки. Я всегда рекомендую выносить это в `enum`

2024-01-13 13:55 UTC, INextYP commented on src/shared/ui/gradient-divider/index.tsx
> +export const GradientDivider: React.FC<PropsGradientDivider> = (props) => {
Используй просто `FC` , деструктуризиировав его из `import { FC } from 'react';` + деструктуризируй сразу пропсы

2024-01-13 13:55 UTC, INextYP commented on src/shared/ui/input-wrapper/index.tsx
> +import React, { ChangeEvent, useState } from 'react';
Опять импорт `React`. Не нужно его тащить целиком. Используй деструктуризацию.

2024-01-13 13:55 UTC, INextYP commented on src/shared/ui/input-wrapper/index.tsx
> +  containerMessages: boolean;
Странное название для булева ключа. Логичнее было назвать `isContainerMessages`

2024-01-13 13:55 UTC, INextYP commented on src/shared/ui/input-wrapper/index.tsx
> +  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
`ChangeEvent` вытягиваем из реакта

2024-01-13 13:55 UTC, INextYP commented on src/shared/ui/input-wrapper/index.tsx
> +export const InputWrapper: React.FC<PropsInputWrapper> = (props) => {
`FC` вытягиваем из реакта + деструктуризируем пропсы сразу или тут или ниже
`const {  } = props;`

2024-01-13 13:55 UTC, INextYP commented on src/shared/ui/input-wrapper/index.tsx
> +    e: React.ChangeEvent<HTMLInputElement>
`ChangeEvent` вытягиваем из реакта

2024-01-13 13:55 UTC, INextYP commented on src/shared/ui/input-wrapper/index.tsx
> +  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
`FormEvent` вытягиваем из реакта

2024-01-13 13:55 UTC, INextYP commented on src/shared/ui/input-wrapper/index.tsx
> +              key={i}
у `dataMessage`-элемента нет более уникального id для установки в качестве key?

2024-01-13 13:55 UTC, INextYP commented on src/widgets/header/menu/index.tsx
> +  console.log(user?.role);
Старайся не оставлять консоли в коде

2024-01-13 13:55 UTC, INextYP commented on src/widgets/conflict-information/index.tsx
> +import React from 'react';
Опять тянешь весь реакт.

2024-01-13 13:55 UTC, INextYP commented on src/widgets/conflict-information/index.tsx
> +export const InfoConflict: React.FC<PropsInfoConflict> = (props) => {
1. Деструктуризация пропсов. 
2. FC тяням из реакта

2024-01-13 13:55 UTC, INextYP commented on src/widgets/conflict-information/index.tsx
> +}
У тебя уже есть похожий интерфейс. Приучайся к переиспользованию

2024-05-25 18:46 UTC, merged